ALTER TABLE exercise ADD COLUMN owner_id UUID REFERENCES app_user(id) ON DELETE CASCADE;
CREATE INDEX idx_exercise_owner ON exercise(owner_id,name);

INSERT INTO exercise(id,code,name,muscle_group,equipment) VALUES
(gen_random_uuid(),'CAT_CHEST_BENCH_BAR','Press de banca con barra','Pecho','Barra'),
(gen_random_uuid(),'CAT_CHEST_BENCH_DB','Press de banca con mancuernas','Pecho','Mancuernas'),
(gen_random_uuid(),'CAT_CHEST_INCLINE_BAR','Press inclinado con barra','Pecho','Barra'),
(gen_random_uuid(),'CAT_CHEST_INCLINE_DB','Press inclinado con mancuernas','Pecho','Mancuernas'),
(gen_random_uuid(),'CAT_CHEST_MACHINE','Press de pecho en máquina','Pecho','Máquina'),
(gen_random_uuid(),'CAT_CHEST_FLY_DB','Aperturas con mancuernas','Pecho','Mancuernas'),
(gen_random_uuid(),'CAT_CHEST_FLY_CABLE','Cruce de poleas','Pecho','Polea'),
(gen_random_uuid(),'CAT_CHEST_PUSHUP','Flexiones','Pecho','Peso corporal'),
(gen_random_uuid(),'CAT_BACK_PULLUP','Dominadas','Espalda','Peso corporal'),
(gen_random_uuid(),'CAT_BACK_LAT_PULL','Jalón al pecho','Espalda','Polea'),
(gen_random_uuid(),'CAT_BACK_ROW_BAR','Remo con barra','Espalda','Barra'),
(gen_random_uuid(),'CAT_BACK_ROW_DB','Remo con mancuerna','Espalda','Mancuerna'),
(gen_random_uuid(),'CAT_BACK_ROW_CABLE','Remo sentado en polea','Espalda','Polea'),
(gen_random_uuid(),'CAT_BACK_ROW_MACHINE','Remo en máquina','Espalda','Máquina'),
(gen_random_uuid(),'CAT_BACK_PULLOVER','Pullover en polea','Espalda','Polea'),
(gen_random_uuid(),'CAT_BACK_DEADLIFT','Peso muerto convencional','Espalda','Barra'),
(gen_random_uuid(),'CAT_SHOULDER_PRESS_DB','Press militar con mancuernas','Hombros','Mancuernas'),
(gen_random_uuid(),'CAT_SHOULDER_PRESS_BAR','Press militar con barra','Hombros','Barra'),
(gen_random_uuid(),'CAT_SHOULDER_MACHINE','Press de hombro en máquina','Hombros','Máquina'),
(gen_random_uuid(),'CAT_SHOULDER_LATERAL','Elevaciones laterales','Hombros','Mancuernas'),
(gen_random_uuid(),'CAT_SHOULDER_CABLE','Elevación lateral en polea','Hombros','Polea'),
(gen_random_uuid(),'CAT_SHOULDER_REAR','Pájaros con mancuernas','Hombros','Mancuernas'),
(gen_random_uuid(),'CAT_SHOULDER_FACE_PULL','Face pull','Hombros','Polea'),
(gen_random_uuid(),'CAT_BICEPS_BAR','Curl con barra','Bíceps','Barra'),
(gen_random_uuid(),'CAT_BICEPS_DB','Curl alterno con mancuernas','Bíceps','Mancuernas'),
(gen_random_uuid(),'CAT_BICEPS_HAMMER','Curl martillo','Bíceps','Mancuernas'),
(gen_random_uuid(),'CAT_BICEPS_PREACHER','Curl predicador','Bíceps','Banco predicador'),
(gen_random_uuid(),'CAT_BICEPS_CABLE','Curl de bíceps en polea','Bíceps','Polea'),
(gen_random_uuid(),'CAT_TRICEPS_PUSHDOWN','Extensión de tríceps en polea','Tríceps','Polea'),
(gen_random_uuid(),'CAT_TRICEPS_ROPE','Extensión de tríceps con cuerda','Tríceps','Polea'),
(gen_random_uuid(),'CAT_TRICEPS_OVERHEAD','Extensión de tríceps sobre la cabeza','Tríceps','Mancuerna'),
(gen_random_uuid(),'CAT_TRICEPS_FRENCH','Press francés','Tríceps','Barra EZ'),
(gen_random_uuid(),'CAT_TRICEPS_DIPS','Fondos en paralelas','Tríceps','Peso corporal'),
(gen_random_uuid(),'CAT_QUAD_SQUAT','Sentadilla con barra','Cuádriceps','Barra'),
(gen_random_uuid(),'CAT_QUAD_FRONT','Sentadilla frontal','Cuádriceps','Barra'),
(gen_random_uuid(),'CAT_QUAD_LEG_PRESS','Prensa de piernas','Cuádriceps','Máquina'),
(gen_random_uuid(),'CAT_QUAD_EXTENSION','Extensión de cuádriceps','Cuádriceps','Máquina'),
(gen_random_uuid(),'CAT_QUAD_LUNGE','Zancadas','Cuádriceps','Mancuernas'),
(gen_random_uuid(),'CAT_QUAD_BULGARIAN','Sentadilla búlgara','Cuádriceps','Mancuernas'),
(gen_random_uuid(),'CAT_HAM_CURL_SEATED','Curl femoral sentado','Isquiotibiales','Máquina'),
(gen_random_uuid(),'CAT_HAM_CURL_LYING','Curl femoral tumbado','Isquiotibiales','Máquina'),
(gen_random_uuid(),'CAT_HAM_RDL','Peso muerto rumano','Isquiotibiales','Barra'),
(gen_random_uuid(),'CAT_HAM_GOODMORNING','Buenos días','Isquiotibiales','Barra'),
(gen_random_uuid(),'CAT_GLUTE_HIP_THRUST','Hip thrust','Glúteos','Barra'),
(gen_random_uuid(),'CAT_GLUTE_BRIDGE','Puente de glúteos','Glúteos','Peso corporal'),
(gen_random_uuid(),'CAT_GLUTE_KICKBACK','Patada de glúteo en polea','Glúteos','Polea'),
(gen_random_uuid(),'CAT_GLUTE_ABDUCTION','Abducción de cadera','Glúteos','Máquina'),
(gen_random_uuid(),'CAT_CALF_STANDING','Elevación de gemelos de pie','Gemelos','Máquina'),
(gen_random_uuid(),'CAT_CALF_SEATED','Elevación de gemelos sentado','Gemelos','Máquina'),
(gen_random_uuid(),'CAT_CORE_CRUNCH','Crunch abdominal','Core','Peso corporal'),
(gen_random_uuid(),'CAT_CORE_CABLE','Crunch en polea','Core','Polea'),
(gen_random_uuid(),'CAT_CORE_PLANK','Plancha frontal','Core','Peso corporal'),
(gen_random_uuid(),'CAT_CORE_SIDE_PLANK','Plancha lateral','Core','Peso corporal'),
(gen_random_uuid(),'CAT_CORE_LEG_RAISE','Elevación de piernas','Core','Peso corporal'),
(gen_random_uuid(),'CAT_CORE_PALLOF','Press Pallof','Core','Polea'),
(gen_random_uuid(),'CAT_FOREARM_WRIST','Curl de muñeca','Antebrazos','Mancuernas'),
(gen_random_uuid(),'CAT_FOREARM_REVERSE','Curl inverso','Antebrazos','Barra EZ'),
(gen_random_uuid(),'CAT_FULL_BURPEE','Burpees','Cuerpo completo','Peso corporal'),
(gen_random_uuid(),'CAT_FULL_THRUSTER','Thruster','Cuerpo completo','Mancuernas'),
(gen_random_uuid(),'CAT_FULL_KETTLEBELL','Swing con kettlebell','Cuerpo completo','Kettlebell'),
(gen_random_uuid(),'CAT_CARDIO_TREADMILL','Cinta de correr','Cardio','Cinta'),
(gen_random_uuid(),'CAT_CARDIO_BIKE','Bicicleta estática','Cardio','Bicicleta'),
(gen_random_uuid(),'CAT_CARDIO_ELLIPTICAL','Elíptica','Cardio','Elíptica'),
(gen_random_uuid(),'CAT_CARDIO_ROW','Remo ergómetro','Cardio','Ergómetro'),
(gen_random_uuid(),'CAT_CARDIO_STAIRS','Escaladora','Cardio','Máquina')
ON CONFLICT(code) DO UPDATE SET name=EXCLUDED.name,muscle_group=EXCLUDED.muscle_group,equipment=EXCLUDED.equipment,active=TRUE;
