ALTER TABLE user_reminder_settings
  ADD COLUMN checkin_push BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN nutrition_plan_push BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN workout_plan_push BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN pantry_push BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN daily_tracking_push BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN daily_tracking_email BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN daily_tracking_time TIME NOT NULL DEFAULT '22:30';
