package app.anura.notification;

import app.anura.config.CurrentUser;
import app.anura.error.ApiException;
import java.sql.Time;
import java.time.*;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/reminders")
public class ReminderCenterController {
  private final JdbcTemplate db;private final OnboardingEmailService onboarding;
  ReminderCenterController(JdbcTemplate db,OnboardingEmailService onboarding){this.db=db;this.onboarding=onboarding;}

  @GetMapping
  Map<String,Object> get(){UUID user=CurrentUser.id();Map<String,Object> result=new LinkedHashMap<>();result.put("settings",settingsFor(user));result.put("custom",db.queryForList("SELECT id,title,details,frequency,reminder_time,day_of_week,email_enabled,in_app_enabled,enabled,next_due_at FROM custom_reminder WHERE user_id=? ORDER BY enabled DESC,reminder_time,title",user));result.put("pending",pending(user));return result;}

  @PutMapping("/settings")
  void settings(@RequestBody Settings r){LocalTime tracking=parseTime(Optional.ofNullable(r.dailyTrackingTime()).orElse("22:30"));db.update("INSERT INTO user_reminder_settings(user_id,checkin_email,nutrition_plan_email,workout_plan_email,pantry_email,checkin_push,nutrition_plan_push,workout_plan_push,pantry_push,daily_tracking_push,daily_tracking_email,daily_tracking_time) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET checkin_email=EXCLUDED.checkin_email,nutrition_plan_email=EXCLUDED.nutrition_plan_email,workout_plan_email=EXCLUDED.workout_plan_email,pantry_email=EXCLUDED.pantry_email,checkin_push=EXCLUDED.checkin_push,nutrition_plan_push=EXCLUDED.nutrition_plan_push,workout_plan_push=EXCLUDED.workout_plan_push,pantry_push=EXCLUDED.pantry_push,daily_tracking_push=EXCLUDED.daily_tracking_push,daily_tracking_email=EXCLUDED.daily_tracking_email,daily_tracking_time=EXCLUDED.daily_tracking_time,updated_at=CURRENT_TIMESTAMP",CurrentUser.id(),r.checkinEmail(),r.nutritionPlanEmail(),r.workoutPlanEmail(),r.pantryEmail(),r.checkinPush(),r.nutritionPlanPush(),r.workoutPlanPush(),r.pantryPush(),r.dailyTrackingPush(),r.dailyTrackingEmail(),Time.valueOf(tracking));}

  @PostMapping("/custom")
  Map<String,Object> create(@RequestBody CustomInput r){if(r.title()==null||r.title().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"REMINDER_TITLE_REQUIRED","Escribe un nombre para el recordatorio");String frequency="WEEKLY".equalsIgnoreCase(r.frequency())?"WEEKLY":"DAILY";LocalTime time=parseTime(r.time());Integer day="WEEKLY".equals(frequency)?Optional.ofNullable(r.dayOfWeek()).orElse(LocalDate.now().getDayOfWeek().getValue()):null;UUID id=UUID.randomUUID();db.update("INSERT INTO custom_reminder(id,user_id,title,details,frequency,reminder_time,day_of_week,email_enabled,in_app_enabled,next_due_at) VALUES(?,?,?,?,?,?,?,?,?,?)",id,CurrentUser.id(),r.title().trim(),clean(r.details()),frequency,Time.valueOf(time),day,r.emailEnabled(),r.inAppEnabled(),nextDue(frequency,time,day));return db.queryForMap("SELECT id,title,details,frequency,reminder_time,day_of_week,email_enabled,in_app_enabled,enabled,next_due_at FROM custom_reminder WHERE id=?",id);}

  @PutMapping("/custom/{id}")
  Map<String,Object> update(@PathVariable UUID id,@RequestBody CustomInput r){if(r.title()==null||r.title().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"REMINDER_TITLE_REQUIRED","Escribe un nombre para el recordatorio");String frequency="WEEKLY".equalsIgnoreCase(r.frequency())?"WEEKLY":"DAILY";LocalTime time=parseTime(r.time());Integer day="WEEKLY".equals(frequency)?Optional.ofNullable(r.dayOfWeek()).orElse(LocalDate.now().getDayOfWeek().getValue()):null;int updated=db.update("UPDATE custom_reminder SET title=?,details=?,frequency=?,reminder_time=?,day_of_week=?,email_enabled=?,in_app_enabled=?,next_due_at=?,last_sent_at=NULL,last_acknowledged_at=NULL WHERE id=? AND user_id=?",r.title().trim(),clean(r.details()),frequency,Time.valueOf(time),day,r.emailEnabled(),r.inAppEnabled(),nextDue(frequency,time,day),id,CurrentUser.id());if(updated==0)throw new ApiException(HttpStatus.NOT_FOUND,"REMINDER_NOT_FOUND","Recordatorio no encontrado");return db.queryForMap("SELECT id,title,details,frequency,reminder_time,day_of_week,email_enabled,in_app_enabled,enabled,next_due_at FROM custom_reminder WHERE id=?",id);}

  @DeleteMapping("/custom/{id}") void delete(@PathVariable UUID id){db.update("DELETE FROM custom_reminder WHERE id=? AND user_id=?",id,CurrentUser.id());}
  @PostMapping("/guide") void guide(){onboarding.sendGuide(CurrentUser.id());}
  @PostMapping("/custom/{id}/ack") void acknowledge(@PathVariable UUID id){Map<String,Object> r=db.queryForList("SELECT frequency,reminder_time,day_of_week FROM custom_reminder WHERE id=? AND user_id=?",id,CurrentUser.id()).stream().findFirst().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"REMINDER_NOT_FOUND","Recordatorio no encontrado"));LocalTime time=((Time)r.get("reminder_time")).toLocalTime();db.update("UPDATE custom_reminder SET last_acknowledged_at=CURRENT_TIMESTAMP,next_due_at=? WHERE id=? AND user_id=?",nextDue(String.valueOf(r.get("frequency")),time,(Integer)r.get("day_of_week")),id,CurrentUser.id());}

  private List<Map<String,Object>> pending(UUID user){List<Map<String,Object>> rows=new ArrayList<>();Map<String,Object> checkin=db.queryForList("SELECT MAX(checkin_date) last_date FROM body_checkin WHERE user_id=?",user).getFirst();Object last=checkin.get("last_date");if(last==null||((java.sql.Date)last).toLocalDate().isBefore(LocalDate.now().minusDays(6)))rows.add(alert("CHECKIN","Check-in semanal pendiente","Registra peso, grasa, medidas y fotografías desde el botón +.","WEIGHT",0));addPlan(rows,user,"nutrition_plan","DIET","Dieta");addPlan(rows,user,"workout_plan","WORKOUT","Entrenamiento");Integer shopping=db.queryForObject("SELECT COUNT(*) FROM shopping_list_item i WHERE i.shopping_list_id=(SELECT l.id FROM shopping_list l JOIN nutrition_plan p ON p.id=l.nutrition_plan_id WHERE p.owner_id=? OR EXISTS(SELECT 1 FROM household_member hm WHERE hm.household_id=p.household_id AND hm.user_id=?) ORDER BY l.updated_at DESC,l.created_at DESC LIMIT 1) AND i.purchased=FALSE AND i.quantity>0",Integer.class,user,user);if(shopping!=null&&shopping>0)rows.add(alert("PANTRY","Compra pendiente",shopping+" productos necesitan reposición o confirmación de compra.","SHOPPING",shopping));dailyTracking(user).ifPresent(rows::add);rows.addAll(db.queryForList("SELECT 'CUSTOM' type,title,COALESCE(details,'Recordatorio personal') message,'REMINDERS' action,0 priority,id reference_id FROM custom_reminder WHERE user_id=? AND enabled=TRUE AND in_app_enabled=TRUE AND next_due_at<=CURRENT_TIMESTAMP AND (last_acknowledged_at IS NULL OR last_acknowledged_at<next_due_at)",user));return rows;}
  private void addPlan(List<Map<String,Object>> rows,UUID user,String table,String type,String label){String sql="SELECT name,valid_until FROM "+table+" p WHERE status='ACTIVE' AND "+("nutrition_plan".equals(table)?"(p.owner_id=? OR EXISTS(SELECT 1 FROM household_member hm WHERE hm.household_id=p.household_id AND hm.user_id=?))":"p.user_id=?")+" ORDER BY created_at DESC LIMIT 1";List<Map<String,Object>> found="nutrition_plan".equals(table)?db.queryForList(sql,user,user):db.queryForList(sql,user);if(found.isEmpty())return;Object raw=found.getFirst().get("valid_until");if(raw==null)return;LocalDate end=raw instanceof LocalDate d?d:((java.sql.Date)raw).toLocalDate();long days=java.time.temporal.ChronoUnit.DAYS.between(LocalDate.now(),end);if(days<=1)rows.add(alert(type,label+(days<0?" caducado":" por renovar"),days<0?"El plan ya ha terminado.":days==0?"Termina hoy.":"Queda 1 día. Genera el prompt y prepara la siguiente versión.",type,days<0?100:9));}
  private Map<String,Object> alert(String type,String title,String message,String action,int priority){Map<String,Object> row=new LinkedHashMap<>();row.put("type",type);row.put("title",title);row.put("message",message);row.put("action",action);row.put("priority",priority);return row;}
  List<Map<String,Object>> pushPending(UUID user){Map<String,Object> s=settingsFor(user);List<Map<String,Object>> rows=new ArrayList<>(pending(user).stream().filter(row->switch(String.valueOf(row.get("type"))){case"CHECKIN"->flag(s,"checkin_push");case"DIET"->flag(s,"nutrition_plan_push");case"WORKOUT"->flag(s,"workout_plan_push");case"PANTRY"->flag(s,"pantry_push");case"DAILY_TRACKING"->flag(s,"daily_tracking_push");default->true;}).toList());cycleReminder(user).ifPresent(rows::add);return rows;}
  private Optional<Map<String,Object>> cycleReminder(UUID user){List<Map<String,Object>> cycles=db.queryForList("SELECT id,start_date FROM menstrual_cycle_record WHERE user_id=? AND end_date IS NULL AND start_date<=CURRENT_DATE-7 ORDER BY start_date DESC LIMIT 1",user);if(cycles.isEmpty())return Optional.empty();Map<String,Object> cycle=cycles.getFirst(),row=alert("CYCLE_"+LocalDate.now().with(DayOfWeek.MONDAY),"Periodo en curso","Hace una semana que registraste el inicio. Cuando se te vaya, añade la fecha de fin para completar el ciclo.","CYCLE",4);row.put("reference_id",cycle.get("id"));return Optional.of(row);}
  Optional<Map<String,Object>> dailyTracking(UUID user){Map<String,Object> s=settingsFor(user);LocalTime due=((Time)s.get("daily_tracking_time")).toLocalTime();if(LocalTime.now(ZoneId.of("Europe/Madrid")).isBefore(due))return Optional.empty();List<String> missing=new ArrayList<>();Integer meals=db.queryForObject("SELECT COUNT(*) FROM nutrition_plan p JOIN nutrition_plan_day d ON d.nutrition_plan_id=p.id JOIN planned_meal pm ON pm.nutrition_plan_day_id=d.id JOIN user_meal_portion ump ON ump.planned_meal_id=pm.id AND ump.user_id=? WHERE p.status='ACTIVE' AND (p.owner_id=? OR EXISTS(SELECT 1 FROM household_member hm WHERE hm.household_id=p.household_id AND hm.user_id=?)) AND d.day_number=EXTRACT(ISODOW FROM CURRENT_DATE)::int AND NOT EXISTS(SELECT 1 FROM consumed_meal cm WHERE cm.user_id=? AND cm.planned_meal_id=pm.id AND cm.meal_date=CURRENT_DATE) AND NOT EXISTS(SELECT 1 FROM nutrition_travel_mode t JOIN household_member hm ON hm.household_id=t.household_id WHERE hm.user_id=? AND t.status='ACTIVE' AND CURRENT_DATE BETWEEN t.start_date AND t.end_date)",Integer.class,user,user,user,user,user);if(meals!=null&&meals>0)missing.add(meals+" comida"+(meals==1?"":"s"));Boolean workout=db.queryForObject("SELECT (EXISTS(SELECT 1 FROM workout_plan p JOIN workout_plan_day d ON d.workout_plan_id=p.id WHERE p.user_id=? AND p.status='ACTIVE' AND d.day_number=EXTRACT(ISODOW FROM CURRENT_DATE)::int AND NOT EXISTS(SELECT 1 FROM workout_day_adjustment a WHERE a.user_id=? AND a.workout_plan_day_id=d.id AND a.original_date=CURRENT_DATE AND a.status IN ('MOVED','SKIPPED'))) OR EXISTS(SELECT 1 FROM workout_day_adjustment a WHERE a.user_id=? AND a.status='MOVED' AND a.scheduled_date=CURRENT_DATE)) AND NOT EXISTS(SELECT 1 FROM workout_session s WHERE s.user_id=? AND s.planned_date=CURRENT_DATE AND s.status IN ('COMPLETED','ABANDONED') AND s.deleted_at IS NULL)",Boolean.class,user,user,user,user);if(Boolean.TRUE.equals(workout))missing.add("entrenamiento");Boolean sleep=db.queryForObject("SELECT NOT EXISTS(SELECT 1 FROM sleep_session WHERE user_id=? AND sleep_date=CURRENT_DATE)",Boolean.class,user);if(Boolean.TRUE.equals(sleep))missing.add("sueño");if(missing.isEmpty())return Optional.empty();String message="Te falta registrar "+String.join(", ",missing)+" antes de cerrar el día.";return Optional.of(alert("DAILY_TRACKING","Completa el seguimiento de hoy",message,"HOME",8));}
  Map<String,Object> settingsFor(UUID user){return db.queryForList("SELECT checkin_email,nutrition_plan_email,workout_plan_email,pantry_email,checkin_push,nutrition_plan_push,workout_plan_push,pantry_push,daily_tracking_push,daily_tracking_email,daily_tracking_time FROM user_reminder_settings WHERE user_id=?",user).stream().findFirst().orElseGet(()->{Map<String,Object> defaults=new LinkedHashMap<>();for(String key:List.of("checkin_email","nutrition_plan_email","workout_plan_email","pantry_email","checkin_push","nutrition_plan_push","workout_plan_push","pantry_push","daily_tracking_push"))defaults.put(key,true);defaults.put("daily_tracking_email",false);defaults.put("daily_tracking_time",Time.valueOf("22:30:00"));return defaults;});}
  private static boolean flag(Map<String,Object> settings,String key){return Boolean.TRUE.equals(settings.get(key));}
  private static LocalTime parseTime(String value){try{return LocalTime.parse(value==null?"09:00":value);}catch(Exception e){return LocalTime.of(9,0);}}
  static OffsetDateTime nextDue(String frequency,LocalTime time,Integer day){ZoneId zone=ZoneId.of("Europe/Madrid");ZonedDateTime now=ZonedDateTime.now(zone),next=now.with(time).withSecond(0).withNano(0);if("WEEKLY".equals(frequency)){int delta=(day-now.getDayOfWeek().getValue()+7)%7;next=next.plusDays(delta);if(!next.isAfter(now))next=next.plusWeeks(1);}else if(!next.isAfter(now))next=next.plusDays(1);return next.toOffsetDateTime();}
  private static String clean(String value){return value==null||value.isBlank()?null:value.trim();}
  record Settings(boolean checkinEmail,boolean nutritionPlanEmail,boolean workoutPlanEmail,boolean pantryEmail,boolean checkinPush,boolean nutritionPlanPush,boolean workoutPlanPush,boolean pantryPush,boolean dailyTrackingPush,boolean dailyTrackingEmail,String dailyTrackingTime){}
  record CustomInput(String title,String details,String frequency,String time,Integer dayOfWeek,boolean emailEnabled,boolean inAppEnabled){}
}
