package app.anura.notification;

import java.sql.Time;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

@Service
public class ReminderEmailService {
  private final JdbcTemplate db;private final EmailService email;
  ReminderEmailService(JdbcTemplate db,EmailService email){this.db=db;this.email=email;}
  @Scheduled(cron="0 */10 * * * *",zone="Europe/Madrid") void custom(){if(!email.enabled())return;for(Map<String,Object> r:db.queryForList("SELECT r.id,r.title,r.details,u.email FROM custom_reminder r JOIN app_user u ON u.id=r.user_id WHERE r.enabled=TRUE AND r.email_enabled=TRUE AND r.next_due_at<=CURRENT_TIMESTAMP AND (r.last_sent_at IS NULL OR r.last_sent_at<r.next_due_at)")){try{email.send(String.valueOf(r.get("email")),"Recordatorio ANURA · "+r.get("title"),"Es el momento de "+r.get("title")+".\n\n"+Optional.ofNullable(r.get("details")).orElse("Abre ANURA para revisar tus pendientes."));db.update("UPDATE custom_reminder SET last_sent_at=CURRENT_TIMESTAMP WHERE id=?",r.get("id"));}catch(Exception ignored){}}}
  @Scheduled(cron="0 0 9 * * *",zone="Europe/Madrid") void system(){if(!email.enabled())return;for(Map<String,Object> u:db.queryForList("SELECT u.id,u.email,u.display_name,COALESCE(s.checkin_email,TRUE) checkin_email,COALESCE(s.workout_plan_email,TRUE) workout_plan_email,COALESCE(s.pantry_email,TRUE) pantry_email FROM app_user u LEFT JOIN user_reminder_settings s ON s.user_id=u.id WHERE u.enabled=TRUE")){UUID id=(UUID)u.get("id");String address=String.valueOf(u.get("email")),name=String.valueOf(u.get("display_name"));if(Boolean.TRUE.equals(u.get("checkin_email")))checkin(id,address,name);if(Boolean.TRUE.equals(u.get("workout_plan_email")))workout(id,address,name);if(Boolean.TRUE.equals(u.get("pantry_email")))pantry(id,address,name);}}
  private void checkin(UUID user,String address,String name){Object last=db.queryForObject("SELECT MAX(checkin_date) FROM body_checkin WHERE user_id=?",Object.class,user);if(last!=null&&!toDate(last).isBefore(LocalDate.now().minusDays(6)))return;String week=LocalDate.now().getYear()+"-"+LocalDate.now().get(java.time.temporal.IsoFields.WEEK_OF_WEEK_BASED_YEAR);sendOnce(user,"CHECKIN",week,address,"Tu check-in semanal está pendiente","Hola "+name+",\n\nRegistra tu check-in semanal en Evolución para mantener al día peso, medidas y seguimiento.");}
  private void workout(UUID user,String address,String name){for(Map<String,Object> p:db.queryForList("SELECT id,name,valid_until FROM workout_plan WHERE user_id=? AND status='ACTIVE' AND valid_until<=CURRENT_DATE+1",user)){LocalDate end=toDate(p.get("valid_until"));long days=java.time.temporal.ChronoUnit.DAYS.between(LocalDate.now(),end);sendOnce(user,"WORKOUT_PLAN",String.valueOf(p.get("id")),address,"Tu plan de entrenamiento necesita revisión","Hola "+name+",\n\nA tu plan \""+p.get("name")+"\" "+(days<0?"ya se le ha pasado la fecha":days==0?"le queda hoy":"le queda 1 día")+". Genera el prompt actualizado y prepara la siguiente versión.");}}
  private void pantry(UUID user,String address,String name){List<Map<String,Object>> lists=db.queryForList("SELECT l.id,COUNT(*) products FROM shopping_list l JOIN nutrition_plan p ON p.id=l.nutrition_plan_id JOIN shopping_list_item i ON i.shopping_list_id=l.id WHERE i.purchased=FALSE AND i.quantity>0 AND (p.owner_id=? OR EXISTS(SELECT 1 FROM household_member hm WHERE hm.household_id=p.household_id AND hm.user_id=?)) GROUP BY l.id ORDER BY MAX(l.created_at) DESC LIMIT 1",user,user);if(lists.isEmpty())return;Map<String,Object> list=lists.getFirst();sendOnce(user,"PANTRY",String.valueOf(list.get("id")),address,"Hay productos pendientes en la compra","Hola "+name+",\n\nANURA ha detectado "+list.get("products")+" productos que necesitan reposición o confirmar su compra. Abre Nutrición → Compra.");}
  private void sendOnce(UUID user,String type,String reference,String address,String subject,String body){Boolean sent=db.queryForObject("SELECT EXISTS(SELECT 1 FROM reminder_delivery_log WHERE user_id=? AND reminder_type=? AND reference_key=?)",Boolean.class,user,type,reference);if(Boolean.TRUE.equals(sent))return;try{email.send(address,subject,body);db.update("INSERT INTO reminder_delivery_log(user_id,reminder_type,reference_key) VALUES(?,?,?)",user,type,reference);}catch(Exception ignored){}}
  private static LocalDate toDate(Object value){return value instanceof LocalDate d?d:((java.sql.Date)value).toLocalDate();}
}
