package app.anura.notification;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Security;
import java.net.URI;
import java.util.*;
import nl.martijndwars.webpush.Encoding;
import nl.martijndwars.webpush.Notification;
import nl.martijndwars.webpush.PushService;
import nl.martijndwars.webpush.Utils;
import org.bouncycastle.jce.ECNamedCurveTable;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.jce.spec.ECPublicKeySpec;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.apache.http.util.EntityUtils;

@Service
public class WebPushService {
  private static final Logger log=LoggerFactory.getLogger(WebPushService.class);
  private final JdbcTemplate db;private final ObjectMapper json;private final ReminderCenterController reminders;
  private final boolean configured;private final String publicKey;private final PushService push;
  WebPushService(JdbcTemplate db,ObjectMapper json,ReminderCenterController reminders,@Value("${app.push.enabled:false}") boolean enabled,@Value("${app.push.public-key:}") String publicKey,@Value("${app.push.private-key:}") String privateKey,@Value("${app.push.subject:mailto:soporte@anura.app}") String subject){
    this.db=db;this.json=json;this.reminders=reminders;this.publicKey=cleanSecret(publicKey);String cleanPrivateKey=cleanSecret(privateKey);this.configured=enabled&&!this.publicKey.isBlank()&&!cleanPrivateKey.isBlank();PushService ready=null;
    if(configured)try{if(Security.getProvider(BouncyCastleProvider.PROVIDER_NAME)==null)Security.addProvider(new BouncyCastleProvider());ready=new PushService();ready.setPublicKey(Utils.loadPublicKey(this.publicKey));ready.setPrivateKey(Utils.loadPrivateKey(cleanPrivateKey));ready.setSubject(normalizeSubject(subject));}catch(Exception exception){throw new IllegalStateException("La configuración VAPID de Web Push no es válida",exception);}this.push=ready;
  }
  boolean enabled(){return configured;}String publicKey(){return configured?publicKey:"";}
  void sendTest(UUID user){if(!configured)throw new app.anura.error.ApiException(HttpStatus.SERVICE_UNAVAILABLE,"WEB_PUSH_NOT_CONFIGURED","Web Push todavía no está configurado en el servidor");DeliveryResult result=sendToUser(user,"ANURA ya puede avisarte","Las notificaciones están activadas correctamente.","HOME","test:"+System.currentTimeMillis(),0);if(result.attempted()==0)throw new app.anura.error.ApiException(HttpStatus.CONFLICT,"WEB_PUSH_NO_SUBSCRIPTION","Este dispositivo no tiene una suscripción activa. Desactiva y vuelve a activar las notificaciones.");if(result.delivered()==0)throw new app.anura.error.ApiException(HttpStatus.BAD_GATEWAY,"WEB_PUSH_DELIVERY_FAILED","El servicio de notificaciones rechazó el envío. Desactiva y vuelve a activar las notificaciones en este dispositivo.");}
  @Scheduled(cron="0 */10 * * * *",zone="Europe/Madrid") void dispatchDue(){if(!configured)return;int hour=java.time.ZonedDateTime.now(java.time.ZoneId.of("Europe/Madrid")).getHour();boolean quiet=hour<8||hour>=22;for(UUID user:db.query("SELECT DISTINCT user_id FROM web_push_subscription WHERE enabled=TRUE",(row,index)->row.getObject(1,UUID.class))){try{List<Map<String,Object>> due=reminders.pushPending(user);for(Map<String,Object> reminder:due){String type=String.valueOf(reminder.get("type"));if(quiet&&!Set.of("CUSTOM","DAILY_TRACKING").contains(type))continue;String message=String.valueOf(reminder.get("message")),action=String.valueOf(reminder.get("action"));sendToUser(user,String.valueOf(reminder.get("title")),message,action,referenceKey(user,reminder),due.size());}}catch(Exception exception){log.warn("No se pudieron procesar los avisos Push del usuario {}",user,exception);}}}
  @Scheduled(fixedDelay=1000) void dispatchRestTimers(){if(!configured)return;for(Map<String,Object> timer:db.queryForList("SELECT id,user_id,client_timer_id FROM web_push_rest_timer WHERE status='PENDING' AND end_at<=CURRENT_TIMESTAMP ORDER BY end_at LIMIT 20")){UUID id=(UUID)timer.get("id");if(db.update("UPDATE web_push_rest_timer SET status='SENDING' WHERE id=? AND status='PENDING'",id)!=1)continue;try{DeliveryResult result=sendToUser((UUID)timer.get("user_id"),"Descanso terminado","Vamos a por la siguiente serie.","WORKOUT","rest:"+timer.get("client_timer_id"),0);db.update("UPDATE web_push_rest_timer SET status=?,sent_at=CASE WHEN ?>0 THEN CURRENT_TIMESTAMP ELSE NULL END WHERE id=?",result.delivered()>0?"SENT":"FAILED",result.delivered(),id);}catch(Exception exception){db.update("UPDATE web_push_rest_timer SET status='FAILED' WHERE id=?",id);log.warn("No se pudo completar el aviso de descanso {}",id,exception);}}db.update("DELETE FROM web_push_rest_timer WHERE created_at<CURRENT_TIMESTAMP-INTERVAL '1 day'");}
  private String referenceKey(UUID user,Map<String,Object> reminder){String type=String.valueOf(reminder.get("type")),fallback=String.valueOf(reminder.get("message"));Object id=reminder.get("reference_id");if("DAILY_TRACKING".equals(type))return type+":"+java.time.LocalDate.now(java.time.ZoneId.of("Europe/Madrid"));if("CUSTOM".equals(type)&&id!=null){Object due=db.queryForList("SELECT next_due_at FROM custom_reminder WHERE id=?",id).stream().findFirst().map(row->row.get("next_due_at")).orElse("unknown");return type+":"+id+":"+due;}if("CHECKIN".equals(type)){Object latest=db.queryForObject("SELECT COALESCE(MAX(checkin_date)::text,'none') FROM body_checkin WHERE user_id=?",Object.class,user);return type+":"+latest;}if("PANTRY".equals(type)){Object list=db.queryForList("SELECT l.id FROM shopping_list l JOIN nutrition_plan p ON p.id=l.nutrition_plan_id WHERE p.owner_id=? OR EXISTS(SELECT 1 FROM household_member hm WHERE hm.household_id=p.household_id AND hm.user_id=?) ORDER BY l.updated_at DESC LIMIT 1",user,user).stream().findFirst().map(row->row.get("id")).orElse("none");return type+":"+list+":"+fallback;}if("DIET".equals(type)){Object plan=db.queryForList("SELECT id FROM nutrition_plan p WHERE status='ACTIVE' AND (p.owner_id=? OR EXISTS(SELECT 1 FROM household_member hm WHERE hm.household_id=p.household_id AND hm.user_id=?)) ORDER BY created_at DESC LIMIT 1",user,user).stream().findFirst().map(row->row.get("id")).orElse("none");return type+":"+plan+":"+fallback;}if("WORKOUT".equals(type)){Object plan=db.queryForList("SELECT id FROM workout_plan WHERE user_id=? AND status='ACTIVE' ORDER BY created_at DESC LIMIT 1",user).stream().findFirst().map(row->row.get("id")).orElse("none");return type+":"+plan+":"+fallback;}return type+":"+fallback;}
  private DeliveryResult sendToUser(UUID user,String title,String body,String action,String reference,int badge){int attempted=0,deliveredCount=0;for(Map<String,Object> subscription:db.queryForList("SELECT id,endpoint,p256dh,auth FROM web_push_subscription WHERE user_id=? AND enabled=TRUE",user)){UUID id=(UUID)subscription.get("id");String endpoint=String.valueOf(subscription.get("endpoint"));Boolean delivered=db.queryForObject("SELECT EXISTS(SELECT 1 FROM web_push_delivery_log WHERE subscription_id=? AND reference_key=?)",Boolean.class,id,reference);if(Boolean.TRUE.equals(delivered))continue;attempted++;try{byte[] payload=json.writeValueAsBytes(Map.of("title",title,"body",body,"action",action,"url","/?anuraAction="+action,"badge",badge,"tag","anura-"+action.toLowerCase(Locale.ROOT)));Notification notification=new Notification(endpoint,userPublicKey(String.valueOf(subscription.get("p256dh"))),decode(String.valueOf(subscription.get("auth"))),payload,3600);var response=push.send(notification,Encoding.AES128GCM);int status=response.getStatusLine().getStatusCode();if(status>=200&&status<300){deliveredCount++;db.update("UPDATE web_push_subscription SET last_success_at=CURRENT_TIMESTAMP,last_seen_at=CURRENT_TIMESTAMP WHERE id=?",id);db.update("INSERT INTO web_push_delivery_log(subscription_id,reference_key) VALUES(?,?) ON CONFLICT DO NOTHING",id,reference);}else{String provider=URI.create(endpoint).getHost(),detail=response.getEntity()==null?"":EntityUtils.toString(response.getEntity());log.warn("Web Push rechazado para suscripción {} en {} con HTTP {}: {}",id,provider,status,detail);if(status==404||status==410)db.update("UPDATE web_push_subscription SET enabled=FALSE WHERE id=?",id);}}catch(Exception exception){log.warn("No se pudo enviar Web Push a la suscripción {}: {}",id,exception.getMessage(),exception);}}return new DeliveryResult(attempted,deliveredCount);}
  private static PublicKey userPublicKey(String encoded)throws Exception{var spec=ECNamedCurveTable.getParameterSpec("secp256r1");return KeyFactory.getInstance("ECDH",BouncyCastleProvider.PROVIDER_NAME).generatePublic(new ECPublicKeySpec(spec.getCurve().decodePoint(decode(encoded)),spec));}
  private static byte[] decode(String value){return Base64.getUrlDecoder().decode(pad(value));}private static String pad(String value){String clean=value.replace('+','-').replace('/','_').replace("=","");return clean+"=".repeat((4-clean.length()%4)%4);}private static String cleanSecret(String value){String clean=value==null?"":value.trim();if(clean.length()>=2&&((clean.startsWith("\"")&&clean.endsWith("\""))||(clean.startsWith("'")&&clean.endsWith("'"))))return clean.substring(1,clean.length()-1).trim();return clean;}
  private static String normalizeSubject(String value){String clean=cleanSecret(value);if(clean.isBlank())return"https://anura-frontend-production.up.railway.app";if(clean.startsWith("https://"))return clean;int open=clean.indexOf('<'),close=clean.indexOf('>');if(open>=0&&close>open)clean=clean.substring(open+1,close).trim();if(clean.startsWith("mailto:"))clean=clean.substring(7).trim();clean=clean.replace("<","").replace(">","").trim();if(clean.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"))return"mailto:"+clean;throw new IllegalArgumentException("WEB_PUSH_SUBJECT debe ser un correo simple o una URL https");}
  private record DeliveryResult(int attempted,int delivered){}
}
