import { useEffect,useMemo,useRef,useState } from "react";
import { createPortal } from "react-dom";
import { Activity,Bot,Camera,ChevronDown,Copy,Edit3,Flame,Plus,Save,Scale,Trash2,TrendingDown,TrendingUp,X } from "lucide-react";
import { api,bodyProgressApi,householdApi,nutritionApi,workoutApi,workRoutineApi,type BodyCheckin,type BodyCheckinInput,type BodyEvolution,type EvolutionPoint } from "./api";
import { AdherenceCard } from "./AdherenceCard";

type Range="1M"|"3M"|"6M"|"1Y"|"ALL";type Metric="weight"|"waistCm"|"chestCm"|"hipCm"|"arms"|"thighs";
const metrics:Array<{id:Metric;label:string;unit:string}>=[{id:"weight",label:"Peso",unit:"kg"},{id:"waistCm",label:"Cintura",unit:"cm"},{id:"chestCm",label:"Pecho",unit:"cm"},{id:"hipCm",label:"Cadera",unit:"cm"},{id:"arms",label:"Brazos",unit:"cm"},{id:"thighs",label:"Muslos",unit:"cm"}];

export function BodyProgress({addSignal=0}:{addSignal?:number}){
 const previousAddSignal=useRef(addSignal);
 const [rows,setRows]=useState<BodyCheckin[]>([]),[evolution,setEvolution]=useState<BodyEvolution|null>(null),[adherence,setAdherence]=useState<Awaited<ReturnType<typeof nutritionApi.adherence>>|null>(null),[hasNutritionPlan,setHasNutritionPlan]=useState(false),[avatar,setAvatar]=useState(""),[range,setRange]=useState<Range>("3M"),[metric,setMetric]=useState<Metric>("weight"),[editing,setEditing]=useState<BodyCheckin|null|undefined>(undefined),[deleting,setDeleting]=useState<BodyCheckin|null>(null),[loading,setLoading]=useState(true),[intro,setIntro]=useState(true),[error,setError]=useState(""),[saved,setSaved]=useState(""),[report,setReport]=useState(""),[reportBusy,setReportBusy]=useState(false);
 const dates=useMemo(()=>period(range),[range]);
 const load=async()=>{setLoading(true);setError("");try{const [list,trend,ad,profile,plans]=await Promise.all([bodyProgressApi.list(),bodyProgressApi.evolution(dates.from,dates.to),nutritionApi.adherence().catch(()=>null),api.profilePreferences().catch(()=>null),nutritionApi.plans().catch(()=>[])]);setRows(list);setEvolution(trend);setAdherence(ad);setHasNutritionPlan(plans.length>0);setAvatar(profile?.avatar_url||"")}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo cargar la evolución")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[dates.from,dates.to]);
 useEffect(()=>{setIntro(false)},[]);
 useEffect(()=>{if(addSignal!==previousAddSignal.current)setEditing(null);previousAddSignal.current=addSignal},[addSignal]);
 if(loading||intro)return <div className="progress-loading" aria-live="polite">Cargando evolución…</div>;
 const latest=rows[0];
 const currentWeek=adherence?.currentWeek,weekComplete=currentWeek?.complete===true;
 return <section className="body-progress">
  {!rows.length&&<div className="progress-fab-hint"><Plus/><span><b>Registra tu check-in desde el botón +</b><small>Peso, grasa, medidas y fotografías quedan reunidos aquí.</small></span></div>}
  <div className="body-summary"><div className="body-summary-head"><span><small>EVOLUCIÓN CORPORAL</small><h2>{latest?`${Number(latest.weight).toFixed(1)} kg`:"Tu punto de partida"}</h2><p>{latest?`Último check-in · ${formatDate(latest.checkinDate)}`:"Registra tu primer check-in semanal"}</p></span></div>{latest&&<div className="body-kpis"><Kpi label="Último cambio" value={signed(evolution?.previousWeightChange,"kg")} tone={(evolution?.previousWeightChange||0)<=0?"good":"warm"}/><Kpi label="En el periodo" value={signed(evolution?.totalWeightChange,"kg")} tone="neutral"/><Kpi label="Racha semanal" value={`${evolution?.weeklyStreak||0} sem.`} tone="lime"/><Kpi label="Check-ins" value={String(evolution?.checkinCount||0)} tone="neutral"/></div>}</div>
  <div className="progress-range">{(["1M","3M","6M","1Y","ALL"] as Range[]).map(r=><button className={range===r?"active":""} onClick={()=>setRange(r)} key={r}>{r==="ALL"?"Todo":r}</button>)}</div>
  {adherence&&<AdherenceCard data={adherence} mode="total"/>}
  {weekComplete&&<section className="weekly-celebration" aria-live="polite"><div className="celebration-avatar"><img src={avatar||"/anura-mascot.png"} alt="Tu avatar celebrando la semana completada"/><i/><i/><i/></div><span><small>SEMANA COMPLETADA</small><h3>Lo estás haciendo increíble.</h3><p>Has completado tu nutrición y tus entrenamientos previstos. La constancia ya está haciendo su trabajo.</p></span><strong>100%<small>esta semana</small></strong></section>}
  {error&&<div className="error">{error}<button onClick={()=>void load()}>Reintentar</button></div>}{saved&&<div className="progress-saved"><Save/>{saved}</div>}
  <section className="coach-report"><div className="coach-report-head"><Bot/><span><small>EXPEDIENTE PARA CHATGPT</small><h3>{hasNutritionPlan?"Prepara la siguiente versión de tu plan":rows.length?"Tu seguimiento completo, sin perder contexto":"Crea tu primer plan desde tus datos iniciales"}</h3><p>{rows.length?"Incluye planes anteriores, ejecución real y evolución cronológica para comparar lo previsto con lo realizado.":"No necesitas registrar peso antes. Incluye perfil, objetivos, trabajo, turnos y, si perteneces a una unidad doméstica, los datos autorizados de todos sus miembros."}</p></span><button disabled={reportBusy} onClick={async()=>{setReportBusy(true);try{setReport(await buildCoachPrompt(rows,evolution))}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo generar el informe")}finally{setReportBusy(false)}}}>{reportBusy?"Recopilando…":rows.length?"Generar prompt completo":"Generar prompt inicial"}</button></div>{report&&<div className="coach-report-output"><textarea readOnly value={report}/><button onClick={()=>void navigator.clipboard.writeText(report)}><Copy/>Copiar para ChatGPT</button></div>}</section>
  {!rows.length?<div className="body-empty"><Scale/><h3>Empieza a ver tu tendencia</h3><p>Un check-in semanal es suficiente para entender el rumbo sin obsesionarte con cada día.</p><button onClick={()=>setEditing(null)}>Registrar primer check-in</button></div>:<>
   <div className="metric-tabs">{metrics.map(m=><button key={m.id} className={metric===m.id?"active":""} onClick={()=>setMetric(m.id)}>{m.label}</button>)}</div>
   <ProgressChart points={evolution?.points||[]} metric={metric}/>
   <div className="trend-strip">{evolution?.trend==="UP"?<TrendingUp/>:<TrendingDown/>}<span><b>{evolution?.minimumWeight?.toFixed(1)}–{evolution?.maximumWeight?.toFixed(1)} kg</b><small>Rango de peso del periodo · La media móvil aparece cuando hay datos suficientes</small></span></div>
   <h2 className="progress-history-title">Historial de check-ins</h2><div className="checkin-history">{rows.map((row,index)=><CheckinCard key={row.id} row={row} previous={rows[index+1]} edit={()=>setEditing(row)} remove={()=>setDeleting(row)}/>)}</div>
  </>}
  {editing!==undefined&&<CheckinModal value={editing} onClose={()=>setEditing(undefined)} onSaved={async()=>{setEditing(undefined);setSaved("Check-in guardado");await load();setTimeout(()=>setSaved(""),2500)}}/>}
  {deleting&&<ConfirmDelete row={deleting} close={()=>setDeleting(null)} confirm={async()=>{await bodyProgressApi.remove(deleting.id);setDeleting(null);setSaved("Check-in eliminado");await load()}}/>}
 </section>
}

async function buildCoachPrompt(checkins:BodyCheckin[],evolution:BodyEvolution|null){
 const [entries,profile,cycles,supplements,nutritionPreferences,workRoutine,adherence,targets,nutritionPlans,consumedMeals,workoutPlans,workoutHistory]=await Promise.all([
  api.entries().catch(()=>[]),api.profilePreferences().catch(()=>null),api.cycles().catch(()=>[]),api.supplements().catch(()=>[]),nutritionApi.preferences().catch(()=>null),workRoutineApi.get().catch(()=>null),nutritionApi.adherence().catch(()=>null),nutritionApi.targets().catch(()=>[]),nutritionApi.plans().catch(()=>[]),nutritionApi.consumedMeals().catch(()=>[]),workoutApi.plans().catch(()=>[]),allWorkoutHistory().catch(()=>[])
 ]);
 const dietPlans=await Promise.all(nutritionPlans.slice(0,2).map(async plan=>({plan,meals:await nutritionApi.planDetails(plan.id).catch(()=>[])})));
 const household=(await householdApi.list().catch(()=>[]))[0];
 const householdContext=household?await householdApi.promptContext(household.id).catch(()=>null):null;
 const trainingPlans=await Promise.all(workoutPlans.slice(0,2).map(async plan=>({plan,exercises:await workoutApi.planDetails(plan.id).catch(()=>[])})));
 const realSessions=await Promise.all(workoutHistory.map(item=>workoutApi.one(item.id).catch(()=>null)));
 const cycleText=profile?.biological_sex==="FEMALE"?(cycles.map(c=>`- ${c.start_date}${c.end_date?` a ${c.end_date}`:" (en curso)"} | flujo ${fmt(c.flow_level)} | síntomas ${fmt(c.symptoms)} | notas ${fmt(c.notes)}`).join("\n")||"- Sin periodos registrados"):"- No aplica o no indicado";
 const baseGoals=entries.filter(entry=>entry.type==="GOAL").map(entry=>`- ${entry.title}: ${entry.value??"sin valor"}${entry.unit||""}${entry.details?` | ${entry.details}`:""}${entry.notes?` | Notas: ${entry.notes}`:""}`).join("\n")||"- Sin objetivos registrados";
 const supplementText=supplements.length?supplements.map(item=>`- ${item.name} | ${item.active?"activo":"pausado"} | dosis ${fmt(item.dose)} | horario ${fmt(item.schedule)} | motivo ${fmt(item.purpose)} | notas ${fmt(item.notes)}`).join("\n"):"- Ninguno registrado";
 if(nutritionPreferences)Object.assign(nutritionPreferences,{anuraPlanningRules:["Usar primero las existencias reales de la despensa doméstica incluidas en el contexto.","Descontar el consumo previsto semana a semana y reponer solo cuando quede menos de lo necesario para la siguiente semana.","Tratar las cantidades marcadas como compradas como inventario real y aprovechar formatos abiertos antes de introducir otros equivalentes."]});
 const statedGoals=`${baseGoals}\n\nPREFERENCIAS Y CONTEXTO ALIMENTARIO\n${nutritionPreferences?JSON.stringify(nutritionPreferences,null,2):"Sin preferencias registradas"}\n\nREGLAS DE PLANIFICACIÓN Y COCINA\n- Minimiza desperdicio: agrupa ingredientes durante la semana, reutiliza productos abiertos y planifica sobrantes deliberados. No introduzcas un producto perecedero para una sola toma y lo abandones durante semanas.\n- Respeta gustos, exclusiones, bebidas habituales y notas de cada miembro; no conviertas una preferencia de una persona en la de toda la casa.\n- Usa porciones domésticas medibles: huevos enteros o medios preparados, yogures por envase o gramos razonables, piezas, latas, rebanadas y cantidades redondeadas. Evita indicaciones inviables como 40 g de huevo cocido.\n- Para una unidad compartida indica en cada receta: cantidad de cada ingrediente para cada persona y total conjunto a cocinar, explicando cómo repartirlo.\n- Diseña la compra según formatos comerciales razonables e indica qué sobrante queda para comidas posteriores. Mantén las unidades normalizadas para ANURA.\n- Mantén estable el catálogo entre versiones: reutiliza exactamente los códigos, nombres canónicos y unidades de los ingredientes y recetas ya presentes en los planes anteriores. No cambies singular/plural, abreviaturas, acentos, estado (crudo/cocido) ni unidad para un mismo producto. Crea un código nuevo solo si el alimento o la receta son realmente distintos. Si necesitas corregir una denominación, indícalo expresamente como migración en vez de crear silenciosamente otro ingrediente. Esta estabilidad es necesaria para enlazar la despensa y el histórico de ANURA.\n\nSUPLEMENTOS ACTUALES\n${supplementText}\nTenlos en cuenta para evitar duplicidades. Separa claramente cualquier complemento nuevo que propongas, explica el motivo y advierte que debe revisarse frente a medicación, patologías y analíticas con un profesional sanitario.`;
 const goals=`${statedGoals}\n\nHISTORIAL MENSTRUAL\n${cycleText}\nUsa el ciclo solo como contexto individual de síntomas, recuperación y tolerancia observada. No presupongas menor rendimiento por una fase; adapta el entreno únicamente cuando los datos y sensaciones lo justifiquen.\n\nRUTINA LABORAL, PLANTILLAS Y CALENDARIO PROPIOS\n${workRoutine?JSON.stringify(workRoutine,null,2):"Sin datos laborales"}${householdContext?`\n\nUNIDAD DOMÉSTICA Y EXPEDIENTE COMPLETO DE TODOS LOS MIEMBROS\n${JSON.stringify(householdContext,null,2)}\n\nUsa para cada persona sus planes nutricionales y deportivos, comidas realmente consumidas, sesiones con ejercicios y series, evolución corporal, sueño, horarios, preferencias y sensaciones. Compara siempre lo planificado con lo realizado de cada miembro antes de proponer cambios. Para el plan conjunto conserva objetivos y macros individuales. Prioriza platos base, ingredientes y preparaciones comunes, pero adapta cantidades, número de comidas, horarios, lugar de consumo, transporte, turnos y entrenamiento de cada persona. Relaciona el sueño y la energía percibida con recuperación, apetito y rendimiento solo como tendencias observadas, sin asumir causalidad ni diagnosticar. No igualar cantidades automáticamente.`:""}`;
 const body=[...checkins].reverse().map((row,index,list)=>{const previous=list[index-1],delta=previous?Number(row.weight)-Number(previous.weight):null;return `- ${row.checkinDate} | Peso ${fmt(row.weight)} kg${delta==null?"":` (${delta>=0?"+":""}${delta.toFixed(1)} kg vs. registro anterior)`} | Grasa corporal ${fmt(row.bodyFatPercentage)} % | Masa muscular ${fmt(row.muscleMassKg)} kg | Índice de grasa visceral ${fmt(row.visceralFatPercentage)} (sin unidad) | Grasa subcutánea ${fmt(row.subcutaneousFatPercentage)} % | Cintura ${fmt(row.waistCm)} cm | Pecho ${fmt(row.chestCm)} cm | Cadera ${fmt(row.hipCm)} cm | Brazo I/D ${fmt(row.leftArmCm)}/${fmt(row.rightArmCm)} cm | Muslo I/D ${fmt(row.leftThighCm)}/${fmt(row.rightThighCm)} cm | Fotos ${row.photos.length}${row.notes?` | Notas: ${row.notes}`:""}`}).join("\n")||"- Sin check-ins";
 const targetsText=targets.map(target=>`- Desde ${fmt(target.valid_from)}: ${fmt(target.calories)} kcal, P ${fmt(target.protein)} g, C ${fmt(target.carbohydrates)} g, G ${fmt(target.fat)} g, fibra ${fmt(target.fiber)} g`).join("\n")||"- Sin objetivos nutricionales";
 const plannedDiet=dietPlans.map(({plan,meals})=>{const rows=meals.map(meal=>`  - Semana ${fmt(meal.week_number)} · Día ${fmt(meal.day_number)} ${fmt(meal.day_name)} | ${fmt(meal.meal_type)} | ${fmt(meal.meal_name||meal.recipe)} | Ración x${fmt(meal.portion_multiplier)}${meal.quantity?` (cantidad ${fmt(meal.quantity)})`:""} | ${fmt(meal.calories)} kcal, P ${fmt(meal.protein)}, C ${fmt(meal.carbohydrates)}, G ${fmt(meal.fat)}`).join("\n");return `- PLAN: ${plan.name} v${plan.version} [${plan.status}]\n${rows||"  - Sin detalle disponible"}`}).join("\n")||"- Sin dietas importadas";
 const actualDiet=groupByDate(consumedMeals,"meal_date",meal=>`${fmt(meal.meal_type)}: ${fmt(meal.name)} [${meal.status}]${meal.adherence_percent!=null?` adherencia ${meal.adherence_percent}%`:""}${meal.deviation_reason?` motivo: ${meal.deviation_reason}`:""}${meal.planned_meal?` (prevista: ${meal.planned_meal})`:""}; ${fmt(meal.portion)}; ${fmt(meal.calories)} kcal, P ${fmt(meal.protein)}, C ${fmt(meal.carbohydrates)}, G ${fmt(meal.fat)}${meal.notes?`; notas: ${meal.notes}`:""}`);
 const plannedTraining=trainingPlans.map(({plan,exercises})=>{const rows=exercises.map(ex=>`  - S${ex.weekNumber} D${ex.dayNumber} ${ex.dayName||""} · ${ex.sessionName} · ${ex.order}. ${ex.exercise} (${ex.muscleGroup||"sin grupo"}, ${ex.equipment||"sin equipo"}) · ${ex.sets}x${ex.repsMin}-${ex.repsMax} · RIR ${fmt(ex.targetRir)} · RPE ${fmt(ex.targetRpe)} · descanso ${fmt(ex.restSeconds)} s${ex.tempo?` · tempo ${ex.tempo}`:""}${ex.instructions?` · instrucciones: ${ex.instructions}`:""}${ex.notes?` · notas: ${ex.notes}`:""}`).join("\n");return `- PLAN: ${plan.name} v${plan.version} [${plan.status}] · ${plan.validFrom||"?"} a ${plan.validUntil||"?"}\n${rows||"  - Sin detalle disponible"}`}).join("\n")||"- Sin planes de entrenamiento";
 const actualTraining=realSessions.filter(Boolean).map(session=>{if(!session)return"";const h=session.header,exercises=session.exercises.map(ex=>`  - ${ex.order}. ${ex.name} [${ex.completed?"completado":"incompleto"}] · objetivo ${fmt(ex.targetSets)}x${fmt(ex.targetRepsMin)}-${fmt(ex.targetRepsMax)}, RIR ${fmt(ex.targetRir)}${ex.painReported?` · dolor ${fmt(ex.painIntensity)} ${ex.painArea||""}`:""}${ex.notes?` · ${ex.notes}`:""}\n${ex.sets.map(set=>`    · Serie ${set.setNumber} ${set.setType}: ${fmt(set.weight)} kg x ${fmt(set.repetitions)} reps, RIR ${fmt(set.rir)}, RPE ${fmt(set.rpe)}, ${fmt(set.durationSeconds)} s, ${fmt(set.distanceMeters)} m, descanso ${fmt(set.restSeconds)} s${set.painLevel?`, dolor ${set.painLevel}`:""} [${set.completed?"hecha":"no hecha"}]`).join("\n")}`).join("\n");return `- ${h.plannedDate} · ${h.name} [${h.status}] · duración ${fmt(h.durationSeconds)} s · RPE global ${fmt(h.globalRpe)} · energía ${fmt(h.energyLevel)} · congestión ${fmt(h.pumpLevel)} · dolor ${fmt(h.painLevel)} · dificultad ${fmt(h.difficultyLevel)} · volumen ${fmt(session.metrics.volume)}${h.notes?` · notas: ${h.notes}`:""}\n${exercises}`}).join("\n")||"- Sin sesiones registradas";
 const profileText=(profile?`Objetivo principal: ${fmt(profile.primary_goal)}; sexo: ${fmt(profile.biological_sex)}; experiencia: ${fmt(profile.experience_level)}; actividad: ${fmt(profile.activity_level)}; altura: ${fmt(profile.height_cm)} cm; días disponibles: ${fmt(profile.training_days)}; limitaciones: ${fmt(profile.limitations)}`:"Sin perfil disponible")+(adherence?`\nAdherencia ${adherence.days} días: nutrición ${fmt(adherence.meals.score)}% (${adherence.meals.missing} sin registrar), entreno ${fmt(adherence.workouts.score)}% (${adherence.workouts.partial} parciales, ${adherence.workouts.missing} sin registrar). Motivos de entreno: ${adherence.workoutReasons.map(r=>`${r.reason} (${r.incidents})`).join(", ")||"ninguno registrado"}.`:"");
 return `Actúa como mi analista de entrenamiento y nutrición. Este texto es un expediente exportado por ANURA. Compara siempre PLANIFICADO frente a REALIZADO; no confundas ausencia de registro con incumplimiento. Detecta tendencias, adherencia y posibles incoherencias, pero no diagnostiques ni sustituyas a profesionales sanitarios.\n\nPERFIL Y CONTEXTO\n${profileText}\n\nOBJETIVOS DECLARADOS\n${goals}\n\nOBJETIVOS NUTRICIONALES HISTÓRICOS\n${targetsText}\n\nEVOLUCIÓN SEMANA A SEMANA (PESO Y MEDIDAS)\n${body}\nResumen del periodo visible: cambio ${fmt(evolution?.totalWeightChange)} kg; mínimo ${fmt(evolution?.minimumWeight)} kg; máximo ${fmt(evolution?.maximumWeight)} kg; tendencia ${fmt(evolution?.trend)}; racha ${fmt(evolution?.weeklyStreak)} semanas.\n\nDIETA PLANIFICADA ACTUAL Y ANTERIOR (DETALLADA)\n${plannedDiet}\n\nDIETA REAL REGISTRADA (DETALLADA POR DÍA)\n${actualDiet}\n\nENTRENAMIENTO PLANIFICADO ACTUAL Y ANTERIOR (DETALLADO)\n${plannedTraining}\n\nENTRENAMIENTO REAL REALIZADO (SESIONES, EJERCICIOS Y SERIES)\n${actualTraining}\n\nTAREA\n1. Resume la evolución y la adherencia con cifras.\n2. Compara dieta planificada y real por día, calorías y macros.\n3. Compara entreno planificado y real: volumen, cargas, repeticiones, RIR/RPE, dolor y progresión.\n4. Relaciona los cambios semanales de peso, grasa y perímetros con la adherencia, sin afirmar causalidad no demostrada.\n5. Señala datos ausentes o poco fiables antes de concluir.\n6. Propón ajustes concretos y prudentes para el siguiente periodo, explicando el motivo.\n7. Si te pido nuevos planes, entrégalos completos y compatibles con las plantillas CSV de ANURA, conservando unidades, estructura y nivel de detalle.`;
}
async function allWorkoutHistory(){const result=[];for(let page=0;page<20;page++){const batch=await workoutApi.history(page,50);result.push(...batch);if(batch.length<50)break}return result}
function fmt(value:unknown){return value===null||value===undefined||value===""?"—":String(value)}
function groupByDate<T>(rows:T[],dateKey:keyof T,render:(row:T)=>string){if(!rows.length)return"- Sin comidas reales registradas";const groups=new Map<string,T[]>();rows.forEach(row=>{const date=fmt(row[dateKey]);groups.set(date,[...(groups.get(date)||[]),row])});return [...groups.entries()].map(([date,items])=>`- ${date}\n${items.map(item=>`  - ${render(item)}`).join("\n")}`).join("\n")}
function Kpi({label,value,tone}:{label:string;value:string;tone:string}){return <div className={tone}><small>{label}</small><strong>{value}</strong></div>}
function ProgressChart({points,metric}:{points:EvolutionPoint[];metric:Metric}){const series=points.map(p=>({date:p.date,value:metric==="arms"?average(p.leftArmCm,p.rightArmCm):metric==="thighs"?average(p.leftThighCm,p.rightThighCm):p[metric]})).filter((p):p is {date:string;value:number}=>p.value!=null);if(series.length<1)return <div className="chart-no-data">No hay medidas de {metrics.find(m=>m.id===metric)?.label.toLowerCase()} en este periodo.</div>;const vals=series.map(p=>Number(p.value)),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(max-min,1),pts=series.map((p,i)=>({x:series.length===1?50:7+i/(series.length-1)*86,y:82-(p.value-min)/span*62,...p})),path=pts.map(p=>`${p.x},${p.y}`).join(" "),unit=metrics.find(m=>m.id===metric)?.unit;return <div className="body-chart"><div className="body-chart-value"><small>{metrics.find(m=>m.id===metric)?.label.toUpperCase()}</small><b>{series.at(-1)?.value.toFixed(1)} {unit}</b></div><div className="body-chart-plot"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`Evolución de ${metrics.find(m=>m.id===metric)?.label.toLowerCase()}`}><defs><linearGradient id={`bodyFill-${metric}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#c8f15d" stopOpacity=".32"/><stop offset="1" stopColor="#c8f15d" stopOpacity="0"/></linearGradient></defs><path className="body-grid" d="M7 20H93 M7 51H93 M7 82H93"/><path className="body-area" fill={`url(#bodyFill-${metric})`} d={`M${pts[0].x},88 L${pts.map(p=>`${p.x},${p.y}`).join(" L")} L${pts.at(-1)?.x},88 Z`}/><polyline points={path} fill="none" stroke="#668c2d" strokeWidth="3" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/></svg>{pts.map(p=><i className="body-chart-point" key={p.date} style={{left:`${p.x}%`,top:`${p.y}%`}} title={`${formatDate(p.date)}: ${p.value.toFixed(1)} ${unit}`}/>)}</div><div className="body-chart-axis"><span>{formatDate(series[0].date)}</span><span>{formatDate(series.at(-1)!.date)}</span></div></div>}
function CheckinCard({row,previous,edit,remove}:{row:BodyCheckin;previous?:BodyCheckin;edit:()=>void;remove:()=>void}){const [open,setOpen]=useState(false),change=previous?row.weight-previous.weight:null,measures=[["Cintura",row.waistCm],["Pecho",row.chestCm],["Cadera",row.hipCm],["Brazos",average(row.leftArmCm,row.rightArmCm)],["Muslos",average(row.leftThighCm,row.rightThighCm)]].filter(x=>x[1]!=null);return <article className={`checkin-card ${open?"open":""}`}><button className="checkin-main" onClick={()=>setOpen(!open)}><span className="checkin-date"><b>{new Date(row.checkinDate+"T12:00").getDate()}</b><small>{new Date(row.checkinDate+"T12:00").toLocaleDateString("es",{month:"short"})}</small></span><span><small>CHECK-IN</small><strong>{Number(row.weight).toFixed(1)} kg</strong><em>{change==null?"Primer registro":signed(change,"kg")}</em></span><span className="photo-count"><Camera/>{row.photos.length}</span><ChevronDown/></button><div className="checkin-detail">{measures.length>0&&<div className="measure-grid">{measures.map(([name,value])=><span key={String(name)}><small>{name}</small><b>{Number(value).toFixed(1)} cm</b></span>)}</div>}{row.bodyFatPercentage!=null&&<p><b>Grasa corporal:</b> {row.bodyFatPercentage}%</p>}{row.notes&&<p className="checkin-notes">{row.notes}</p>}{row.photos.length>0&&<div className="photo-strip">{row.photos.map(photo=><a href={photo.storageUrl} target="_blank" rel="noreferrer" key={photo.id}><img src={photo.thumbnailUrl||photo.storageUrl} alt={`Progreso ${photo.photoType}`}/><small>{photo.photoType}</small></a>)}</div>}<div className="checkin-actions"><button onClick={edit}><Edit3/>Editar</button><button className="danger" onClick={remove}><Trash2/>Eliminar</button></div></div></article>}

function CheckinModal({value,onClose,onSaved}:{value:BodyCheckin|null;onClose:()=>void;onSaved:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget),number=(name:string)=>f.get(name)?Number(f.get(name)):undefined;const body:BodyCheckinInput={checkinDate:String(f.get("date")),weight:Number(f.get("weight")),bodyFatPercentage:number("fat"),muscleMassKg:number("muscleMass"),visceralFatPercentage:number("visceralFat"),subcutaneousFatPercentage:number("subcutaneousFat"),waistCm:number("waist"),chestCm:number("chest"),hipCm:number("hip"),leftArmCm:number("leftArm"),rightArmCm:number("rightArm"),leftThighCm:number("leftThigh"),rightThighCm:number("rightThigh"),notes:String(f.get("notes")||"")};try{const saved=value?await bodyProgressApi.update(value.id,body):await bodyProgressApi.create(body);for(const type of ["FRONT","SIDE","BACK"]){const file=f.get(`photo-${type}`);if(file instanceof File&&file.size){const storageUrl=await compressPhoto(file);await bodyProgressApi.addPhoto(saved.id,{photoType:type,storageUrl,takenAt:new Date().toISOString()})}}onSaved()}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo guardar")}finally{setBusy(false)}};
 const composition=[["muscleMass","Masa muscular","kg",value?.muscleMassKg],["visceralFat","Índice de grasa visceral","nivel",value?.visceralFatPercentage],["subcutaneousFat","Grasa subcutánea","%",value?.subcutaneousFatPercentage]];
 return createPortal(<div className="overlay checkin-overlay"><form className="modal checkin-modal" onSubmit={submit}><div className="modal-head"><div><small>REVISIÓN SEMANAL</small><h2>{value?"Editar check-in":"Nuevo check-in"}</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="checkin-form-scroll"><section className="checkin-basic"><div><small>DATOS PRINCIPALES</small><p>Fecha, peso y composición corporal.</p></div><div className="checkin-primary-fields"><label>Fecha<input required type="date" name="date" defaultValue={value?.checkinDate||new Date().toISOString().slice(0,10)}/></label><label>Peso (kg)<input required inputMode="decimal" type="number" min="20" max="500" step="0.1" name="weight" defaultValue={value?.weight}/></label><label>Grasa corporal %<input inputMode="decimal" type="number" min="1" max="80" step="0.1" name="fat" defaultValue={value?.bodyFatPercentage}/></label></div></section><section className="composition-fields"><div className="advanced-heading"><span><small>COMPOSICIÓN CORPORAL</small><b>Datos de báscula inteligente</b></span><p>Opcional: registra siempre valores de la misma báscula para comparar tendencias.</p></div><div>{composition.map(([name,label,unit,current])=><label key={String(name)}>{label} ({unit})<input inputMode="decimal" type="number" min="0" max="300" step="0.1" name={String(name)} defaultValue={current}/></label>)}</div></section><section className="measurement-fields"><div className="advanced-heading"><span><small>SEGUIMIENTO AVANZADO</small><b>Medidas corporales</b></span><p>Opcional: rellénalas cuando te sea posible para obtener un seguimiento más preciso.</p></div><div>{[["waist","Cintura",value?.waistCm],["chest","Pecho",value?.chestCm],["hip","Cadera",value?.hipCm],["leftArm","Brazo izq.",value?.leftArmCm],["rightArm","Brazo der.",value?.rightArmCm],["leftThigh","Muslo izq.",value?.leftThighCm],["rightThigh","Muslo der.",value?.rightThighCm]].map(([name,label,current])=><label key={String(name)}>{label} (cm)<input inputMode="decimal" type="number" min="10" max="300" step="0.1" name={String(name)} defaultValue={current}/></label>)}</div></section><section className="photo-url-fields"><div className="advanced-heading"><span><Camera/><b>Fotografías de progreso</b></span><p>Opcional y privado. Añade frente, perfil y espalda para comparar tu evolución.</p></div><div className="photo-input-grid">{[["FRONT","Frente"],["SIDE","Perfil"],["BACK","Espalda"]].map(([type,label])=><label key={type}><span>{label}</span><input type="file" name={`photo-${type}`} accept="image/jpeg,image/png,image/webp" capture="environment"/></label>)}</div></section><label>Notas<textarea name="notes" defaultValue={value?.notes} placeholder="Sensaciones, contexto y observaciones…"/></label>{error&&<div className="error">{error}</div>}</div><button className="checkin-save" disabled={busy}><Save/>{busy?"Guardando…":"Guardar check-in"}</button></form></div>,document.body)
}

function compressPhoto(file:File):Promise<string>{return new Promise((resolve,reject)=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{const scale=Math.min(1,1200/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d")?.drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL("image/jpeg",.78))};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("No se pudo leer una de las fotografías"))};image.src=url})}
function ConfirmDelete({row,close,confirm}:{row:BodyCheckin;close:()=>void;confirm:()=>void}){return <div className="overlay confirm-overlay"><section className="confirm-card"><Trash2/><h3>Eliminar check-in</h3><p>Se eliminará el registro del {formatDate(row.checkinDate)} y sus referencias fotográficas. Esta acción no se puede deshacer.</p><div><button onClick={close}>Cancelar</button><button className="danger" onClick={confirm}>Eliminar</button></div></section></div>}
function period(range:Range){const to=new Date(),from=new Date();if(range==="1M")from.setMonth(from.getMonth()-1);if(range==="3M")from.setMonth(from.getMonth()-3);if(range==="6M")from.setMonth(from.getMonth()-6);if(range==="1Y")from.setFullYear(from.getFullYear()-1);if(range==="ALL")from.setFullYear(2000);return{from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10)}}function average(a?:number,b?:number){if(a==null&&b==null)return undefined;if(a==null)return b;if(b==null)return a;return(a+b)/2}function signed(value?:number|null,unit=""){if(value==null)return"—";return`${value>0?"+":""}${Number(value).toFixed(1)} ${unit}`.trim()}function formatDate(date:string){return new Date(date+"T12:00").toLocaleDateString("es",{day:"numeric",month:"short",year:"numeric"})}
