import {useEffect,useMemo,useState} from "react";
import {CalendarDays,ChevronDown,Droplets,Pencil,Save,Sparkles,Trash2,X} from "lucide-react";
import {api} from "./api";
type Cycles=Awaited<ReturnType<typeof api.cycles>>;
type Cycle=Cycles[number];
const MS=86400000,parse=(value:string)=>new Date(`${value}T12:00:00`),key=(date:Date)=>date.toLocaleDateString("en-CA"),add=(date:Date,days:number)=>{const result=new Date(date);result.setDate(result.getDate()+days);return result};
export function CycleTracker({addSignal=0}:{addSignal?:number}){
 const [cycles,setCycles]=useState<Cycles>([]),[formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState<Cycle|null>(null),[message,setMessage]=useState(""),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
 const load=()=>api.cycles().then(setCycles).catch(()=>setCycles([]));useEffect(()=>{void load()},[]);useEffect(()=>{if(addSignal){setEditing(null);setFormOpen(true)}},[addSignal]);
 const prediction=useMemo(()=>{const ordered=[...cycles].sort((a,b)=>a.start_date.localeCompare(b.start_date)),gaps=ordered.slice(1).map((item,index)=>Math.round((parse(item.start_date).getTime()-parse(ordered[index].start_date).getTime())/MS)).filter(value=>value>=18&&value<=45),durations=ordered.map(item=>item.end_date?Math.round((parse(item.end_date).getTime()-parse(item.start_date).getTime())/MS)+1:0).filter(value=>value>0&&value<11),cycle=Math.round(gaps.reduce((a,b)=>a+b,0)/(gaps.length||1))||28,duration=Math.round(durations.reduce((a,b)=>a+b,0)/(durations.length||1))||5,last=ordered.at(-1);if(!last)return{cycle,duration};const next=add(parse(last.start_date),cycle),ovulation=add(next,-14);return{cycle,duration,next,ovulation,fertileStart:add(ovulation,-5),fertileEnd:add(ovulation,1)}},[cycles]);
 const first=new Date(month.getFullYear(),month.getMonth(),1),start=add(first,-((first.getDay()+6)%7)),days=Array.from({length:42},(_,index)=>add(start,index)),phase=(date:Date)=>{const dateKey=key(date);if(cycles.some(cycle=>dateKey>=cycle.start_date&&dateKey<=(cycle.end_date||key(new Date()))))return"period";if(prediction.next&&dateKey>=key(prediction.next)&&dateKey<key(add(prediction.next,prediction.duration)))return"predicted";if(prediction.fertileStart&&prediction.fertileEnd&&dateKey>=key(prediction.fertileStart)&&dateKey<=key(prediction.fertileEnd))return"fertile";return""};
 const save=async(form:HTMLFormElement)=>{const data=new FormData(form),body={startDate:String(data.get("start")),endDate:String(data.get("end")||"")||undefined,flowLevel:String(data.get("flow")||""),symptoms:String(data.get("symptoms")||""),notes:String(data.get("notes")||"")};if(editing)await api.updateCycle(editing.id,body);else await api.saveCycle(body);setFormOpen(false);setEditing(null);await load();setMessage(editing?"Periodo actualizado":"Periodo en curso registrado")};
 return <section className="cycle-tracker"><div className="cycle-hero"><CalendarDays/><span><small>SEGUIMIENTO PRIVADO</small><h2>Tu ciclo</h2><p>Predicciones orientativas basadas en tus registros; no sustituyen un método anticonceptivo.</p></span></div>{message&&<div className="progress-saved"><Save/>{message}</div>}
 <div className="cycle-insights"><article><Droplets/><span><small>PRÓXIMA REGLA</small><b>{prediction.next?prediction.next.toLocaleDateString("es",{day:"numeric",month:"long"}):"Registra un periodo"}</b><em>Ciclo medio: {prediction.cycle} días</em></span></article><article><Sparkles/><span><small>OVULACIÓN ESTIMADA</small><b>{prediction.ovulation?prediction.ovulation.toLocaleDateString("es",{day:"numeric",month:"long"}):"Sin datos suficientes"}</b><em>Estimación, puede variar</em></span></article></div>
 <section className="cycle-calendar"><header><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><h3>{month.toLocaleDateString("es",{month:"long",year:"numeric"})}</h3><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></header><div className="cycle-weekdays">{["L","M","X","J","V","S","D"].map(day=><span key={day}>{day}</span>)}</div><div className="cycle-days">{days.map(date=><span key={key(date)} className={`${date.getMonth()!==month.getMonth()?"outside":""} ${phase(date)} ${key(date)===key(new Date())?"today":""}`}><b>{date.getDate()}</b></span>)}</div><footer><span><i className="period"/>Registrado</span><span><i className="predicted"/>Predicción</span><span><i className="fertile"/>Ventana fértil</span></footer></section>
 <details className="cycle-history"><summary><span><small>HISTÓRICO</small><b>{cycles.length} periodos registrados</b></span><ChevronDown/></summary><div className="cycle-list">{cycles.length?cycles.map(cycle=><article key={cycle.id}><span><b>{parse(cycle.start_date).toLocaleDateString("es")}{cycle.end_date?` – ${parse(cycle.end_date).toLocaleDateString("es")}`:" · En curso"}</b><small>{cycle.flow_level||"Flujo sin indicar"}{cycle.symptoms?` · ${cycle.symptoms}`:""}</small>{cycle.notes&&<em>{cycle.notes}</em>}</span><button aria-label="Editar periodo" onClick={()=>{setEditing(cycle);setFormOpen(true)}}><Pencil/></button><button aria-label="Eliminar periodo" onClick={async()=>{await api.deleteCycle(cycle.id);await load()}}><Trash2/></button></article>):<div className="cycle-empty">Aún no hay periodos registrados.</div>}</div></details>
 {formOpen&&<div className="overlay cycle-form-overlay"><form className="modal cycle-form-modal" onSubmit={async event=>{event.preventDefault();await save(event.currentTarget)}}><button type="button" className="close-sheet" onClick={()=>{setFormOpen(false);setEditing(null)}}><X/></button><small>{editing?"PERIODO EN CURSO":"NUEVO REGISTRO"}</small><h2>{editing?"Actualizar periodo":"Registrar periodo"}</h2>{editing&&!editing.end_date&&<p>Déjalo sin fecha de fin hasta que se te vaya; podrás volver a editarlo cuando lo sepas.</p>}<div className="cycle-form-row"><label>Inicio<input required name="start" type="date" defaultValue={editing?.start_date||key(new Date())}/></label><label>Fin<input name="end" type="date" defaultValue={editing?.end_date||""}/></label><label>Flujo<select name="flow" defaultValue={editing?.flow_level||""}><option value="">Sin indicar</option><option value="LIGHT">Ligero</option><option value="MEDIUM">Medio</option><option value="HEAVY">Abundante</option></select></label></div><label>Síntomas<input name="symptoms" defaultValue={editing?.symptoms||""} placeholder="Dolor, fatiga, hinchazón…"/></label><label>Notas<textarea name="notes" defaultValue={editing?.notes||""} placeholder="Sensaciones, descanso o contexto…"/></label><button className="primary"><Save/>{editing?"Guardar cambios":"Guardar periodo"}</button></form></div>}</section>
}
