import {useEffect,useMemo,useState} from "react";
import {CalendarDays,ChevronDown,Droplets,Save,Sparkles,Trash2,X} from "lucide-react";
import {api} from "./api";
type Cycles=Awaited<ReturnType<typeof api.cycles>>;
const MS=86400000,parse=(v:string)=>new Date(`${v}T12:00:00`),key=(d:Date)=>d.toLocaleDateString("en-CA"),add=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
export function CycleTracker({addSignal=0}:{addSignal?:number}){
 const [cycles,setCycles]=useState<Cycles>([]),[formOpen,setFormOpen]=useState(false),[message,setMessage]=useState(""),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
 const load=()=>api.cycles().then(setCycles).catch(()=>setCycles([]));useEffect(()=>{void load()},[]);useEffect(()=>{if(addSignal)setFormOpen(true)},[addSignal]);
 const prediction=useMemo(()=>{const ordered=[...cycles].sort((a,b)=>a.start_date.localeCompare(b.start_date)),gaps=ordered.slice(1).map((x,i)=>Math.round((parse(x.start_date).getTime()-parse(ordered[i].start_date).getTime())/MS)).filter(x=>x>=18&&x<=45),durations=ordered.map(x=>x.end_date?Math.round((parse(x.end_date).getTime()-parse(x.start_date).getTime())/MS)+1:0).filter(x=>x>0&&x<11),cycle=Math.round(gaps.reduce((a,b)=>a+b,0)/(gaps.length||1))||28,duration=Math.round(durations.reduce((a,b)=>a+b,0)/(durations.length||1))||5,last=ordered.at(-1);if(!last)return{cycle,duration};const next=add(parse(last.start_date),cycle),ovulation=add(next,-14);return{cycle,duration,next,ovulation,fertileStart:add(ovulation,-5),fertileEnd:add(ovulation,1)}},[cycles]);
 const first=new Date(month.getFullYear(),month.getMonth(),1),start=add(first,-((first.getDay()+6)%7)),days=Array.from({length:42},(_,i)=>add(start,i)),phase=(date:Date)=>{const k=key(date);if(cycles.some(c=>k>=c.start_date&&k<=(c.end_date||c.start_date)))return"period";if(prediction.next&&k>=key(prediction.next)&&k<key(add(prediction.next,prediction.duration)))return"predicted";if(prediction.fertileStart&&prediction.fertileEnd&&k>=key(prediction.fertileStart)&&k<=key(prediction.fertileEnd))return"fertile";return""};
 return <section className="cycle-tracker"><div className="cycle-hero"><CalendarDays/><span><small>SEGUIMIENTO PRIVADO</small><h2>Tu ciclo</h2><p>Predicciones orientativas basadas en tus registros; no sustituyen un método anticonceptivo.</p></span></div>{message&&<div className="progress-saved"><Save/>{message}</div>}
 <div className="cycle-insights"><article><Droplets/><span><small>PRÓXIMA REGLA</small><b>{prediction.next?prediction.next.toLocaleDateString("es",{day:"numeric",month:"long"}):"Registra un periodo"}</b><em>Ciclo medio: {prediction.cycle} días</em></span></article><article><Sparkles/><span><small>OVULACIÓN ESTIMADA</small><b>{prediction.ovulation?prediction.ovulation.toLocaleDateString("es",{day:"numeric",month:"long"}):"Sin datos suficientes"}</b><em>Estimación, puede variar</em></span></article></div>
 <section className="cycle-calendar"><header><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><h3>{month.toLocaleDateString("es",{month:"long",year:"numeric"})}</h3><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></header><div className="cycle-weekdays">{["L","M","X","J","V","S","D"].map(x=><span key={x}>{x}</span>)}</div><div className="cycle-days">{days.map(d=><span key={key(d)} className={`${d.getMonth()!==month.getMonth()?"outside":""} ${phase(d)} ${key(d)===key(new Date())?"today":""}`}><b>{d.getDate()}</b></span>)}</div><footer><span><i className="period"/>Registrado</span><span><i className="predicted"/>Predicción</span><span><i className="fertile"/>Ventana fértil</span></footer></section>
 <details className="cycle-history"><summary><span><small>HISTÓRICO</small><b>{cycles.length} periodos registrados</b></span><ChevronDown/></summary><div className="cycle-list">{cycles.length?cycles.map(c=><article key={c.id}><span><b>{parse(c.start_date).toLocaleDateString("es")}{c.end_date?` – ${parse(c.end_date).toLocaleDateString("es")}`:""}</b><small>{c.flow_level||"Flujo sin indicar"}{c.symptoms?` · ${c.symptoms}`:""}</small>{c.notes&&<em>{c.notes}</em>}</span><button aria-label="Eliminar periodo" onClick={async()=>{await api.deleteCycle(c.id);await load()}}><Trash2/></button></article>):<div className="cycle-empty">Aún no hay periodos registrados.</div>}</div></details>
 {formOpen&&<div className="overlay cycle-form-overlay"><form className="modal cycle-form-modal" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api.saveCycle({startDate:String(f.get("start")),endDate:String(f.get("end")||"")||undefined,flowLevel:String(f.get("flow")||""),symptoms:String(f.get("symptoms")||""),notes:String(f.get("notes")||"")});setFormOpen(false);await load();setMessage("Periodo registrado")}}><button type="button" className="close-sheet" onClick={()=>setFormOpen(false)}><X/></button><small>NUEVO REGISTRO</small><h2>Registrar periodo</h2><div className="cycle-form-row"><label>Inicio<input required name="start" type="date" defaultValue={key(new Date())}/></label><label>Fin<input name="end" type="date"/></label><label>Flujo<select name="flow"><option value="">Sin indicar</option><option value="LIGHT">Ligero</option><option value="MEDIUM">Medio</option><option value="HEAVY">Abundante</option></select></label></div><label>Síntomas<input name="symptoms" placeholder="Dolor, fatiga, hinchazón…"/></label><label>Notas<textarea name="notes" placeholder="Sensaciones, descanso o contexto…"/></label><button className="primary"><Save/>Guardar periodo</button></form></div>}</section>
}
