import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './App.tsx';
import './styles.css';
import './install.css';
import './import.css';
import './nutrition.css';
import './nutrition-plan.css';
import './premium.css';
import './workout.css';
import './mobile-modal.css';
import './body-progress.css';
import './meal-flow.css';
import './meal-flow-v2.css';
import './responsive.css';
import './household-management.css';
import './workout-desktop.css';
import './body-progress-desktop.css';
import './profile-import.css';
import './nutrition-scroll.css';
import './features-v2.css';
import './profile-settings.css';
import './shopping-v2.css';
import './adherence.css';
import './work-routine.css';
import './household-sharing.css';
import './work-routine-mobile.css';
import './cycle-tracker.css';
import './evolution-motion.css';
import './plan-expiry.css';
import './expiring-card.css';
import './supplements.css';
import './nutrition-redesign.css';
import './nutrition-polish.css';
import './home-premium.css';
import './wow-polish.css';
import './quick-activity.css';
import './workout-change-modal.css';
import './meal-substitution.css';
import './batch-cooking.css';
import './plan-meal-details.css';
import './evolution-redesign.css';

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/sw.js'));
