import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './App.tsx';
import './styles.css';
import './install.css';
import './import.css';
import './nutrition.css';
import './nutrition-plan.css';
import './premium.css';
import './workout.css';
import './mobile-modal.css';
import './body-progress.css';
import './meal-flow.css';
import './meal-flow-v2.css';
import './responsive.css';
import './household-management.css';
import './workout-desktop.css';

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/sw.js'));
