import {useEffect,useMemo,useRef,useState} from "react";
import {Apple,ArrowLeft,Calculator,Check,ChevronRight,Clock3,Edit3,MinusCircle,Plus,X} from "lucide-react";
import {api,nutritionApi,type Entry,type MealInput,type MealType,type TodayMeal} from "./api";

const moments:Array<{id:MealType;label:string;matches:string[]}>= [
 {id:"BREAKFAST",label:"Desayuno",matches:["BREAKFAST","DESAYUNO"]},
 {id:"MID_MORNING",label:"Media mañana",matches:["MID_MORNING","MEDIA MAÑANA"]},
 {id:"LUNCH",label:"Comida",matches:["LUNCH","COMIDA"]},
 {id:"SNACK",label:"Merienda / snack",matches:["SNACK","MERIENDA"]},
 {id:"DINNER",label:"Cena",matches:["DINNER","CENA"]},
 {id:"OTHER",label:"Otro",matches:["OTHER","OTRO"]},
];

export function MealFlow({meals,editing,initialMealId,onClose,onBackToMeals,onDone}:{meals:TodayMeal[];editing?:Entry|null;initialMealId?:string|null;onClose:()=>void;onBackToMeals?:()=>void;onDone:()=>void}){
 const initialMeal=initialMealId?meals.find(meal=>meal.planned_meal_id===initialMealId):undefined;
 const initialMoment=initialMeal?moments.find(moment=>moment.matches.some(match=>initialMeal.meal_type.toLowerCase().includes(match.toLowerCase())))?.id:undefined;
 const [moment,setMoment]=useState<MealType|undefined>(editing?"OTHER":initialMoment),[mode,setMode]=useState<"proposal"|"substitute"|"additional"|"custom">(editing?"custom":"proposal"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[skip,setSkip]=useState(false);const close=useRef<HTMLButtonElement>(null);
 useEffect(()=>{close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!busy)onClose()};document.body.classList.add("modal-open");addEventListener("keydown",key);return()=>{document.body.classList.remove("modal-open");removeEventListener("keydown",key)}},[busy,onClose]);
 const planned=useMemo(()=>initialMeal||meals.find(meal=>meal.status==="PENDING"&&moments.find(x=>x.id===moment)?.matches.includes(meal.meal_type.toUpperCase())),[initialMeal,meals,moment]);
 const run=async(action:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError("");try{await action();onDone()}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo guardar la comida")}finally{setBusy(false)}};
 const heading=!moment?"¿Qué comida es?":planned&&mode==="proposal"?"Tu comida prevista":mode==="substitute"?"He comido otra cosa":mode==="additional"?"He comido esto y además...":editing?"Editar comida":"Registrar comida";
 return <div className="overlay meal-flow-overlay" role="presentation"><section className="modal meal-flow" role="dialog" aria-modal="true" aria-labelledby="meal-flow-title"><div className="modal-head"><div><small>NUTRICIÓN DE HOY</small><h2 id="meal-flow-title">{heading}</h2></div><button ref={close} type="button" onClick={onClose} aria-label="Cerrar"><X/></button></div>
 {!moment?<MomentPicker choose={setMoment}/>:<>
  <button className="meal-back" type="button" onClick={()=>{if(planned&&mode!=="proposal"){setMode("proposal");setSkip(false)}else if(initialMealId)(onBackToMeals||onClose)();else{setMoment(undefined);setMode("proposal");setSkip(false)}}><ArrowLeft/>{planned&&mode!=="proposal"?"Volver a la comida prevista":initialMealId?"Volver a las comidas de hoy":"Cambiar momento"}</button>
  {planned&&mode==="proposal"?<Proposal meal={planned} busy={busy} skip={skip} setSkip={setSkip} complete={()=>void run(()=>nutritionApi.completeToday(planned.planned_meal_id))} partial={(percent,reason)=>void run(()=>nutritionApi.partialToday(planned.planned_meal_id,{percent,reason}))} skipMeal={(notes)=>void run(()=>nutritionApi.skipToday(planned.planned_meal_id,notes))} substitute={()=>setMode("substitute")} additional={()=>setMode("additional")}/>:<MealForm moment={moment} planned={mode==="substitute"?planned:undefined} editing={editing} busy={busy} error={error} save={(input)=>void run(()=>mode==="substitute"&&planned?nutritionApi.substituteToday(planned.planned_meal_id,input):mode==="additional"&&planned?nutritionApi.additionalToday(planned.planned_meal_id,{...input,mealType:moment}):editing?api.update(editing.id,{type:"MEAL",title:input.name,entryDate:input.date||new Date().toISOString().slice(0,10),value:input.calories,unit:"kcal",details:input.portion,notes:input.notes,completed:true}):nutritionApi.customMeal({...input,mealType:moment}))}/>}
  {error&&mode==="proposal"&&<div className="error" role="alert">{error}</div>}
 </>}</section></div>
}

function MomentPicker({choose}:{choose:(value:MealType)=>void}){return <div className="moment-grid">{moments.map(moment=><button type="button" onClick={()=>choose(moment.id)} key={moment.id}><Clock3/><span>{moment.label}</span><ChevronRight/></button>)}</div>}

function Proposal({meal,busy,skip,setSkip,complete,partial,skipMeal,substitute,additional}:{meal:TodayMeal;busy:boolean;skip:boolean;setSkip:(value:boolean)=>void;complete:()=>void;partial:(percent:number,reason:string)=>void;skipMeal:(notes:string)=>void;substitute:()=>void;additional:()=>void}){const [notes,setNotes]=useState(""),[partialOpen,setPartialOpen]=useState(false),[percent,setPercent]=useState(50);return <div className="planned-proposal"><div className="proposal-card"><Apple/><div><small>{meal.meal_name}</small><h3>{meal.recipe}</h3><p>Ración × {meal.portion_multiplier||1}</p></div><strong>{Number(meal.calories||0).toFixed(0)}<small>kcal</small></strong></div><div className="macro-strip"><span><b>{Number(meal.protein||0).toFixed(0)} g</b><small>Proteína</small></span><span><b>{Number(meal.carbohydrates||0).toFixed(0)} g</b><small>Carbohidratos</small></span><span><b>{Number(meal.fat||0).toFixed(0)} g</b><small>Grasas</small></span></div>{skip||partialOpen?<div className="skip-panel">{partialOpen&&<label>Porción aproximada: {percent}%<input type="range" min="10" max="90" step="10" value={percent} onChange={e=>setPercent(Number(e.target.value))}/></label>}<label>{partialOpen?"Motivo o cambio":"Nota opcional"}<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder={partialOpen?"Ej. Dejé la mitad…":"¿Por qué te la has saltado?"}/></label><div><button type="button" onClick={()=>{setSkip(false);setPartialOpen(false)}}>Cancelar</button><button type="button" disabled={busy} onClick={()=>partialOpen?partial(percent,notes):skipMeal(notes)}>{partialOpen?"Guardar parcial":"Confirmar saltada"}</button></div></div>:<div className="proposal-actions"><button className="meal-yes" type="button" disabled={busy} onClick={complete}><Check/>{busy?"Guardando…":"Sí, he comido esto"}</button><button type="button" disabled={busy} onClick={()=>setPartialOpen(true)}>He comido una parte</button><button type="button" disabled={busy} onClick={substitute}><Edit3/>He comido otra cosa</button><button type="button" disabled={busy} onClick={()=>setSkip(true)}><MinusCircle/>Me la he saltado</button><button className="meal-additional" type="button" disabled={busy} onClick={additional}><Plus/>Es una comida adicional</button></div>}</div>}

function MealForm({moment,planned,editing,busy,error,save}:{moment:MealType;planned?:TodayMeal;editing?:Entry|null;busy:boolean;error:string;save:(input:Omit<MealInput,"mealType">)=>void}){const [estimateOpen,setEstimateOpen]=useState(false),[calories,setCalories]=useState<number|"">(editing?.value??""),[estimated,setEstimated]=useState(false);return <form className="quick-meal-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),number=(name:string)=>f.get(name)?Number(f.get(name)):undefined,notes=String(f.get("notes")||"");save({name:String(f.get("name")),date:String(f.get("date")),portion:String(f.get("portion")||""),calories:calories===""?undefined:Number(calories),protein:number("protein"),carbohydrates:number("carbohydrates"),fat:number("fat"),notes:estimated?`${notes}${notes?" · ":""}Calorías estimadas con margen aproximado ±20%.`:notes})}}><p>{planned?<>Sustituye <b>{planned.recipe}</b>. Conservaremos la referencia al plan original.</>:<>Registra tu {moments.find(x=>x.id===moment)?.label.toLowerCase()} sin campos innecesarios.</>}</p><label>¿Qué has comido?<input required autoFocus name="name" defaultValue={editing?.title||""} placeholder="Ej. Yogur con fruta"/></label><div className="meal-form-row"><label>Fecha<input required type="date" name="date" defaultValue={editing?.entryDate||new Date().toISOString().slice(0,10)}/></label><label>Cantidad o ración<input name="portion" defaultValue={editing?.details||""} placeholder="Ej. 1 plato, medio bocadillo…"/></label></div><button className="estimate-trigger" type="button" onClick={()=>setEstimateOpen(value=>!value)}><Calculator/>{estimateOpen?"Cerrar estimador":"No sé las calorías · Estimar"}</button>{estimateOpen&&<CalorieEstimator apply={value=>{setCalories(value);setEstimated(true);setEstimateOpen(false)}}/>}{estimated&&<small className="estimate-used">Cifra aproximada · margen ±20%</small>}<div className="macro-fields"><label>Kcal<input type="number" min="0" inputMode="decimal" name="calories" value={calories} onChange={e=>setCalories(e.target.value===""?"":Number(e.target.value))}/></label><label>Proteína (g)<input type="number" min="0" step="0.1" inputMode="decimal" name="protein"/></label><label>Carbos (g)<input type="number" min="0" step="0.1" inputMode="decimal" name="carbohydrates"/></label><label>Grasas (g)<input type="number" min="0" step="0.1" inputMode="decimal" name="fat"/></label></div><label>Notas opcionales<textarea name="notes" defaultValue={editing?.notes} placeholder="Cambios, sensaciones…"/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="primary meal-save" disabled={busy}>{busy?"Guardando…":planned?"Guardar sustitución":"Guardar comida"}</button></form>}

const estimateParts=[{id:"protein",label:"Proteína principal",hint:"carne, pescado, tofu",kcal:250},{id:"carbs",label:"Guarnición",hint:"arroz, pasta, patata o pan",kcal:260},{id:"vegetables",label:"Verdura o ensalada",hint:"una ración",kcal:80},{id:"fat",label:"Aceite, salsa o fritura",hint:"cantidad moderada",kcal:150},{id:"dairy",label:"Queso o lácteo",hint:"una ración",kcal:140},{id:"extra",label:"Postre o bebida",hint:"una unidad",kcal:180}];
function CalorieEstimator({apply}:{apply:(value:number)=>void}){const [selected,setSelected]=useState<Record<string,number>>({}),total=estimateParts.reduce((sum,item)=>sum+(selected[item.id]||0)*item.kcal,0);return <section className="calorie-estimator"><div><Calculator/><span><b>Estimación rápida</b><small>No necesita ser perfecta. Pulsa una vez por ración; después de dos vuelve a cero.</small></span></div><div className="estimate-parts">{estimateParts.map(item=><button className={selected[item.id]?"selected":""} type="button" key={item.id} onClick={()=>setSelected(current=>({...current,[item.id]:((current[item.id]||0)+1)%3}))}><span><b>{item.label}</b><small>{item.hint}</small></span><strong>{selected[item.id]||"+"}<small>× {item.kcal}</small></strong></button>)}</div><div className="estimate-result"><span><small>ESTIMACIÓN</small><b>≈ {total} kcal</b><em>{total?`Rango razonable: ${Math.round(total*.8)}–${Math.round(total*1.2)} kcal`:"Añade al menos un componente"}</em></span><button type="button" disabled={!total} onClick={()=>apply(total)}>Usar estimación</button></div><p>Es una aproximación con margen ±20%. Para seguimiento importa más registrar de forma consistente que acertar una cifra exacta.</p></section>}
