import {useMemo,useState} from "react";
import {Apple,Check,ChevronRight,Edit3,Plus,Sparkles,X} from "lucide-react";
import {api,nutritionApi,type Entry,type TodayMeal} from "./api";

const presets=["Desayuno","Comida","Merienda","Cena","Snack","Otro"];
export function MealFlow({meals,editing,onClose,onDone}:{meals:TodayMeal[];editing?:Entry|null;onClose:()=>void;onDone:()=>void}){
 const available=meals.filter(meal=>!meal.completed),[custom,setCustom]=useState(Boolean(editing)||!available.length),[selected,setSelected]=useState(()=>new Set(available.map(m=>m.planned_meal_id))),[changes,setChanges]=useState<Record<string,{title:string;calories:number;notes:string;open:boolean}>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[preset,setPreset]=useState(editing?.title||"Comida");
 const total=useMemo(()=>available.filter(m=>selected.has(m.planned_meal_id)).reduce((sum,m)=>sum+Number(changes[m.planned_meal_id]?.calories??m.calories??0),0),[available,selected,changes]);
 const confirmPlan=async()=>{setBusy(true);setError("");try{for(const meal of available.filter(m=>selected.has(m.planned_meal_id))){const change=changes[meal.planned_meal_id];await nutritionApi.completeToday(meal.planned_meal_id,change?{title:change.title,calories:change.calories,notes:change.notes}:undefined)}onDone()}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo guardar el día")}finally{setBusy(false)}};
 return <div className="overlay meal-flow-overlay"><section className="modal meal-flow"><div className="modal-head"><div><small>NUTRICIÓN DE HOY</small><h2>{editing?"Editar comida":custom?"Añadir comida":"Confirmar dieta"}</h2></div><button onClick={onClose}><X/></button></div>
 {!custom&&<><div className="diet-proposal"><Sparkles/><span><b>Tu dieta completa del día está lista</b><small>Confirma lo que has seguido y modifica solo lo que haya cambiado.</small></span></div><button className="select-all" onClick={()=>setSelected(selected.size===available.length?new Set():new Set(available.map(m=>m.planned_meal_id)))}><Check/>{selected.size===available.length?"Quitar todas":"Seleccionar dieta completa"}</button><div className="meal-review-list">{available.map(meal=>{const change=changes[meal.planned_meal_id],checked=selected.has(meal.planned_meal_id);return <article className={checked?"selected":""} key={meal.planned_meal_id}><button className="meal-check" onClick={()=>setSelected(current=>{const next=new Set(current);next.has(meal.planned_meal_id)?next.delete(meal.planned_meal_id):next.add(meal.planned_meal_id);return next})}><span>{checked?<Check/>:""}</span><b>{change?.title||meal.meal_name}</b><small>{meal.recipe}</small><strong>{Number(change?.calories??meal.calories).toFixed(0)} kcal</strong></button><button className="change-meal" onClick={()=>setChanges(current=>({...current,[meal.planned_meal_id]:{title:change?.title||meal.meal_name,calories:change?.calories??Number(meal.calories),notes:change?.notes||"",open:!change?.open}}))}><Edit3/>¿Hubo cambios?</button>{change?.open&&<div className="meal-change-fields"><label>Nombre<input value={change.title} onChange={e=>setChanges(c=>({...c,[meal.planned_meal_id]:{...change,title:e.target.value}}))}/></label><label>Kcal<input type="number" inputMode="numeric" value={change.calories} onChange={e=>setChanges(c=>({...c,[meal.planned_meal_id]:{...change,calories:Number(e.target.value)}}))}/></label><label>Qué cambió<textarea value={change.notes} onChange={e=>setChanges(c=>({...c,[meal.planned_meal_id]:{...change,notes:e.target.value}}))}/></label></div>}</article>})}</div><div className="meal-confirm-bar"><span><small>TOTAL SELECCIONADO</small><b>{total.toFixed(0)} kcal</b></span><button disabled={!selected.size||busy} onClick={confirmPlan}>{busy?"Guardando…":"Confirmar día"}<ChevronRight/></button></div><button className="add-other-meal" onClick={()=>setCustom(true)}><Plus/>Añadir algo fuera de la dieta</button></>}
 {custom&&<CustomMeal editing={editing} initial={preset} setPreset={setPreset} busy={busy} error={error} back={available.length&&!editing?()=>setCustom(false):undefined} save={async body=>{setBusy(true);setError("");try{editing?await api.update(editing.id,body):await api.create(body);onDone()}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo guardar la comida")}finally{setBusy(false)}}}/>} {error&&!custom&&<div className="error">{error}</div>}</section></div>
}
function CustomMeal({editing,initial,setPreset,busy,error,back,save}:{editing?:Entry|null;initial:string;setPreset:(x:string)=>void;busy:boolean;error:string;back?:()=>void;save:(body:Omit<Entry,"id">)=>void}){const [other,setOther]=useState(!presets.includes(initial));return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({type:"MEAL",title:other?String(f.get("other")):initial,entryDate:String(f.get("date")),value:f.get("calories")?Number(f.get("calories")):undefined,unit:"kcal",details:String(f.get("details")||""),notes:String(f.get("notes")||""),completed:true})}}><p className="meal-question">¿Qué tipo de comida quieres registrar?</p><div className="meal-presets">{presets.map(item=><button type="button" className={!other&&initial===item||other&&item==="Otro"?"active":""} onClick={()=>{setOther(item==="Otro");if(item!=="Otro")setPreset(item)}} key={item}>{item}</button>)}</div>{other&&<label>Nombre de la comida<input required name="other" defaultValue={editing?.title&&!presets.includes(editing.title)?editing.title:""} placeholder="Ej. Brunch"/></label>}<div className="row"><label>Fecha<input required type="date" name="date" defaultValue={editing?.entryDate||new Date().toISOString().slice(0,10)}/></label><label>Calorías<input type="number" inputMode="numeric" name="calories" defaultValue={editing?.value}/></label></div><label>Contenido<textarea name="details" defaultValue={editing?.details} placeholder="Alimentos, cantidades…"/></label><label>Notas<textarea name="notes" defaultValue={editing?.notes} placeholder="Cambios o sensaciones…"/></label>{error&&<div className="error">{error}</div>}<div className="custom-meal-actions">{back&&<button type="button" onClick={back}>Volver a la dieta</button>}<button className="primary" disabled={busy}>{busy?"Guardando…":editing?"Guardar cambios":"Añadir comida"}</button></div></form>}
