import { useState } from "react";
import { Trash2, X } from "lucide-react";
import { localDate, sleepApi, type SleepSession } from "./api";

const qualityOptions = [["😫", "Muy mala"], ["😕", "Mala"], ["😐", "Normal"], ["🙂", "Buena"], ["🤩", "Excelente"]] as const;
const energyOptions = [["🪫", "Agotado"], ["🥱", "Cansado"], ["😐", "Normal"], ["🙂", "Con energía"], ["⚡", "A tope"]] as const;

export function SleepModal({ value, close, saved, deleted }: { value: SleepSession | null; close: () => void; saved: (value: SleepSession) => void; deleted?: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [quality, setQuality] = useState(value?.quality_score || 0); const [energy, setEnergy] = useState(value?.morning_energy || 0);
  const total = value?.total_sleep_minutes ?? 480;
  const remove = async () => { if (!value || !deleted || !window.confirm("¿Borrar esta noche?")) return; setBusy(true); setError(""); try { await sleepApi.remove(value.id); deleted(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo borrar el registro."); } finally { setBusy(false); } };
  const scale = (title:string, options:readonly (readonly string[])[], selected:number, set:(n:number)=>void) => <fieldset className="sleep-scale"><legend>{title}</legend><div>{options.map(([emoji,label], index)=><button key={label} type="button" aria-label={label} className={selected===index+1?"active":""} onClick={()=>set(index+1)}><span>{emoji}</span></button>)}</div>{selected>0&&<small>{options[selected-1][1]}</small>}</fieldset>;
  return <div className="overlay sleep-modal"><section className="modal sleep-modal-card"><button type="button" aria-label="Cerrar" className="close-sheet" onClick={close}><X /></button><small>DESCANSO</small><h2>{value ? "Editar sueño" : "¿Cómo has dormido?"}</h2><form onSubmit={async event=>{event.preventDefault();const data=new FormData(event.currentTarget), hours=Number(data.get("hours")), minutes=Number(data.get("minutes"));if(hours<0||hours>24||minutes<0||minutes>59||hours*60+minutes>1440){setError("Indica una duración entre 0 y 24 horas.");return;}setBusy(true);setError("");try{saved(await sleepApi.save({sleepDate:localDate(),totalSleepMinutes:hours*60+minutes,qualityScore:quality||undefined,morningEnergy:energy||undefined,bedTime:String(data.get("bed")||"")||undefined,wakeTime:String(data.get("wake")||"")||undefined,notes:String(data.get("notes")||"")||undefined}));}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo guardar el registro.");}finally{setBusy(false);}}><div className="sleep-fields"><label>Horas<input name="hours" type="number" min="0" max="24" required defaultValue={Math.floor(total/60)}/></label><label>Minutos<input name="minutes" type="number" min="0" max="59" required defaultValue={total%60}/></label></div><p className="sleep-disclaimer">Si usas un wearable, consulta sus estadísticas para completar el registro con mayor precisión.</p>{scale("Calidad del sueño",qualityOptions,quality,setQuality)}{scale("Energía al despertar",energyOptions,energy,setEnergy)}<div className="sleep-fields"><label>Me acosté<input name="bed" type="time" defaultValue={value?.bed_time?.slice(0,5)}/></label><label>Me levanté<input name="wake" type="time" defaultValue={value?.wake_time?.slice(0,5)}/></label></div><label>Notas opcionales<textarea name="notes" defaultValue={value?.notes||""}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?"Guardando…":"Guardar sueño"}</button></form>{value&&deleted&&<button type="button" className="danger-action" disabled={busy} onClick={remove}><Trash2/>Borrar registro</button>}</section></div>;
}
