import { useEffect,useMemo,useRef,useState } from "react";
import { createPortal } from "react-dom";
import { Activity,ArrowLeft,CalendarDays,Check,ChevronDown,Clock,Copy,Dumbbell,FileUp,History,Pause,Play,Plus,RotateCcw,Search,Signal,SignalZero,Trash2,X } from "lucide-react";
import { api,bodyProgressApi,workoutApi,type PlannedWorkoutExercise,type TodayWorkout,type WorkoutDayAdjustment,type WorkoutExercise,type WorkoutPlan,type WorkoutSession,type WorkoutSet,type WorkoutSummary } from "./api";
import { pendingOperations,queueOperation,removeOperations,type OfflineOperation } from "./workoutOffline";

export function WorkoutHub({onClose,onImport,onWorkoutChanged}:{onClose:()=>void;onImport:()=>void;onWorkoutChanged?:()=>void}){
 const [today,setToday]=useState<TodayWorkout|null>(null),[scheduled,setScheduled]=useState<TodayWorkout[]>([]),[missed,setMissed]=useState<Array<{date:string;workout:TodayWorkout}>>([]),[scheduleDate,setScheduleDate]=useState(localDate(new Date())),[session,setSession]=useState<WorkoutSession|null>(null),[history,setHistory]=useState<WorkoutSummary[]>([]),[plans,setPlans]=useState<WorkoutPlan[]>([]),[selectedPlanId,setSelectedPlanId]=useState<string|null>(null),[planExercises,setPlanExercises]=useState<PlannedWorkoutExercise[]>([]),[view,setView]=useState<"today"|"plan"|"active"|"history"|"summary"|"manage">("today"),[busy,setBusy]=useState(false),[sync,setSync]=useState("Cambios guardados");
 const loadMissed=async()=>{const dates=Array.from({length:7},(_,index)=>localDate(new Date(Date.now()-(index+1)*86400000))),lists=await Promise.all(dates.map(date=>workoutApi.byDate(date).catch(()=>[])));setMissed(lists.flatMap((workouts,index)=>workouts.map(workout=>({date:dates[index],workout}))))};
 const load=async(date=scheduleDate)=>{const [t,a,h,list]=await Promise.all([workoutApi.today().catch(()=>({workout:null,adjustment:null,workouts:[]})),workoutApi.active().catch(()=>null),workoutApi.history().catch(()=>[]),workoutApi.byDate(date).catch(()=>[])]);setToday(t.workout??null);setScheduled(date===localDate(new Date())?(t.workouts||list):list);setSession(a);setHistory(h);if(a)setView("active")};
 useEffect(()=>{void load();void loadMissed()},[]);
 const loadPlanDetails=async(id?:string)=>setPlanExercises(id?await workoutApi.planDetails(id):[]);
 const loadPlans=async()=>{try{const rows=await workoutApi.plans();setPlans(rows);const selected=rows.find(plan=>plan.id===selectedPlanId)||rows.find(plan=>plan.status==="ACTIVE")||rows[0];setSelectedPlanId(selected?.id||null);await loadPlanDetails(selected?.id)}catch{setPlans([]);setSelectedPlanId(null);setPlanExercises([])}};
 useEffect(()=>{void loadPlans()},[]);
 const syncPending=async()=>{if(!navigator.onLine||!session)return;const ops=await pendingOperations(session.header.id);if(!ops.length){setSync("Cambios guardados");return}setSync("Guardando cambios…");try{const result=await workoutApi.sync(session.header.id,ops);await removeOperations(result.filter(x=>x.result==="APPLIED").map(x=>x.operationId));setSync(result.some(x=>x.result==="CONFLICT")?"Revisar cambios":"Cambios guardados");setSession(await workoutApi.one(session.header.id))}catch{setSync("Pendiente de guardar")}};
 useEffect(()=>{const online=()=>void syncPending();window.addEventListener("online",online);return()=>window.removeEventListener("online",online)},[session?.header.id]);
 const start=async(free=false,workout=today,date=scheduleDate)=>{setBusy(true);try{const s=await workoutApi.start({workoutPlanDayId:free?undefined:workout?.dayId,name:free?"Entrenamiento libre":undefined,plannedDate:date,clientExternalId:crypto.randomUUID()});setSession(s);setView("active");navigator.vibrate?.(35)}finally{setBusy(false)}};
 return <div className="overlay"><section className="modal workout-hub"><header className="workout-top"><div><small>{view==="plan"||view==="manage"?"PLANIFICACIÓN":"EJECUCIÓN REAL"}</small><h2>{view==="history"?"Histórico":view==="plan"?"Plan semanal":view==="manage"?"Gestión":session?.header.name||"Entrenamiento"}</h2></div><button onClick={onClose}><X/></button></header>
 <nav className="workout-tabs"><button className={view==="today"?"active":""} onClick={()=>setView("today")}><Dumbbell/>Hoy</button><button className={view==="plan"?"active":""} onClick={()=>setView("plan")}><CalendarDays/>Plan</button><button className={view==="active"?"active":""} disabled={!session} onClick={()=>setView("active")}><Play/>Sesión</button><button className={view==="history"?"active":""} onClick={()=>setView("history")}><History/>Histórico</button><button className={view==="manage"?"active":""} onClick={()=>setView("manage")}><FileUp/>Gestión</button></nav>
 {view==="today"&&<div className="today-workout-shell"><TodayScreen workouts={scheduled} date={scheduleDate} active={session} history={history} busy={busy} changeDate={async()=>undefined} onStart={start} onContinue={()=>setView("active")} onHistory={()=>setView("history")} onChanged={async()=>{await load();await loadMissed();onWorkoutChanged?.()}}/></div>}
 {view==="plan"&&<WorkoutPlanView plan={plans.find(item=>item.id===selectedPlanId)||plans.find(item=>item.status==="ACTIVE")||plans[0]} exercises={planExercises} onDeleted={loadPlans} onWorkoutChanged={async()=>{await load();onWorkoutChanged?.()}}/>}
 {view==="active"&&session&&<ActiveWorkout session={session} sync={sync} setSession={setSession} onSync={syncPending} onCancel={async()=>{await load();setView("today")}} onFinish={()=>{void load();void loadMissed();setView("summary");onWorkoutChanged?.()}}/>}
 {view==="history"&&<WorkoutHistory rows={history} missed={missed} onRegister={(workout,date)=>void start(false,workout,date)} onOpen={async id=>{setSession(await workoutApi.one(id));setView("summary")}} onDeleted={id=>setHistory(current=>current.filter(row=>row.id!==id))}/>}
 {view==="summary"&&session&&<WorkoutSummaryView session={session} onBack={()=>{void load();void loadMissed();setView("history")}}/>}
 {view==="manage"&&<WorkoutManagement plans={plans} onImport={onImport} refresh={loadPlans} onOpenPlan={async id=>{setSelectedPlanId(id);await loadPlanDetails(id);setView("plan")}}/>}
 </section></div>
}

function WorkoutPlanView({plan,exercises,onDeleted,onWorkoutChanged}:{plan?:WorkoutPlan;exercises:PlannedWorkoutExercise[];onDeleted:()=>Promise<void>;onWorkoutChanged:()=>Promise<void>}){
 const weeks=[...new Set(exercises.map(item=>item.weekNumber))].sort((a,b)=>a-b),elapsedWeek=plan?.validFrom?Math.max(0,Math.floor((new Date(`${localDate(new Date())}T12:00:00`).getTime()-new Date(`${plan.validFrom}T12:00:00`).getTime())/(7*86400000))):0,planWeek=weeks.length?weeks[elapsedWeek%weeks.length]:1,[week,setWeek]=useState(planWeek);
 const [changeDay,setChangeDay]=useState<{id:string;name:string;date:string;completedSession?:WorkoutSummary}|null>(null);
 const [adjustments,setAdjustments]=useState<WorkoutDayAdjustment[]>([]);
 const [completedSessions,setCompletedSessions]=useState<WorkoutSummary[]>([]);
 const loadAdjustments=async()=>{if(!plan)return;try{setAdjustments(await workoutApi.adjustments(plan.id))}catch{setAdjustments([])}};
 useEffect(()=>{void loadAdjustments()},[plan?.id]);
 useEffect(()=>{void workoutApi.history(0,50).then(setCompletedSessions).catch(()=>setCompletedSessions([]))},[plan?.id]);
 useEffect(()=>{if(!weeks.length)return;setWeek(weeks.includes(planWeek)?planWeek:weeks[0])},[plan?.id,exercises]);
 const todayDate=localDate(new Date()),todayNumber=new Date().getDay()||7;
 const rows=exercises.filter(item=>item.weekNumber===week);
 const movedToToday=adjustments.find(item=>item.status==="MOVED"&&item.scheduledDate===todayDate&&rows.some(row=>row.dayId===item.dayId));
 const preferredDay=movedToToday?.dayNumber??todayNumber;
 const days=[...new Set(rows.map(item=>item.dayNumber))].sort((a,b)=>a===preferredDay?-1:b===preferredDay?1:a-b);
 const adjustmentFor=(dayId:string,date:string)=>adjustments.find(item=>item.dayId===dayId&&item.originalDate===date);
 if(!plan)return <div className="workout-plan-empty"><CalendarDays/><h3>No hay un plan importado</h3><p>Importa y activa uno para consultar aquí toda tu semana.</p></div>;
 return <div className="workout-plan-view"><section className="workout-plan-hero"><span><small>PLAN ACTIVO · VERSIÓN {plan.version}</small><h3>{plan.name}</h3><p>{plan.validFrom||"Sin fecha inicial"}{plan.validUntil?` — ${plan.validUntil}`:""}</p></span><strong>{days.length}<small>días esta semana</small></strong></section><button className="delete-workout-plan" onClick={async()=>{if(confirm("¿Eliminar este plan de entrenamiento? Las sesiones ya realizadas conservarán su histórico.")){await workoutApi.deletePlan(plan.id);await onDeleted()}}}><Trash2/>Eliminar plan</button>{weeks.length>1&&<div className="workout-week-tabs">{weeks.map(value=><button className={value===week?"active":""} key={value} onClick={()=>setWeek(value)}>Semana {value}</button>)}</div>}<div className="workout-plan-days">{days.map((day,index)=>{const dayRows=rows.filter(item=>item.dayNumber===day),first=dayRows[0],name=first?.sessionName||first?.dayName||"Entrenamiento",date=nextDateForDay(day),adjustment=first?adjustmentFor(first.dayId,date):undefined,scheduledDate=adjustment?.status==="MOVED"&&adjustment.scheduledDate?adjustment.scheduledDate:date,done=first&&completedSessions.find(session=>session.workoutPlanDayId===first.dayId&&session.status==="COMPLETED"&&session.date===scheduledDate);return <details key={day} className={done?"workout-day-completed":undefined} open={index===0}><summary><span><small>DÍA {day}</small><b>{name}</b><em>{first?.dayName}{adjustment?.status==="MOVED"&&adjustment.scheduledDate?` · Movido al ${new Date(`${adjustment.scheduledDate}T12:00:00`).toLocaleDateString("es",{weekday:"long",day:"numeric",month:"short"})}`:adjustment?.status==="SKIPPED"?" · No realizado":""} · {dayRows.length} ejercicios</em>{done&&<span className="plan-completed-label">Realizado el {new Date(`${done.date}T12:00:00`).toLocaleDateString("es",{day:"numeric",month:"long"})}</span>}</span><span className="plan-day-actions"><button title="Cambiar este día" onClick={event=>{event.preventDefault();event.stopPropagation();setChangeDay({id:first.dayId,name,date,completedSession:done})}}><CalendarDays/>Cambiar</button><ChevronDown/></span></summary><div>{dayRows.map(item=><article key={`${day}-${item.order}`}><i>{String(item.order).padStart(2,"0")}</i><span><b>{item.exercise}</b><small>{item.muscleGroup||"Ejercicio"}{item.equipment?` · ${item.equipment}`:""}</small></span><strong>{item.sets}×{item.repsMin}-{item.repsMax}<small>{item.targetRir!=null?`RIR ${item.targetRir}`:item.targetRpe!=null?`RPE ${item.targetRpe}`:""}</small></strong>{item.instructions&&<p>{item.instructions}</p>}</article>)}</div></details>})}</div>{changeDay&&<PlanDayChangeSheet day={changeDay} close={()=>setChangeDay(null)} saved={async()=>{setChangeDay(null);await Promise.all([loadAdjustments(),onWorkoutChanged()])}}/>}</div>
}

function nextDateForDay(day:number){return dateForCurrentWeekDay(day)}
function dateForCurrentWeekDay(day:number){const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()-(date.getDay()||7)+day);return localDate(date)}
function localDate(date:Date){const year=date.getFullYear(),month=String(date.getMonth()+1).padStart(2,"0"),day=String(date.getDate()).padStart(2,"0");return `${year}-${month}-${day}`}
function completedSessionId(session?:WorkoutSummary){if(!session)throw new Error("No hay una sesión realizada que anular");return session.id}
function PlanDayChangeSheet({day,close,saved}:{day:{id:string;name:string;date:string;completedSession?:WorkoutSummary};close:()=>void;saved:()=>void}){
 const now=new Date(),monday=new Date(now);monday.setHours(12,0,0,0);monday.setDate(now.getDate()-(now.getDay()||7)+1);const dates=Array.from({length:14},(_,index)=>{const date=new Date(monday);date.setDate(monday.getDate()+index);return date}),available=dates.filter(date=>localDate(date)!==day.date),preferred=available.find(date=>localDate(date)===localDate(new Date(Date.now()-86400000)))||available[0],[target,setTarget]=useState(localDate(preferred)),[busy,setBusy]=useState(false);
 return createPortal(<div className="workout-change-overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="workout-change-dialog" role="dialog" aria-modal="true" aria-labelledby="change-workout-title"><button className="close-sheet" onClick={close} aria-label="Cerrar"><X/></button><small>CAMBIO DE PLAN</small><h2 id="change-workout-title">Cambiar entrenamiento</h2><p><b>{day.name}</b> estaba previsto para {new Date(`${day.date}T12:00:00`).toLocaleDateString("es",{weekday:"long",day:"numeric",month:"long"})}.</p><div className="unavailable-options"><section><CalendarDays/><span><b>Mover a otro día</b><small>Conserva todos sus ejercicios y el seguimiento sabrá cuándo lo hiciste.</small></span><select value={target} onChange={event=>setTarget(event.target.value)}>{dates.map(date=><option key={localDate(date)} value={localDate(date)}>{date.toLocaleDateString("es",{weekday:"long",day:"numeric",month:"short"})}</option>)}</select><button disabled={busy} onClick={async()=>{setBusy(true);try{await workoutApi.rescheduleDay(day.id,day.date,target);saved()}finally{setBusy(false)}}}>Mover entrenamiento</button></section><section className="skip-workout"><X/><span><b>No lo haré</b><small>Quedará como no realizado. Cualquier deporte que hagas se registra aparte desde Inicio.</small></span><button disabled={busy} onClick={async()=>{if(confirm("¿Marcar este entrenamiento como no realizado?")){setBusy(true);try{await workoutApi.skipDay(day.id,day.date,"No disponible");saved()}finally{setBusy(false)}}}}>Marcar como no realizado</button></section>{day.completedSession&&<section className="skip-workout"><Trash2/><span><b>Anular sesión realizada</b><small>Elimina ese registro y la marca como no realizada. Úsalo solo si se asignó al día equivocado.</small></span><button disabled={busy} onClick={async()=>{if(confirm("¿Anular este registro? Sus métricas y récords dejarán de contar y el día quedará como no realizado.")){setBusy(true);try{await workoutApi.deleteSession(completedSessionId(day.completedSession));await workoutApi.skipDay(day.id,day.date,"Registro anulado");saved()}finally{setBusy(false)}}}}>Anular sesión</button></section>}</div></section></div>,document.body)
}

function TodayScreen({workouts,date,active,history,busy,changeDate,onStart,onContinue,onHistory,onChanged}:{workouts:TodayWorkout[];date:string;active:WorkoutSession|null;history:WorkoutSummary[];busy:boolean;changeDate:(date:string)=>Promise<void>;onStart:(free?:boolean,workout?:TodayWorkout|null,date?:string)=>void;onContinue:()=>void;onHistory:()=>void;onChanged:()=>Promise<void>}){const [unavailable,setUnavailable]=useState<TodayWorkout|null>(null),today=localDate(new Date()),yesterday=localDate(new Date(Date.now()-86400000));
 return <div className="today-workout workout-agenda">{active&&<button className="continue-workout" onClick={onContinue}><span><small>SESIÓN EN CURSO</small><b>{active.header.name}</b></span><Play/></button>}<div className="workout-date-switch"><button className={date===yesterday?"active":""} onClick={()=>void changeDate(yesterday)}>Ayer</button><button className={date===today?"active":""} onClick={()=>void changeDate(today)}>Hoy</button><input type="date" min={localDate(new Date(Date.now()-7*86400000))} max={localDate(new Date(Date.now()+14*86400000))} value={date} onChange={event=>void changeDate(event.target.value)}/></div>{workouts.length?workouts.map((workout,index)=><section className="scheduled-workout" key={`${workout.dayId}-${date}`}><div className="today-hero"><span className="day-badge">{workouts.length>1?`SESIÓN ${index+1} DE ${workouts.length}`:`DÍA ${workout.dayNumber}`}</span><p>{workout.planName} · v{workout.planVersion}</p><h1>{workout.sessionName}</h1><div className="today-meta"><span><Clock/>~{workout.estimatedMinutes||45} min</span><span><Dumbbell/>{workout.exerciseCount} ejercicios</span></div></div><details className="agenda-exercises"><summary>Ver ejercicios</summary><div className="planned-list">{workout.exercises.map((exercise,i)=><div key={exercise.exerciseId}><i>{String(i+1).padStart(2,"0")}</i><span><b>{exercise.name}</b><small>{exercise.muscleGroup||"Ejercicio"} · {exercise.sets}×{exercise.repsMin}-{exercise.repsMax}</small></span></div>)}</div></details><button className="start-workout" disabled={busy||!!active} onClick={()=>onStart(false,workout,date)}><Play/>{date<today?"Registrar entrenamiento pendiente":"Empezar entrenamiento"}</button>{date===today&&<button className="cant-train-today" disabled={!!active} onClick={()=>setUnavailable(workout)}>Cambiar este entrenamiento…</button>}</section>):<div className="workout-empty"><Dumbbell/><h3>No hay entrenamientos para este día</h3><p>Consulta ayer si se te quedó uno pendiente o abre Plan para mover una sesión.</p></div>}<button className="secondary-action free-session-action" disabled={!!active} onClick={()=>onStart(true,null,date)}><Plus/>Sesión libre</button>{history.length>0&&<button className="last-session" onClick={onHistory}><History/><span><small>ÚLTIMA SESIÓN</small><b>{history[0].name}</b></span><strong>{Math.round((history[0].durationSeconds||0)/60)} min</strong></button>}{unavailable&&<UnavailableWorkoutSheet today={unavailable} close={()=>setUnavailable(null)} saved={async()=>{setUnavailable(null);await onChanged()}}/>}</div>
}

function UnavailableWorkoutSheet({today,close,saved}:{today:TodayWorkout;close:()=>void;saved:()=>Promise<void>}){
 const now=new Date();
 const original=localDate(now);
 const yesterday=new Date(now);
 yesterday.setDate(yesterday.getDate()-1);
 const dates=Array.from({length:14},(_,index)=>{
  const date=new Date(now);
  date.setHours(12,0,0,0);
  date.setDate(date.getDate()+index-6);
  return date;
 }).filter(date=>localDate(date)!==original);
 const [target,setTarget]=useState(localDate(yesterday));
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState("");

 return <div className="finish-sheet unavailable-workout">
  <button className="close-sheet" onClick={close}><X/></button>
  <small>CAMBIO DE PLAN</small>
  <h2>Cambiar entrenamiento</h2>
  <p>Estás cambiando <b>{today.sessionName}</b>. Si el día elegido ya tiene otra sesión, te avisaremos antes de añadir las dos.</p>
  <div className="unavailable-options">
   <section>
    <CalendarDays/>
    <span><b>Mover a otro día</b><small>Puedes corregirlo hasta seis días atrás y después registrar las métricas desde Histórico.</small></span>
    <select value={target} onChange={event=>setTarget(event.target.value)}>
     {dates.map(date=><option key={localDate(date)} value={localDate(date)}>{localDate(date)===localDate(yesterday)?"Ayer · ":""}{date.toLocaleDateString("es",{weekday:"long",day:"numeric",month:"short"})}</option>)}
    </select>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <button disabled={busy} onClick={async()=>{
     setBusy(true);
     setError("");
     try{
      await workoutApi.rescheduleDay(today.dayId,original,target);
      await saved();
     }catch(cause){
      setError(cause instanceof Error?cause.message:"No se pudo mover el entrenamiento. Inténtalo de nuevo.");
     }finally{
      setBusy(false);
     }
    }}>{busy?"Moviendo…":"Mover entrenamiento"}</button>
   </section>
   <section className="skip-workout">
    <X/>
    <span><b>No lo haré esta semana</b><small>Quedará como no realizado sin afectar a las demás sesiones de hoy.</small></span>
    <button disabled={busy} onClick={async()=>{if(confirm("¿Marcar este entrenamiento como no realizado?")){setBusy(true);try{await workoutApi.skipDay(today.dayId,original,"No disponible");await saved()}finally{setBusy(false)}}}}>Marcar como no realizado</button>
   </section>
  </div>
 </div>
}

function ActiveWorkout({session,sync,setSession,onSync,onCancel,onFinish}:{session:WorkoutSession;sync:string;setSession:(s:WorkoutSession)=>void;onSync:()=>void;onCancel:()=>Promise<void>;onFinish:()=>void}){
 const sessionSeconds=(at:number)=>Math.max(0,Math.floor((at-new Date(session.header.startedAt).getTime())/1000)-(session.header.pausedSeconds||0));
 const [now,setNow]=useState(Date.now()),[pausedElapsed,setPausedElapsed]=useState<number|null>(session.header.status==="PAUSED"?sessionSeconds(session.header.pausedAt?new Date(session.header.pausedAt).getTime():Date.now()):null),[expanded,setExpanded]=useState(session.exercises.find(e=>!e.completed)?.id||session.exercises[0]?.id),[restEnd,setRestEnd]=useState<number|null>(null),[restNotice,setRestNotice]=useState(false),[finish,setFinish]=useState(false),[activity,setActivity]=useState<WorkoutExercise|null>(null),[exercisePicker,setExercisePicker]=useState(false);
 const restTimerId=useRef<string|null>(null),restEndRef=useRef<number|null>(null);
 useEffect(()=>{if(session.header.status==="COMPLETED"){onFinish();return}const id=setInterval(()=>{if(session.header.status!=="PAUSED")setNow(Date.now())},1000);return()=>clearInterval(id)},[session.header.status]);
 useEffect(()=>{if(session.header.status==="PAUSED")setPausedElapsed(sessionSeconds(session.header.pausedAt?new Date(session.header.pausedAt).getTime():Date.now()));else setPausedElapsed(null)},[session.header.status,session.header.startedAt,session.header.pausedAt,session.header.pausedSeconds]);
 const elapsed=pausedElapsed??sessionSeconds(now);const completed=session.exercises.filter(e=>e.completed).length;const rest=restEnd?Math.max(0,Math.ceil((restEnd-now)/1000)):0;
 useEffect(()=>{restEndRef.current=restEnd},[restEnd]);
 useEffect(()=>{if(restEnd&&rest===0){navigator.vibrate?.([150,80,150]);setRestNotice(true);setTimeout(()=>setRestNotice(false),3500);restTimerId.current=null;restEndRef.current=null;setRestEnd(null)}},[rest,restEnd]);
 const startRest=(seconds:number)=>{const previous=restTimerId.current;if(previous)void api.cancelRestPush(previous).catch(()=>undefined);const id=crypto.randomUUID(),end=Date.now()+seconds*1000;restTimerId.current=id;restEndRef.current=end;setRestEnd(end);void api.scheduleRestPush(id,new Date(end).toISOString(),session.header.id).catch(()=>undefined)};
 const rescheduleRest=(seconds:number)=>{const id=restTimerId.current;if(!id||!restEnd)return;const end=restEnd+seconds*1000;restEndRef.current=end;setRestEnd(end);void api.scheduleRestPush(id,new Date(end).toISOString(),session.header.id).catch(()=>undefined)};
 const cancelRest=()=>{const id=restTimerId.current;if(id)void api.cancelRestPush(id).catch(()=>undefined);restTimerId.current=null;restEndRef.current=null;setRestEnd(null)};
 const refresh=()=>workoutApi.one(session.header.id).then(setSession);
 const addExercise=()=>setExercisePicker(true);
 return <div className="active-workout"><div className={`active-status ${session.header.status==="PAUSED"?"paused":""}`}><div><Clock/><b>{formatTime(elapsed)}</b><small>{session.header.status==="PAUSED"?"SESIÓN EN PAUSA":"DURACIÓN DE LA SESIÓN"}</small></div><div className="progress"><span style={{width:`${session.exercises.length?completed/session.exercises.length*100:0}%`}}/><small>{completed} de {session.exercises.length} ejercicios completados</small></div><button aria-label={session.header.status==="PAUSED"?"Reanudar entrenamiento":"Pausar entrenamiento"} title={session.header.status==="PAUSED"?"Reanudar":"Pausar"} onClick={async()=>setSession(session.header.status==="PAUSED"?await workoutApi.resume(session.header.id):await workoutApi.pause(session.header.id))}>{session.header.status==="PAUSED"?<Play/>:<Pause/>}</button></div><button className={`sync-state ${sync==="Cambios guardados"?"ok":""}`} title="ANURA guarda automáticamente las series y pesos de esta sesión" onClick={onSync}>{navigator.onLine?<Signal/>:<SignalZero/>}{navigator.onLine?sync:"Guardado en este dispositivo"}</button>
 {restNotice&&<div className="rest-finished-toast" role="status"><Check/><span><b>Descanso terminado</b><small>Vamos a por la siguiente serie.</small></span></div>}
 {restEnd&&<div className={`rest-timer ${rest<=5?"ending":""}`}><span><small>DESCANSO</small><b>{formatTime(rest)}</b></span><button onClick={()=>rescheduleRest(-15)}>−15</button><button onClick={()=>rescheduleRest(15)}>+15</button><button onClick={cancelRest}><X/></button></div>}
 {session.exercises.map(ex=><ExerciseCard key={ex.id} sessionId={session.header.id} exercise={ex} open={expanded===ex.id} onToggle={()=>setExpanded(expanded===ex.id?"":ex.id)} refresh={refresh} startRest={startRest} onActivity={()=>setActivity(ex)}/>)}
 <div className="workout-session-actions"><button className="secondary-action" onClick={addExercise}><Plus/>Añadir ejercicio</button><button className="cancel-workout" onClick={async()=>{if(confirm("¿Cancelar este entrenamiento en curso? Se guardará como cancelado y dejará de aparecer como sesión activa.")){await workoutApi.abandon(session.header.id,"Cancelado por el usuario");await onCancel()}}}><X/>Cancelar sesión</button></div><button className="finish-workout" onClick={()=>setFinish(true)}><Check/>Finalizar entrenamiento</button>{exercisePicker&&<ExercisePicker title="Añadir ejercicio" close={()=>setExercisePicker(false)} selected={async exercise=>{await workoutApi.addExercise(session.header.id,{exerciseId:exercise.id});setExercisePicker(false);await refresh()}}/>}{activity&&<ActivitySheet session={session} exercise={activity} close={()=>setActivity(null)} saved={async()=>{setActivity(null);await refresh()}}/>}{finish&&<FinishSheet session={session} close={()=>setFinish(false)} done={async body=>{setSession(await workoutApi.complete(session.header.id,body));setFinish(false);onFinish()}}/>}</div>
}

function ExerciseCard({sessionId,exercise,open,onToggle,refresh,startRest,onActivity}:{sessionId:string;exercise:WorkoutExercise;open:boolean;onToggle:()=>void;refresh:()=>Promise<unknown>;startRest:(s:number)=>void;onActivity:()=>void}) {
  const template=exercise.sets.at(-1);
  const [exercisePicker,setExercisePicker]=useState(false),[setError,setSetError]=useState("");
  const add=async(copy?:WorkoutSet)=>{const body={setNumber:exercise.sets.length+1,setType:copy?.setType||"WORKING",weight:copy?.weight,repetitions:copy?.repetitions,rir:copy?.rir??exercise.targetRir,restSeconds:exercise.targetRestSeconds,completed:false,clientExternalId:crypto.randomUUID()};setSetError("");try{await workoutApi.addSet(sessionId,exercise.id,body);await refresh()}catch(cause){if(navigator.onLine){setSetError(cause instanceof Error?cause.message:"No se pudo añadir la serie");return}await queueOperation({operationId:crypto.randomUUID(),clientEntityId:body.clientExternalId,operationType:"ADD_SET",entityType:"SET",occurredAt:new Date().toISOString(),payload:{exercisePerformanceId:exercise.id,...body},sessionId});await refresh().catch(()=>undefined)}};
 const copyLast=async()=>{const last=await workoutApi.lastPerformance(exercise.exerciseId);if(last)await add({...last,id:"",setNumber:0,setType:"WORKING",completed:false,clientExternalId:crypto.randomUUID()})};
 return <article className={`live-exercise ${open?"open":""}`}><button className="exercise-head" onClick={onToggle}><span className={exercise.completed?"done":""}>{exercise.completed?<Check/>:exercise.order}</span><div><small>{exercise.muscleGroup||"EJERCICIO"}</small><h3>{exercise.name}</h3><p>{exercise.targetSets||"–"} series · {exercise.targetRepsMin||"–"}-{exercise.targetRepsMax||"–"} reps {exercise.targetRir!=null?`· RIR ${exercise.targetRir}`:""}</p></div><ChevronDown/></button><div className="exercise-body">{exercise.instructions&&<p className="exercise-tip">{exercise.instructions}</p>}<div className="set-labels"><span>SET</span><span>KG</span><span>REPS</span><span>RIR</span><span></span></div>{exercise.sets.map(s=><SetRow key={s.id} session={sessionId} exercise={exercise.id} value={s} refresh={refresh} rest={()=>startRest(s.restSeconds||exercise.targetRestSeconds||90)}/>)}<div className="set-actions"><button onClick={()=>void add()}><Plus/>Añadir</button><button disabled={!template} onClick={()=>void add(template)}><Copy/>Duplicar</button><button onClick={copyLast}><History/>Última</button></div>{setError&&<p className="form-error">{setError}</p>}<div className="exercise-actions"><button onClick={()=>setExercisePicker(true)}>Otro ejercicio</button><button disabled={exercise.completed} onClick={onActivity}><Activity/>Deporte/cardio</button><button onClick={async()=>{const intensity=Number(prompt("Intensidad de molestia (0-10)","0"));if(Number.isFinite(intensity)){await workoutApi.pain(sessionId,exercise.id,{intensity,area:"Sin especificar"});await refresh()}}}>Molestia</button><button onClick={async()=>{await workoutApi.finishExercise(sessionId,exercise.id);await refresh()}}><Check/>{exercise.completed?"Reabrir":"Terminar"}</button></div>{exercise.painReported&&<p className="pain-note">Revisa la técnica o el ejercicio y consulta con un profesional si el dolor persiste o es intenso.</p>}</div>{exercisePicker&&<ExercisePicker title={`Sustituir ${exercise.name}`} close={()=>setExercisePicker(false)} selected={async selected=>{await workoutApi.substitute(sessionId,exercise.id,{replacementExerciseId:selected.id,reason:"PREFERENCE",notes:"Sustitución desde entrenamiento"});setExercisePicker(false);await refresh()}}/>}</article>
}

type ExerciseOption={id:string;name:string;muscleGroup?:string;equipment?:string};
const muscleOrder=["Pecho","Espalda","Hombros","Bíceps","Tríceps","Cuádriceps","Isquiotibiales","Glúteos","Gemelos","Core","Antebrazos","Cardio","Cuerpo completo","Otro"];
function canonicalMuscle(value?:string){const text=(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();if(/pecho|pectoral/.test(text))return"Pecho";if(/espalda|dorsal|trapecio/.test(text))return"Espalda";if(/hombro|deltoid/.test(text))return"Hombros";if(/bicep/.test(text))return"Bíceps";if(/tricep/.test(text))return"Tríceps";if(/cuadricep/.test(text))return"Cuádriceps";if(/isquio|femoral/.test(text))return"Isquiotibiales";if(/glute/.test(text))return"Glúteos";if(/gemelo|pantorrilla/.test(text))return"Gemelos";if(/core|abdomen|abdominal/.test(text))return"Core";if(/antebrazo/.test(text))return"Antebrazos";if(/cardio|carrera|bicicleta/.test(text))return"Cardio";if(/completo|full/.test(text))return"Cuerpo completo";return"Otro"}
function ExercisePicker({title,close,selected}:{title:string;close:()=>void;selected:(exercise:ExerciseOption)=>Promise<void>}){
 const [options,setOptions]=useState<ExerciseOption[]>([]),[muscle,setMuscle]=useState<string|null>(null),[search,setSearch]=useState(""),[custom,setCustom]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{void workoutApi.exercises().then(setOptions).catch(()=>setError("No se pudo cargar el catálogo"))},[]);
 const groups=muscleOrder.filter(group=>group==="Otro"||options.some(option=>canonicalMuscle(option.muscleGroup)===group)),visible=options.filter(option=>canonicalMuscle(option.muscleGroup)===muscle&&option.name.toLocaleLowerCase("es").includes(search.toLocaleLowerCase("es")));
 const choose=async(option:ExerciseOption)=>{setBusy(true);setError("");try{await selected(option)}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo seleccionar el ejercicio");setBusy(false)}};
 const saveCustom=async()=>{if(custom.trim().length<2){setError("Escribe el nombre del ejercicio");return}setBusy(true);setError("");try{await selected(await workoutApi.createExercise({name:custom.trim(),muscleGroup:"Otro"}))}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo crear el ejercicio");setBusy(false)}};
 return createPortal(<div className="exercise-picker-overlay" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)close()}}><section className="exercise-picker" role="dialog" aria-modal="true" aria-label={title}><header>{muscle&&<button className="exercise-picker-back" onClick={()=>{setMuscle(null);setSearch("");setCustom("")}}><ArrowLeft/></button>}<span><small>CATÁLOGO DE EJERCICIOS</small><h2>{muscle||title}</h2><p>{muscle?"Selecciona el ejercicio concreto":title}</p></span><button className="close-sheet" onClick={close} disabled={busy}><X/></button></header>{!muscle?<div className="muscle-grid">{groups.map(group=><button key={group} className={group==="Otro"?"other":""} onClick={()=>setMuscle(group)}><span><Dumbbell/></span><b>{group}</b><small>{group==="Otro"?"Escribir ejercicio":`${options.filter(option=>canonicalMuscle(option.muscleGroup)===group).length} ejercicios`}</small></button>)}</div>:muscle==="Otro"?<div className="custom-exercise"><span><Plus/></span><h3>Ejercicio personalizado</h3><p>Se guardará en tu catálogo para poder reutilizarlo.</p><label>Nombre del ejercicio<input autoFocus value={custom} maxLength={180} onChange={event=>setCustom(event.target.value)} placeholder="Ej. Escalada, trabajo técnico…" onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();void saveCustom()}}}/></label><button className="primary" disabled={busy||custom.trim().length<2} onClick={()=>void saveCustom()}>{busy?"Guardando…":"Usar este ejercicio"}</button></div>:<><label className="exercise-search"><Search/><input autoFocus value={search} onChange={event=>setSearch(event.target.value)} placeholder={`Buscar en ${muscle.toLowerCase()}…`}/></label><div className="exercise-option-list">{visible.map(option=><button key={option.id} disabled={busy} onClick={()=>void choose(option)}><span><b>{option.name}</b><small>{option.equipment||"Sin equipo indicado"}</small></span><Plus/></button>)}{!visible.length&&<p>No hay ejercicios que coincidan con la búsqueda.</p>}</div></>}{error&&<p className="form-error">{error}</p>}</section></div>,document.body)
}

function SetRow({session,exercise,value,refresh,rest}:{session:string;exercise:string;value:WorkoutSet;refresh:()=>Promise<unknown>;rest:()=>void}) {
 const [draft,setDraft]=useState(value);
 const save=async(next:WorkoutSet)=>{setDraft(next);try{await workoutApi.updateSet(session,exercise,value.id,{...next,clientExternalId:value.clientExternalId});await refresh()}catch{await queueOperation({operationId:crypto.randomUUID(),clientEntityId:value.clientExternalId,operationType:"UPDATE_SET",entityType:"SET",occurredAt:new Date().toISOString(),payload:{exercisePerformanceId:exercise,setId:value.id,...next},sessionId:session})}if(next.completed&&!value.completed){navigator.vibrate?.(25);rest()}};
 const remove=async()=>{try{await workoutApi.deleteSet(session,exercise,value.id);await refresh()}catch{await queueOperation({operationId:crypto.randomUUID(),clientEntityId:value.clientExternalId,operationType:"DELETE_SET",entityType:"SET",occurredAt:new Date().toISOString(),payload:{exercisePerformanceId:exercise,setId:value.id},sessionId:session})}};
 return <div className={`set-row ${draft.completed?"completed":""}`}><b>{value.setNumber}</b><input aria-label="Peso" type="number" step="0.1" inputMode="decimal" value={draft.weight??""} onChange={e=>setDraft({...draft,weight:e.target.value===""?undefined:Number(e.target.value)})} onBlur={()=>void save(draft)}/><input aria-label="Repeticiones" inputMode="numeric" value={draft.repetitions??""} onChange={e=>setDraft({...draft,repetitions:e.target.value===""?undefined:Number(e.target.value)})} onBlur={()=>void save(draft)}/><input aria-label="RIR" inputMode="decimal" value={draft.rir??""} onChange={e=>setDraft({...draft,rir:e.target.value===""?undefined:Number(e.target.value)})} onBlur={()=>void save(draft)}/><button aria-label="Completar serie" onClick={()=>void save({...draft,completed:!draft.completed})}><Check/></button><button className="set-delete" onClick={remove}><Trash2/></button></div>
}

const sportOptions=[{name:"Pádel",met:7},{name:"Tenis",met:7.3},{name:"Fútbol",met:8},{name:"Correr suave",met:7},{name:"Correr intenso",met:10},{name:"Bicicleta",met:7.5},{name:"Natación",met:8},{name:"Elíptica",met:5.5},{name:"Caminar rápido",met:4.5},{name:"Otro deporte",met:6}];
function ActivitySheet({session,exercise,close,saved}:{session:WorkoutSession;exercise:WorkoutExercise;close:()=>void;saved:()=>Promise<void>}){const [sport,setSport]=useState(sportOptions[0]),[minutes,setMinutes]=useState(60),[weight,setWeight]=useState(70),[calories,setCalories]=useState<number|null>(null),[busy,setBusy]=useState(false);useEffect(()=>{void bodyProgressApi.latest().then(value=>{if(value?.weight)setWeight(Number(value.weight))}).catch(()=>undefined)},[]);const estimate=Math.round(sport.met*3.5*weight/200*minutes),value=calories??estimate;return <div className="finish-sheet activity-sheet"><button className="close-sheet" onClick={close}><X/></button><small>ACTIVIDAD REAL</small><h2>Sustituir {exercise.name}</h2><p>La duración y las calorías que indiques serán las que se mostrarán en esta sesión.</p><form onSubmit={async event=>{event.preventDefault();setBusy(true);try{await workoutApi.recordActivity(session.header.id,exercise.id,{name:sport.name,minutes,calories:value,notes:`Actividad realizada en lugar de ${exercise.name}. Peso usado: ${weight} kg.`});await saved()}finally{setBusy(false)}}}><div className="activity-grid"><label>Actividad<select value={sport.name} onChange={event=>{setSport(sportOptions.find(item=>item.name===event.target.value)||sportOptions[0]);setCalories(null)}}>{sportOptions.map(item=><option key={item.name}>{item.name}</option>)}</select></label><label>Duración real (min)<input type="number" min="5" max="600" value={minutes} onChange={event=>{setMinutes(Number(event.target.value));setCalories(null)}}/></label><label>Peso usado (kg)<input type="number" min="20" max="500" step="0.1" value={weight} onChange={event=>{setWeight(Number(event.target.value));setCalories(null)}}/></label><label>Calorías reales<input type="number" min="0" value={value} onChange={event=>setCalories(Number(event.target.value))}/></label></div><p className="activity-estimate"><b>≈ {estimate} kcal estimadas</b><span>Estimación basada en MET, duración y tu último peso. Puedes sustituirla por el dato del reloj.</span></p><button className="start-workout" disabled={busy}>{busy?"Guardando…":"Guardar actividad y sustituir"}</button></form></div>}

function FinishSheet({session,close,done}:{session:WorkoutSession;close:()=>void;done:(x:object)=>void}){const incomplete=session.exercises.filter(e=>!e.completed).length;return <div className="finish-sheet"><button className="close-sheet" onClick={close}><X/></button><small>RESUMEN FINAL</small><h2>¿Cómo ha ido?</h2><p className="rating-help">Valora solo lo que aplique. El resto no se guardará.</p>{incomplete>0&&<p className="pending-warning">Quedan {incomplete} ejercicios incompletos. Se guardará como sesión parcial.</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const number=(name:string)=>f.has(name)?Number(f.get(name)):undefined;done({globalRpe:number("rpe"),energyLevel:number("energy"),pumpLevel:number("pump"),painLevel:number("pain"),difficultyLevel:number("difficulty"),notes:String(f.get("notes")),adherenceReason:String(f.get("reason")||"")})}}><div className="rating-grid"><OptionalRating name="rpe" label="Esfuerzo (RPE)" initial={7} min={1}/><OptionalRating name="energy" label="Energía" initial={7}/><OptionalRating name="pump" label="Congestión" initial={6}/><OptionalRating name="pain" label="Dolor" initial={0}/><OptionalRating name="difficulty" label="Dificultad" initial={7}/></div>{incomplete>0&&<label className="finish-reason">Motivo<select name="reason" required><option value="">Selecciona</option><option value="TIME">Falta de tiempo</option><option value="FATIGUE">Fatiga</option><option value="PAIN">Dolor o molestia</option><option value="EQUIPMENT">Equipo no disponible</option><option value="OTHER">Otro</option></select></label>}<textarea name="notes" placeholder="Sensaciones y notas…"/><button className="start-workout">Guardar y finalizar</button></form></div>}
function OptionalRating({name,label,initial,min=0}:{name:string;label:string;initial:number;min?:number}){const [enabled,setEnabled]=useState(false),[value,setValue]=useState(initial);return <label className={enabled?"rating-enabled":"rating-disabled"}><span><b>{label}</b>{enabled&&<output>{value}/10</output>}<button type="button" onClick={()=>setEnabled(!enabled)}>{enabled?"Quitar":"Valorar"}</button></span>{enabled?<input name={name} type="range" min={min} max="10" value={value} onChange={e=>setValue(Number(e.target.value))}/>:<em>No aplica</em>}</label>}
function WorkoutHistory({rows,missed,onRegister,onOpen,onDeleted}:{rows:WorkoutSummary[];missed:Array<{date:string;workout:TodayWorkout}>;onRegister:(workout:TodayWorkout,date:string)=>void;onOpen:(id:string)=>void;onDeleted:(id:string)=>void}){return <div className="workout-history">{missed.length>0&&<section className="missed-workouts"><header><small>PENDIENTES DE REGISTRO</small><b>Planificados sin completar</b></header>{missed.map(({date,workout})=><article key={`${date}-${workout.dayId}`}><span className="history-date">{new Date(`${date}T12:00`).toLocaleDateString("es",{day:"2-digit",month:"short"})}</span><span><b>{workout.sessionName}</b><small>Sin entrenamiento ni métricas registradas</small></span><button onClick={()=>onRegister(workout,date)}>Registrar</button></article>)}</section>}{rows.length?rows.map(r=><article key={r.id}><button className="history-open" onClick={()=>onOpen(r.id)}><span className="history-date">{new Date(r.date+"T12:00").toLocaleDateString("es",{day:"2-digit",month:"short"})}</span><span><b>{r.name}</b><small>{r.exercises} ejercicios · {r.sets} series</small></span><strong>{r.activityCalories!=null&&r.activityCalories>0?r.activityCalories:Math.round((r.durationSeconds||45)/60*6)}<small>{r.activityCalories!=null&&r.activityCalories>0?"kcal registradas":"kcal aprox."}</small></strong></button><button className="history-delete" title="Eliminar sesión" aria-label={`Eliminar ${r.name}`} onClick={async()=>{if(confirm("¿Eliminar esta sesión del histórico? También dejará de contar en tu evolución y se eliminarán sus récords. Esta acción no se puede deshacer.")){await workoutApi.deleteSession(r.id);onDeleted(r.id)}}}><Trash2/></button></article>):!missed.length&&<div className="workout-empty"><History/><h3>Tu histórico empieza aquí</h3></div>}</div>}
function WorkoutSummaryView({session,onBack}:{session:WorkoutSession;onBack:()=>void}){const [editing,setEditing]=useState(false),[current,setCurrent]=useState(session),[exercisePicker,setExercisePicker]=useState(false);const refresh=()=>workoutApi.one(session.header.id).then(setCurrent),m=current.metrics,completed=current.exercises.filter(e=>e.completed).length,total=current.exercises.length,activityCalories=current.exercises.reduce((sum,exercise)=>sum+(exercise.activityCalories||0),0),kcal=activityCalories||Math.round((current.header.durationSeconds||45*60)/60*6);return <div className="session-summary"><div className="summary-hero"><Check/><small>ENTRENAMIENTO COMPLETADO</small><h1>{current.header.name}</h1></div><div className="summary-grid"><div><small>ADHERENCIA</small><b>{completed}/{total} ejercicios</b></div><div><small>{activityCalories?"GASTO REGISTRADO":"GASTO ESTIMADO"}</small><b>{activityCalories?"":"≈ "}{kcal} kcal</b></div><div><small>SERIES COMPLETADAS</small><b>{m.sets}</b></div><div><small>DURACIÓN</small><b>{Math.round((current.header.durationSeconds||45*60)/60)} min</b></div></div>{m.maxPain>=5&&<p className="pain-note">Revisa la técnica o el ejercicio y consulta con un profesional si el dolor persiste o es intenso.</p>}<button className="secondary-action" onClick={()=>setEditing(value=>!value)}>{editing?"Cerrar edición":"Editar entreno"}</button>{editing&&<div className="summary-edit-exercises"><DurationEditor session={current} onSaved={setCurrent}/>{current.exercises.map(ex=><ExerciseCard key={ex.id} sessionId={current.header.id} exercise={ex} open={true} onToggle={()=>undefined} refresh={refresh} startRest={()=>undefined} onActivity={()=>undefined}/>)}<button className="secondary-action" onClick={()=>setExercisePicker(true)}><Plus/>Añadir ejercicio y series</button>{exercisePicker&&<ExercisePicker title="Añadir ejercicio a esta sesión" close={()=>setExercisePicker(false)} selected={async exercise=>{await workoutApi.addExercise(current.header.id,{exerciseId:exercise.id});setExercisePicker(false);await refresh()}}/>}</div>}<button className="secondary-action" onClick={onBack}><RotateCcw/>Ver histórico</button></div>}

function WorkoutManagement({plans,onImport,refresh,onOpenPlan}:{plans:WorkoutPlan[];onImport:()=>void;refresh:()=>Promise<void>;onOpenPlan:(id:string)=>Promise<void>}){
 const active=plans.find(plan=>plan.status==="ACTIVE"),drafts=plans.filter(plan=>plan.status==="DRAFT"),past=plans.filter(plan=>plan.status!=="ACTIVE"&&plan.status!=="DRAFT");
 const status=(plan:WorkoutPlan)=>plan.status==="ACTIVE"?"Plan actual":plan.status==="DRAFT"?"Próximo plan":"Plan archivado";
 const PlanCard=({plan}:{plan:WorkoutPlan})=>{
  const remove=async()=>{if(!confirm("¿Eliminar este plan de entrenamiento? Las sesiones realizadas conservarán su histórico."))return;await workoutApi.deletePlan(plan.id);await refresh()};
  return <article><button className="managed-plan-open" onClick={()=>void onOpenPlan(plan.id)}><span><small>{status(plan)}</small><b>{plan.name}</b><em>Versión {plan.version}{plan.validFrom?` · Desde ${plan.validFrom}`:""}{plan.validUntil?` · Hasta ${plan.validUntil}`:""}</em></span></button><div className="managed-plan-actions">{plan.status!=="ACTIVE"&&<button className="managed-plan-activate" onClick={async()=>{await workoutApi.activate(plan.id);await refresh()}}>Activar</button>}<button className="managed-plan-delete" aria-label={`Eliminar ${plan.name}`} onClick={()=>void remove()}><Trash2/><span>Eliminar</span></button></div></article>
 };
 return <div className="workout-management plan-management"><button className="workout-import-action" onClick={onImport}><FileUp/><span><b>Importar entrenamiento</b><small>Sube una nueva planificación o versión</small></span></button><section className="managed-plan-section"><header><small>PLAN ACTUAL</small><b>Lo que se aplica hoy</b></header>{active?<PlanCard plan={active}/>:<p className="managed-plan-empty">No hay un plan activo.</p>}</section>{drafts.length>0&&<section className="managed-plan-section"><header><small>PRÓXIMO PLAN</small><b>Preparado para activarse</b></header>{drafts.map(plan=><PlanCard key={plan.id} plan={plan}/>)}</section>}{past.length>0&&<details className="managed-plan-history"><summary>Historial de planes ({past.length})</summary><div>{past.map(plan=><PlanCard key={plan.id} plan={plan}/>)}</div></details>}</div>
}
function DurationEditor({session,onSaved}:{session:WorkoutSession;onSaved:(session:WorkoutSession)=>void}){const minutes=Math.round((session.header.durationSeconds||45*60)/60);return <button className="secondary-action duration-editor" onClick={async()=>{const input=prompt("Duración real en minutos",String(minutes));const value=Number(input);if(Number.isFinite(value)&&value>0)onSaved(await workoutApi.updateDuration(session.header.id,Math.round(value*60))}}>Editar duración ({minutes} min)</button>}
const formatTime=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
