import { useEffect,useMemo,useState } from "react";
import { createPortal } from "react-dom";
import { Activity,CalendarDays,Check,ChevronDown,Clock,Copy,Dumbbell,FileUp,History,Pause,Play,Plus,RotateCcw,Signal,SignalZero,Trash2,X } from "lucide-react";
import { api,bodyProgressApi,workoutApi,type PlannedWorkoutExercise,type TodayWorkout,type WorkoutDayAdjustment,type WorkoutExercise,type WorkoutPlan,type WorkoutSession,type WorkoutSet,type WorkoutSummary } from "./api";
import { pendingOperations,queueOperation,removeOperations,type OfflineOperation } from "./workoutOffline";

export function WorkoutHub({onClose,onImport,onWorkoutChanged}:{onClose:()=>void;onImport:()=>void;onWorkoutChanged?:()=>void}){
 const [today,setToday]=useState<TodayWorkout|null>(null),[session,setSession]=useState<WorkoutSession|null>(null),[history,setHistory]=useState<WorkoutSummary[]>([]),[plans,setPlans]=useState<WorkoutPlan[]>([]),[planExercises,setPlanExercises]=useState<PlannedWorkoutExercise[]>([]),[view,setView]=useState<"today"|"plan"|"active"|"history"|"summary">("today"),[busy,setBusy]=useState(false),[sync,setSync]=useState("Cambios guardados");
 const load=async()=>{const [t,a,h]=await Promise.all([workoutApi.today().catch(()=>({workout:null,adjustment:null})),workoutApi.active().catch(()=>null),workoutApi.history().catch(()=>[])]);setToday(t.workout??null);setSession(a);setHistory(h);if(a)setView("active")};
 useEffect(()=>{void load()},[]);
 const loadPlans=async()=>{try{const rows=await workoutApi.plans();setPlans(rows);const active=rows.find(plan=>plan.status==="ACTIVE")||rows[0];setPlanExercises(active?await workoutApi.planDetails(active.id):[])}catch{setPlans([]);setPlanExercises([])}};
 useEffect(()=>{void loadPlans()},[]);
 const syncPending=async()=>{if(!navigator.onLine||!session)return;const ops=await pendingOperations(session.header.id);if(!ops.length){setSync("Cambios guardados");return}setSync("Guardando cambios…");try{const result=await workoutApi.sync(session.header.id,ops);await removeOperations(result.filter(x=>x.result==="APPLIED").map(x=>x.operationId));setSync(result.some(x=>x.result==="CONFLICT")?"Revisar cambios":"Cambios guardados");setSession(await workoutApi.one(session.header.id))}catch{setSync("Pendiente de guardar")}};
 useEffect(()=>{const online=()=>void syncPending();window.addEventListener("online",online);return()=>window.removeEventListener("online",online)},[session?.header.id]);
 const start=async(free=false)=>{setBusy(true);try{const s=await workoutApi.start({workoutPlanDayId:free?undefined:today?.dayId,name:free?"Entrenamiento libre":undefined,clientExternalId:crypto.randomUUID()});setSession(s);setView("active");navigator.vibrate?.(35)}finally{setBusy(false)}};
 return <div className="overlay"><section className="modal workout-hub"><header className="workout-top"><div><small>{view==="plan"?"PLANIFICACIÓN":"EJECUCIÓN REAL"}</small><h2>{view==="history"?"Histórico":view==="plan"?"Plan semanal":session?.header.name||"Entrenamiento"}</h2></div><button onClick={onClose}><X/></button></header>
 {view==="today"&&<div className="today-workout-shell"><TodayScreen today={today} active={session} history={history} busy={busy} onStart={start} onContinue={()=>setView("active")} onHistory={()=>setView("history")} onChanged={async()=>{await load();onWorkoutChanged?.()}}/></div>}
 {view==="plan"&&<WorkoutPlanView plan={plans.find(item=>item.status==="ACTIVE")||plans[0]} exercises={planExercises} onDeleted={loadPlans} onWorkoutChanged={async()=>{await load();onWorkoutChanged?.()}}/>}
 {view==="active"&&session&&<ActiveWorkout session={session} sync={sync} setSession={setSession} onSync={syncPending} onCancel={async()=>{await load();setView("today")}} onFinish={()=>setView("summary")}/>}
 {view==="history"&&<WorkoutHistory rows={history} onOpen={async id=>{setSession(await workoutApi.one(id));setView("summary")}} onDeleted={id=>setHistory(current=>current.filter(row=>row.id!==id))}/>}
 {view==="summary"&&session&&<WorkoutSummaryView session={session} onBack={()=>{void load();setView("history")}}/>}
 <nav className="workout-tabs"><button className={view==="today"?"active":""} onClick={()=>setView("today")}><Dumbbell/>Hoy</button><button className={view==="plan"?"active":""} onClick={()=>setView("plan")}><CalendarDays/>Plan</button><button className={view==="active"?"active":""} disabled={!session} onClick={()=>setView("active")}><Play/>Sesión</button><button className={view==="history"?"active":""} onClick={()=>setView("history")}><History/>Histórico</button><button onClick={onImport}><FileUp/>Importar</button></nav>
 </section></div>
}

function WorkoutPlanView({plan,exercises,onDeleted,onWorkoutChanged}:{plan?:WorkoutPlan;exercises:PlannedWorkoutExercise[];onDeleted:()=>Promise<void>;onWorkoutChanged:()=>Promise<void>}){
 const weeks=[...new Set(exercises.map(item=>item.weekNumber))].sort((a,b)=>a-b),[week,setWeek]=useState(weeks[0]||1);
 const [changeDay,setChangeDay]=useState<{id:string;name:string;date:string}|null>(null);
 const [adjustments,setAdjustments]=useState<WorkoutDayAdjustment[]>([]);
 const loadAdjustments=async()=>{if(!plan)return;try{setAdjustments(await workoutApi.adjustments(plan.id))}catch{setAdjustments([])}};
 useEffect(()=>{void loadAdjustments()},[plan?.id]);
 useEffect(()=>{if(weeks.length&&!weeks.includes(week))setWeek(weeks[0])},[exercises]);
 const rows=exercises.filter(item=>item.weekNumber===week),days=[...new Set(rows.map(item=>item.dayNumber))].sort((a,b)=>a-b);
 const adjustmentFor=(dayId:string,date:string)=>adjustments.find(item=>item.dayId===dayId&&item.originalDate===date);
 if(!plan)return <div className="workout-plan-empty"><CalendarDays/><h3>No hay un plan importado</h3><p>Importa y activa uno para consultar aquí toda tu semana.</p></div>;
 return <div className="workout-plan-view"><section className="workout-plan-hero"><span><small>PLAN ACTIVO · VERSIÓN {plan.version}</small><h3>{plan.name}</h3><p>{plan.validFrom||"Sin fecha inicial"}{plan.validUntil?` — ${plan.validUntil}`:""}</p></span><strong>{days.length}<small>días esta semana</small></strong></section><button className="delete-workout-plan" onClick={async()=>{if(confirm("¿Eliminar este plan de entrenamiento? Las sesiones ya realizadas conservarán su histórico.")){await workoutApi.deletePlan(plan.id);await onDeleted()}}}><Trash2/>Eliminar plan</button>{weeks.length>1&&<div className="workout-week-tabs">{weeks.map(value=><button className={value===week?"active":""} key={value} onClick={()=>setWeek(value)}>Semana {value}</button>)}</div>}<div className="workout-plan-days">{days.map((day,index)=>{const dayRows=rows.filter(item=>item.dayNumber===day),first=dayRows[0],name=first?.sessionName||first?.dayName||"Entrenamiento",date=nextDateForDay(day),adjustment=first?adjustmentFor(first.dayId,date):undefined;return <details key={day} open={index===0}><summary><span><small>DÍA {day}</small><b>{name}</b><em>{first?.dayName}{adjustment?.status==="MOVED"&&adjustment.scheduledDate?` · Movido al ${new Date(`${adjustment.scheduledDate}T12:00:00`).toLocaleDateString("es",{weekday:"long",day:"numeric",month:"short"})}`:adjustment?.status==="SKIPPED"?" · No realizado":""} · {dayRows.length} ejercicios</em></span><span className="plan-day-actions"><button title="Cambiar este día" onClick={event=>{event.preventDefault();event.stopPropagation();setChangeDay({id:first.dayId,name,date})}}><CalendarDays/>Cambiar</button><ChevronDown/></span></summary><div>{dayRows.map(item=><article key={`${day}-${item.order}`}><i>{String(item.order).padStart(2,"0")}</i><span><b>{item.exercise}</b><small>{item.muscleGroup||"Ejercicio"}{item.equipment?` · ${item.equipment}`:""}</small></span><strong>{item.sets}×{item.repsMin}-{item.repsMax}<small>{item.targetRir!=null?`RIR ${item.targetRir}`:item.targetRpe!=null?`RPE ${item.targetRpe}`:""}</small></strong>{item.instructions&&<p>{item.instructions}</p>}</article>)}</div></details>})}</div>{changeDay&&<PlanDayChangeSheet day={changeDay} close={()=>setChangeDay(null)} saved={async()=>{setChangeDay(null);await Promise.all([loadAdjustments(),onWorkoutChanged()])}}/>}</div>
}

function nextDateForDay(day:number){const date=new Date(),delta=(day-(date.getDay()||7)+7)%7;date.setDate(date.getDate()+delta);return localDate(date)}
function localDate(date:Date){const year=date.getFullYear(),month=String(date.getMonth()+1).padStart(2,"0"),day=String(date.getDate()).padStart(2,"0");return `${year}-${month}-${day}`}
function PlanDayChangeSheet({day,close,saved}:{day:{id:string;name:string;date:string};close:()=>void;saved:()=>void}){
 const now=new Date(),monday=new Date(now);monday.setHours(12,0,0,0);monday.setDate(now.getDate()-(now.getDay()||7)+1);const dates=Array.from({length:7},(_,index)=>{const date=new Date(monday);date.setDate(monday.getDate()+index);return date}).filter(date=>date>=new Date(new Date().setHours(0,0,0,0))||localDate(date)===day.date),available=dates.filter(date=>localDate(date)!==day.date),[target,setTarget]=useState(localDate(available[0]||dates[0])),[busy,setBusy]=useState(false);
 return createPortal(<div className="workout-change-overlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="workout-change-dialog" role="dialog" aria-modal="true" aria-labelledby="change-workout-title"><button className="close-sheet" onClick={close} aria-label="Cerrar"><X/></button><small>CAMBIO DE PLAN</small><h2 id="change-workout-title">Cambiar entrenamiento</h2><p><b>{day.name}</b> estaba previsto para {new Date(`${day.date}T12:00:00`).toLocaleDateString("es",{weekday:"long",day:"numeric",month:"long"})}.</p><div className="unavailable-options"><section><CalendarDays/><span><b>Mover a otro día</b><small>Conserva todos sus ejercicios y el seguimiento sabrá cuándo lo hiciste.</small></span><select value={target} onChange={event=>setTarget(event.target.value)}>{dates.map(date=><option key={localDate(date)} value={localDate(date)}>{date.toLocaleDateString("es",{weekday:"long",day:"numeric",month:"short"})}</option>)}</select><button disabled={busy} onClick={async()=>{setBusy(true);try{await workoutApi.rescheduleDay(day.id,day.date,target);saved()}finally{setBusy(false)}}}>Mover entrenamiento</button></section><section className="skip-workout"><X/><span><b>No lo haré</b><small>Quedará como no realizado. Cualquier deporte que hagas se registra aparte desde Inicio.</small></span><button disabled={busy} onClick={async()=>{if(confirm("¿Marcar este entrenamiento como no realizado?")){setBusy(true);try{await workoutApi.skipDay(day.id,day.date,"No disponible");saved()}finally{setBusy(false)}}}}>Marcar como no realizado</button></section></div></section></div>,document.body)
}

function TodayScreen({today,active,history,busy,onStart,onContinue,onHistory,onChanged}:{today:TodayWorkout|null;active:WorkoutSession|null;history:WorkoutSummary[];busy:boolean;onStart:(free?:boolean)=>void;onContinue:()=>void;onHistory:()=>void;onChanged:()=>Promise<void>}){const [unavailable,setUnavailable]=useState(false);
 return <div className="today-workout">{active&&<button className="continue-workout" onClick={onContinue}><span><small>SESIÓN EN CURSO</small><b>{active.header.name}</b></span><Play/></button>}{today?<><div className="today-hero"><span className="day-badge">DÍA {today.dayNumber}</span><p>{today.planName} · v{today.planVersion}</p><h1>{today.sessionName}</h1><div className="today-meta"><span><Clock/>~{today.estimatedMinutes||45} min</span><span><Dumbbell/>{today.exerciseCount} ejercicios</span></div></div><div className="planned-list">{today.exercises.map((e,i)=><div key={e.exerciseId}><i>{String(i+1).padStart(2,"0")}</i><span><b>{e.name}</b><small>{e.muscleGroup||"Ejercicio"} · {e.sets}×{e.repsMin}-{e.repsMax}{e.targetRir!=null?` · RIR ${e.targetRir}`:""}</small></span></div>)}</div><button className="start-workout" disabled={busy||!!active} onClick={()=>onStart()}><Play/>{busy?"Preparando…":"Empezar entrenamiento"}</button><button className="cant-train-today" disabled={!!active} onClick={()=>setUnavailable(true)}>Hoy no puedo entrenar…</button></>:<div className="workout-empty"><Dumbbell/><h3>No hay plan activo para hoy</h3><p>Puedes empezar una sesión libre y seguirá contando en tus métricas.</p></div>}<button className="secondary-action free-session-action" disabled={!!active} onClick={()=>onStart(true)}><Plus/>Sesión libre</button>{history.length>0&&<button className="last-session" onClick={onHistory}><History/><span><small>ÚLTIMA SESIÓN</small><b>{history[0].name}</b></span><strong>{Math.round((history[0].volume||0)).toLocaleString("es")} kg</strong></button>}{unavailable&&today&&<UnavailableWorkoutSheet today={today} close={()=>setUnavailable(false)} saved={async()=>{setUnavailable(false);await onChanged()}}/>}</div>
}

function UnavailableWorkoutSheet({today,close,saved}:{today:TodayWorkout;close:()=>void;saved:()=>Promise<void>}){const dates=Array.from({length:7},(_,index)=>{const date=new Date();date.setDate(date.getDate()+index+1);return date}),[target,setTarget]=useState(dates[0].toISOString().slice(0,10)),[busy,setBusy]=useState(false);return <div className="finish-sheet unavailable-workout"><button className="close-sheet" onClick={close}><X/></button><small>CAMBIO DE PLAN</small><h2>Hoy no puedo entrenar</h2><p><b>{today.sessionName}</b> seguirá vinculada al plan para que el seguimiento refleje lo que realmente ocurrió.</p><div className="unavailable-options"><section><CalendarDays/><span><b>Mover a otro día</b><small>La sesión aparecerá ese día con todos sus ejercicios.</small></span><select value={target} onChange={event=>setTarget(event.target.value)}>{dates.map(date=><option key={date.toISOString()} value={date.toISOString().slice(0,10)}>{date.toLocaleDateString("es",{weekday:"long",day:"numeric",month:"short"})}</option>)}</select><button disabled={busy} onClick={async()=>{setBusy(true);try{await workoutApi.rescheduleToday(target);await saved()}finally{setBusy(false)}}}>Mover entrenamiento</button></section><section className="skip-workout"><X/><span><b>No lo haré esta semana</b><small>Quedará como no realizado. Después puedes registrar pádel u otra actividad desde Inicio sin confundirla con esta sesión.</small></span><button disabled={busy} onClick={async()=>{if(confirm("¿Marcar este entrenamiento como no realizado?")){setBusy(true);try{await workoutApi.skipToday("No disponible");await saved()}finally{setBusy(false)}}}}>Marcar como no realizado</button></section></div></div>}

function ActiveWorkout({session,sync,setSession,onSync,onCancel,onFinish}:{session:WorkoutSession;sync:string;setSession:(s:WorkoutSession)=>void;onSync:()=>void;onCancel:()=>Promise<void>;onFinish:()=>void}){
 const sessionSeconds=(at:number)=>Math.max(0,Math.floor((at-new Date(session.header.startedAt).getTime())/1000)-(session.header.pausedSeconds||0));
 const [now,setNow]=useState(Date.now()),[pausedElapsed,setPausedElapsed]=useState<number|null>(session.header.status==="PAUSED"?sessionSeconds(session.header.pausedAt?new Date(session.header.pausedAt).getTime():Date.now()):null),[expanded,setExpanded]=useState(session.exercises.find(e=>!e.completed)?.id||session.exercises[0]?.id),[restEnd,setRestEnd]=useState<number|null>(null),[finish,setFinish]=useState(false),[activity,setActivity]=useState<WorkoutExercise|null>(null);
 useEffect(()=>{const id=setInterval(()=>{if(session.header.status!=="PAUSED")setNow(Date.now())},1000);return()=>clearInterval(id)},[session.header.status]);
 useEffect(()=>{if(session.header.status==="PAUSED")setPausedElapsed(sessionSeconds(session.header.pausedAt?new Date(session.header.pausedAt).getTime():Date.now()));else setPausedElapsed(null)},[session.header.status,session.header.startedAt,session.header.pausedAt,session.header.pausedSeconds]);
 const elapsed=pausedElapsed??sessionSeconds(now);const completed=session.exercises.filter(e=>e.completed).length;const rest=restEnd?Math.max(0,Math.ceil((restEnd-now)/1000)):0;
 useEffect(()=>{if(restEnd&&rest===0){navigator.vibrate?.([150,80,150]);setRestEnd(null)}},[rest]);
 const refresh=()=>workoutApi.one(session.header.id).then(setSession);
 const addExercise=async()=>{const options=await workoutApi.exercises();const answer=prompt(`Añadir ejercicio:\n${options.slice(0,25).map((x,i)=>`${i+1}. ${x.name}`).join("\n")}\n\nEscribe el número`);const selected=options[Number(answer)-1];if(selected){await workoutApi.addExercise(session.header.id,{exerciseId:selected.id});await refresh()}};
 return <div className="active-workout"><div className={`active-status ${session.header.status==="PAUSED"?"paused":""}`}><div><Clock/><b>{formatTime(elapsed)}</b><small>{session.header.status==="PAUSED"?"SESIÓN EN PAUSA":"DURACIÓN DE LA SESIÓN"}</small></div><div className="progress"><span style={{width:`${session.exercises.length?completed/session.exercises.length*100:0}%`}}/><small>{completed} de {session.exercises.length} ejercicios completados</small></div><button aria-label={session.header.status==="PAUSED"?"Reanudar entrenamiento":"Pausar entrenamiento"} title={session.header.status==="PAUSED"?"Reanudar":"Pausar"} onClick={async()=>setSession(session.header.status==="PAUSED"?await workoutApi.resume(session.header.id):await workoutApi.pause(session.header.id))}>{session.header.status==="PAUSED"?<Play/>:<Pause/>}</button></div><button className={`sync-state ${sync==="Cambios guardados"?"ok":""}`} title="ANURA guarda automáticamente las series y pesos de esta sesión" onClick={onSync}>{navigator.onLine?<Signal/>:<SignalZero/>}{navigator.onLine?sync:"Guardado en este dispositivo"}</button>
 {restEnd&&<div className={`rest-timer ${rest<=5?"ending":""}`}><span><small>DESCANSO</small><b>{formatTime(rest)}</b></span><button onClick={()=>setRestEnd(restEnd-15000)}>−15</button><button onClick={()=>setRestEnd(restEnd+15000)}>+15</button><button onClick={()=>setRestEnd(null)}><X/></button></div>}
 {session.exercises.map(ex=><ExerciseCard key={ex.id} sessionId={session.header.id} exercise={ex} open={expanded===ex.id} onToggle={()=>setExpanded(expanded===ex.id?"":ex.id)} refresh={refresh} startRest={seconds=>setRestEnd(Date.now()+seconds*1000)} onActivity={()=>setActivity(ex)}/>)}
 <div className="workout-session-actions"><button className="secondary-action" onClick={addExercise}><Plus/>Añadir ejercicio</button><button className="cancel-workout" onClick={async()=>{if(confirm("¿Cancelar este entrenamiento en curso? Se guardará como cancelado y dejará de aparecer como sesión activa.")){await workoutApi.abandon(session.header.id,"Cancelado por el usuario");await onCancel()}}}><X/>Cancelar sesión</button></div><button className="finish-workout" onClick={()=>setFinish(true)}><Check/>Finalizar entrenamiento</button>{activity&&<ActivitySheet session={session} exercise={activity} close={()=>setActivity(null)} saved={async()=>{setActivity(null);await refresh()}}/>}{finish&&<FinishSheet session={session} close={()=>setFinish(false)} done={async body=>{setSession(await workoutApi.complete(session.header.id,body));setFinish(false);onFinish()}}/>}</div>
}

function ExerciseCard({sessionId,exercise,open,onToggle,refresh,startRest,onActivity}:{sessionId:string;exercise:WorkoutExercise;open:boolean;onToggle:()=>void;refresh:()=>Promise<unknown>;startRest:(s:number)=>void;onActivity:()=>void}) {
 const template=exercise.sets.at(-1);
 const add=async(copy?:WorkoutSet)=>{const body={setType:copy?.setType||"WORKING",weight:copy?.weight,repetitions:copy?.repetitions,rir:copy?.rir??exercise.targetRir,restSeconds:exercise.targetRestSeconds,completed:false,clientExternalId:crypto.randomUUID()};try{await workoutApi.addSet(sessionId,exercise.id,body);await refresh()}catch{await queueOperation({operationId:crypto.randomUUID(),clientEntityId:body.clientExternalId,operationType:"ADD_SET",entityType:"SET",occurredAt:new Date().toISOString(),payload:{exercisePerformanceId:exercise.id,...body},sessionId});await refresh().catch(()=>undefined)}};
 const copyLast=async()=>{const last=await workoutApi.lastPerformance(exercise.exerciseId);if(last)await add({...last,id:"",setNumber:0,setType:"WORKING",completed:false,clientExternalId:crypto.randomUUID()})};
 const substitute=async()=>{const options=await workoutApi.exercises();const answer=prompt(`Sustituir por:\n${options.slice(0,20).map((x,i)=>`${i+1}. ${x.name}`).join("\n")}\n\nEscribe el número`);const selected=options[Number(answer)-1];if(selected){await workoutApi.substitute(sessionId,exercise.id,{replacementExerciseId:selected.id,reason:"PREFERENCE",notes:"Sustitución desde entrenamiento"});await refresh()}};
 return <article className={`live-exercise ${open?"open":""}`}><button className="exercise-head" onClick={onToggle}><span className={exercise.completed?"done":""}>{exercise.completed?<Check/>:exercise.order}</span><div><small>{exercise.muscleGroup||"EJERCICIO"}</small><h3>{exercise.name}</h3><p>{exercise.targetSets||"–"} series · {exercise.targetRepsMin||"–"}-{exercise.targetRepsMax||"–"} reps {exercise.targetRir!=null?`· RIR ${exercise.targetRir}`:""}</p></div><ChevronDown/></button><div className="exercise-body">{exercise.instructions&&<p className="exercise-tip">{exercise.instructions}</p>}<div className="set-labels"><span>SET</span><span>KG</span><span>REPS</span><span>RIR</span><span></span></div>{exercise.sets.map(s=><SetRow key={s.id} session={sessionId} exercise={exercise.id} value={s} refresh={refresh} rest={()=>startRest(s.restSeconds||exercise.targetRestSeconds||90)}/>)}<div className="set-actions"><button onClick={()=>add()}><Plus/>Añadir</button><button disabled={!template} onClick={()=>add(template)}><Copy/>Duplicar</button><button onClick={copyLast}><History/>Última</button></div><div className="exercise-actions"><button onClick={substitute}>Otro ejercicio</button><button disabled={exercise.completed} onClick={onActivity}><Activity/>Deporte/cardio</button><button onClick={async()=>{const intensity=Number(prompt("Intensidad de molestia (0-10)","0"));if(Number.isFinite(intensity)){await workoutApi.pain(sessionId,exercise.id,{intensity,area:"Sin especificar"});await refresh()}}}>Molestia</button><button disabled={exercise.completed} onClick={async()=>{await workoutApi.finishExercise(sessionId,exercise.id);await refresh()}}><Check/>Terminar</button></div>{exercise.painReported&&<p className="pain-note">Revisa la técnica o el ejercicio y consulta con un profesional si el dolor persiste o es intenso.</p>}</div></article>
}

function SetRow({session,exercise,value,refresh,rest}:{session:string;exercise:string;value:WorkoutSet;refresh:()=>Promise<unknown>;rest:()=>void}) {
 const [draft,setDraft]=useState(value);
 const save=async(next:WorkoutSet)=>{setDraft(next);try{await workoutApi.updateSet(session,exercise,value.id,{...next,clientExternalId:value.clientExternalId});await refresh()}catch{await queueOperation({operationId:crypto.randomUUID(),clientEntityId:value.clientExternalId,operationType:"UPDATE_SET",entityType:"SET",occurredAt:new Date().toISOString(),payload:{exercisePerformanceId:exercise,setId:value.id,...next},sessionId:session})}if(next.completed&&!value.completed){navigator.vibrate?.(25);rest()}};
 const remove=async()=>{try{await workoutApi.deleteSet(session,exercise,value.id);await refresh()}catch{await queueOperation({operationId:crypto.randomUUID(),clientEntityId:value.clientExternalId,operationType:"DELETE_SET",entityType:"SET",occurredAt:new Date().toISOString(),payload:{exercisePerformanceId:exercise,setId:value.id},sessionId:session})}};
 return <div className={`set-row ${draft.completed?"completed":""}`}><b>{value.setNumber}</b><input aria-label="Peso" type="number" step="0.1" inputMode="decimal" value={draft.weight??""} onChange={e=>setDraft({...draft,weight:e.target.value===""?undefined:Number(e.target.value)})} onBlur={()=>void save(draft)}/><input aria-label="Repeticiones" inputMode="numeric" value={draft.repetitions??""} onChange={e=>setDraft({...draft,repetitions:e.target.value===""?undefined:Number(e.target.value)})} onBlur={()=>void save(draft)}/><input aria-label="RIR" inputMode="decimal" value={draft.rir??""} onChange={e=>setDraft({...draft,rir:e.target.value===""?undefined:Number(e.target.value)})} onBlur={()=>void save(draft)}/><button aria-label="Completar serie" onClick={()=>void save({...draft,completed:!draft.completed})}><Check/></button><button className="set-delete" onClick={remove}><Trash2/></button></div>
}

const sportOptions=[{name:"Pádel",met:7},{name:"Tenis",met:7.3},{name:"Fútbol",met:8},{name:"Correr suave",met:7},{name:"Correr intenso",met:10},{name:"Bicicleta",met:7.5},{name:"Natación",met:8},{name:"Elíptica",met:5.5},{name:"Caminar rápido",met:4.5},{name:"Otro deporte",met:6}];
function ActivitySheet({session,exercise,close,saved}:{session:WorkoutSession;exercise:WorkoutExercise;close:()=>void;saved:()=>Promise<void>}){const [sport,setSport]=useState(sportOptions[0]),[minutes,setMinutes]=useState(60),[weight,setWeight]=useState(70),[calories,setCalories]=useState<number|null>(null),[busy,setBusy]=useState(false);useEffect(()=>{void bodyProgressApi.latest().then(value=>{if(value?.weight)setWeight(Number(value.weight))}).catch(()=>undefined)},[]);const estimate=Math.round(sport.met*3.5*weight/200*minutes),value=calories??estimate;return <div className="finish-sheet activity-sheet"><button className="close-sheet" onClick={close}><X/></button><small>ACTIVIDAD REAL</small><h2>Sustituir {exercise.name}</h2><p>Esta actividad sustituirá únicamente este ejercicio del plan y añadirá sus calorías al día de hoy.</p><form onSubmit={async event=>{event.preventDefault();setBusy(true);try{await api.create({type:"WORKOUT",title:sport.name,entryDate:new Date().toISOString().slice(0,10),value,unit:"kcal",details:`${minutes} min · estimación MET ${sport.met}`,notes:`Actividad realizada en lugar de ${exercise.name}. Peso usado: ${weight} kg.`,completed:true});await workoutApi.finishExercise(session.header.id,exercise.id);await saved()}finally{setBusy(false)}}}><div className="activity-grid"><label>Actividad<select value={sport.name} onChange={event=>{setSport(sportOptions.find(item=>item.name===event.target.value)||sportOptions[0]);setCalories(null)}}>{sportOptions.map(item=><option key={item.name}>{item.name}</option>)}</select></label><label>Duración (min)<input type="number" min="5" max="600" value={minutes} onChange={event=>{setMinutes(Number(event.target.value));setCalories(null)}}/></label><label>Peso usado (kg)<input type="number" min="20" max="500" step="0.1" value={weight} onChange={event=>{setWeight(Number(event.target.value));setCalories(null)}}/></label><label>Calorías<input type="number" min="0" value={value} onChange={event=>setCalories(Number(event.target.value))}/></label></div><p className="activity-estimate"><b>≈ {estimate} kcal estimadas</b><span>Estimación basada en MET, duración y tu último peso. Puedes corregirla con el dato del reloj.</span></p><button className="start-workout" disabled={busy}>{busy?"Guardando…":"Guardar actividad y sustituir"}</button></form></div>}

function FinishSheet({session,close,done}:{session:WorkoutSession;close:()=>void;done:(x:object)=>void}){const incomplete=session.exercises.filter(e=>!e.completed).length;return <div className="finish-sheet"><button className="close-sheet" onClick={close}><X/></button><small>RESUMEN FINAL</small><h2>¿Cómo ha ido?</h2><p className="rating-help">Valora solo lo que aplique. El resto no se guardará.</p>{incomplete>0&&<p className="pending-warning">Quedan {incomplete} ejercicios incompletos. Se guardará como sesión parcial.</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const number=(name:string)=>f.has(name)?Number(f.get(name)):undefined;done({globalRpe:number("rpe"),energyLevel:number("energy"),pumpLevel:number("pump"),painLevel:number("pain"),difficultyLevel:number("difficulty"),notes:String(f.get("notes")),adherenceReason:String(f.get("reason")||"")})}}><div className="rating-grid"><OptionalRating name="rpe" label="Esfuerzo (RPE)" initial={7} min={1}/><OptionalRating name="energy" label="Energía" initial={7}/><OptionalRating name="pump" label="Congestión" initial={6}/><OptionalRating name="pain" label="Dolor" initial={0}/><OptionalRating name="difficulty" label="Dificultad" initial={7}/></div>{incomplete>0&&<label className="finish-reason">Motivo<select name="reason" required><option value="">Selecciona</option><option value="TIME">Falta de tiempo</option><option value="FATIGUE">Fatiga</option><option value="PAIN">Dolor o molestia</option><option value="EQUIPMENT">Equipo no disponible</option><option value="OTHER">Otro</option></select></label>}<textarea name="notes" placeholder="Sensaciones y notas…"/><button className="start-workout">Guardar y finalizar</button></form></div>}
function OptionalRating({name,label,initial,min=0}:{name:string;label:string;initial:number;min?:number}){const [enabled,setEnabled]=useState(false),[value,setValue]=useState(initial);return <label className={enabled?"rating-enabled":"rating-disabled"}><span><b>{label}</b><button type="button" onClick={()=>setEnabled(!enabled)}>{enabled?"Quitar":"Valorar"}</button></span>{enabled?<><input name={name} type="range" min={min} max="10" value={value} onChange={e=>setValue(Number(e.target.value))}/><strong>{value}/10</strong></>:<em>No aplica</em>}</label>}
function WorkoutHistory({rows,onOpen,onDeleted}:{rows:WorkoutSummary[];onOpen:(id:string)=>void;onDeleted:(id:string)=>void}){return <div className="workout-history">{rows.length?rows.map(r=><article key={r.id}><button className="history-open" onClick={()=>onOpen(r.id)}><span className="history-date">{new Date(r.date+"T12:00").toLocaleDateString("es",{day:"2-digit",month:"short"})}</span><span><b>{r.name}</b><small>{r.exercises} ejercicios · {r.sets} series</small></span><strong>{Math.round(r.volume||0).toLocaleString("es")}<small>kg vol.</small></strong></button><button className="history-delete" title="Eliminar sesión" aria-label={`Eliminar ${r.name}`} onClick={async()=>{if(confirm("¿Eliminar esta sesión del histórico? También dejará de contar en tu evolución y se eliminarán sus récords. Esta acción no se puede deshacer.")){await workoutApi.deleteSession(r.id);onDeleted(r.id)}}}><Trash2/></button></article>):<div className="workout-empty"><History/><h3>Tu histórico empieza aquí</h3></div>}</div>}
function WorkoutSummaryView({session,onBack}:{session:WorkoutSession;onBack:()=>void}){const m=session.metrics,[editing,setEditing]=useState(false),[current,setCurrent]=useState(session);const refresh=()=>workoutApi.one(session.header.id).then(setCurrent);return <div className="session-summary"><div className="summary-hero"><Check/><small>ENTRENAMIENTO COMPLETADO</small><h1>{session.header.name}</h1></div><div className="summary-grid"><div><small>VOLUMEN</small><b>{Math.round(m.volume||0).toLocaleString("es")} kg</b></div><div><small>SERIES</small><b>{m.sets}</b></div><div><small>REPETICIONES</small><b>{m.repetitions}</b></div><div><small>RÉCORDS</small><b>{m.personalRecords}</b></div></div>{m.maxPain>=5&&<p className="pain-note">Revisa la técnica o el ejercicio y consulta con un profesional si el dolor persiste o es intenso.</p>}<button className="secondary-action" onClick={()=>setEditing(value=>!value)}>{editing?"Ocultar métricas":"Editar métricas"}</button>{editing&&<div className="summary-edit-exercises">{current.exercises.map(ex=><ExerciseCard key={ex.id} sessionId={current.header.id} exercise={ex} open={true} onToggle={()=>undefined} refresh={refresh} startRest={()=>undefined} onActivity={()=>undefined}/>)}</div>}<button className="secondary-action" onClick={onBack}><RotateCcw/>Ver histórico</button></div>}
const formatTime=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
