import { useEffect,useMemo,useState } from "react";
import { Check,ChevronDown,Clock,Copy,Dumbbell,FileUp,History,Pause,Play,Plus,RotateCcw,Signal,SignalZero,Trash2,X } from "lucide-react";
import { workoutApi, type TodayWorkout,type WorkoutExercise,type WorkoutSession,type WorkoutSet,type WorkoutSummary } from "./api";
import { pendingOperations,queueOperation,removeOperations,type OfflineOperation } from "./workoutOffline";

export function WorkoutHub({onClose,onImport}:{onClose:()=>void;onImport:()=>void}){
 const [today,setToday]=useState<TodayWorkout|null>(null),[session,setSession]=useState<WorkoutSession|null>(null),[history,setHistory]=useState<WorkoutSummary[]>([]),[view,setView]=useState<"today"|"active"|"history"|"summary">("today"),[busy,setBusy]=useState(false),[sync,setSync]=useState("Cambios guardados");
 const load=async()=>{const [t,a,h]=await Promise.all([workoutApi.today().catch(()=>null),workoutApi.active().catch(()=>null),workoutApi.history().catch(()=>[])]);setToday(t);setSession(a);setHistory(h);if(a)setView("active")};
 useEffect(()=>{void load()},[]);
 const syncPending=async()=>{if(!navigator.onLine||!session)return;const ops=await pendingOperations(session.header.id);if(!ops.length){setSync("Cambios guardados");return}setSync("Guardando cambios…");try{const result=await workoutApi.sync(session.header.id,ops);await removeOperations(result.filter(x=>x.result==="APPLIED").map(x=>x.operationId));setSync(result.some(x=>x.result==="CONFLICT")?"Revisar cambios":"Cambios guardados");setSession(await workoutApi.one(session.header.id))}catch{setSync("Pendiente de guardar")}};
 useEffect(()=>{const online=()=>void syncPending();window.addEventListener("online",online);return()=>window.removeEventListener("online",online)},[session?.header.id]);
 const start=async(free=false)=>{setBusy(true);try{const s=await workoutApi.start({workoutPlanDayId:free?undefined:today?.dayId,name:free?"Entrenamiento libre":undefined,clientExternalId:crypto.randomUUID()});setSession(s);setView("active");navigator.vibrate?.(35)}finally{setBusy(false)}};
 return <div className="overlay"><section className="modal workout-hub"><header className="workout-top"><div><small>EJECUCIÓN REAL</small><h2>{view==="history"?"Histórico":session?.header.name||"Entrenamiento"}</h2></div><button onClick={onClose}><X/></button></header>
 {view==="today"&&<TodayScreen today={today} active={session} history={history} busy={busy} onStart={start} onContinue={()=>setView("active")} onHistory={()=>setView("history")}/>} 
 {view==="active"&&session&&<ActiveWorkout session={session} sync={sync} setSession={setSession} onSync={syncPending} onFinish={()=>setView("summary")}/>} 
 {view==="history"&&<WorkoutHistory rows={history} onOpen={async id=>{setSession(await workoutApi.one(id));setView("summary")}}/>}
 {view==="summary"&&session&&<WorkoutSummaryView session={session} onBack={()=>{void load();setView("history")}}/>}
 <nav className="workout-tabs"><button className={view==="today"?"active":""} onClick={()=>setView("today")}><Dumbbell/>Hoy</button><button className={view==="active"?"active":""} disabled={!session} onClick={()=>setView("active")}><Play/>Sesión</button><button className={view==="history"?"active":""} onClick={()=>setView("history")}><History/>Histórico</button><button onClick={onImport}><FileUp/>Importar plan</button></nav>
 </section></div>
}

function TodayScreen({today,active,history,busy,onStart,onContinue,onHistory}:{today:TodayWorkout|null;active:WorkoutSession|null;history:WorkoutSummary[];busy:boolean;onStart:(free?:boolean)=>void;onContinue:()=>void;onHistory:()=>void}){
 return <div className="today-workout">{active&&<button className="continue-workout" onClick={onContinue}><span><small>SESIÓN EN CURSO</small><b>{active.header.name}</b></span><Play/></button>}{today?<><div className="today-hero"><span className="day-badge">DÍA {today.dayNumber}</span><p>{today.planName} · v{today.planVersion}</p><h1>{today.sessionName}</h1><div className="today-meta"><span><Clock/>~{today.estimatedMinutes||45} min</span><span><Dumbbell/>{today.exerciseCount} ejercicios</span></div></div><div className="planned-list">{today.exercises.map((e,i)=><div key={e.exerciseId}><i>{String(i+1).padStart(2,"0")}</i><span><b>{e.name}</b><small>{e.muscleGroup||"Ejercicio"} · {e.sets}×{e.repsMin}-{e.repsMax}{e.targetRir!=null?` · RIR ${e.targetRir}`:""}</small></span></div>)}</div><button className="start-workout" disabled={busy||!!active} onClick={()=>onStart()}><Play/>{busy?"Preparando…":"Empezar entrenamiento"}</button></>:<div className="workout-empty"><Dumbbell/><h3>No hay plan activo para hoy</h3><p>Puedes empezar una sesión libre y seguirá contando en tus métricas.</p></div>}<button className="secondary-action" disabled={!!active} onClick={()=>onStart(true)}><Plus/>Sesión libre</button>{history.length>0&&<button className="last-session" onClick={onHistory}><History/><span><small>ÚLTIMA SESIÓN</small><b>{history[0].name}</b></span><strong>{Math.round((history[0].volume||0)).toLocaleString("es")} kg</strong></button>}</div>
}

function ActiveWorkout({session,sync,setSession,onSync,onFinish}:{session:WorkoutSession;sync:string;setSession:(s:WorkoutSession)=>void;onSync:()=>void;onFinish:()=>void}){
 const sessionSeconds=(at:number)=>Math.max(0,Math.floor((at-new Date(session.header.startedAt).getTime())/1000)-(session.header.pausedSeconds||0));
 const [now,setNow]=useState(Date.now()),[pausedElapsed,setPausedElapsed]=useState<number|null>(session.header.status==="PAUSED"?sessionSeconds(session.header.pausedAt?new Date(session.header.pausedAt).getTime():Date.now()):null),[expanded,setExpanded]=useState(session.exercises.find(e=>!e.completed)?.id||session.exercises[0]?.id),[restEnd,setRestEnd]=useState<number|null>(null),[finish,setFinish]=useState(false);
 useEffect(()=>{const id=setInterval(()=>{if(session.header.status!=="PAUSED")setNow(Date.now())},1000);return()=>clearInterval(id)},[session.header.status]);
 useEffect(()=>{if(session.header.status==="PAUSED")setPausedElapsed(sessionSeconds(session.header.pausedAt?new Date(session.header.pausedAt).getTime():Date.now()));else setPausedElapsed(null)},[session.header.status,session.header.startedAt,session.header.pausedAt,session.header.pausedSeconds]);
 const elapsed=pausedElapsed??sessionSeconds(now);const completed=session.exercises.filter(e=>e.completed).length;const rest=restEnd?Math.max(0,Math.ceil((restEnd-now)/1000)):0;
 useEffect(()=>{if(restEnd&&rest===0){navigator.vibrate?.([150,80,150]);setRestEnd(null)}},[rest]);
 const refresh=()=>workoutApi.one(session.header.id).then(setSession);
 const addExercise=async()=>{const options=await workoutApi.exercises();const answer=prompt(`Añadir ejercicio:\n${options.slice(0,25).map((x,i)=>`${i+1}. ${x.name}`).join("\n")}\n\nEscribe el número`);const selected=options[Number(answer)-1];if(selected){await workoutApi.addExercise(session.header.id,{exerciseId:selected.id});await refresh()}};
 return <div className="active-workout"><div className={`active-status ${session.header.status==="PAUSED"?"paused":""}`}><div><Clock/><b>{formatTime(elapsed)}</b><small>{session.header.status==="PAUSED"?"SESIÓN EN PAUSA":"DURACIÓN DE LA SESIÓN"}</small></div><div className="progress"><span style={{width:`${session.exercises.length?completed/session.exercises.length*100:0}%`}}/><small>{completed} de {session.exercises.length} ejercicios completados</small></div><button aria-label={session.header.status==="PAUSED"?"Reanudar entrenamiento":"Pausar entrenamiento"} title={session.header.status==="PAUSED"?"Reanudar":"Pausar"} onClick={async()=>setSession(session.header.status==="PAUSED"?await workoutApi.resume(session.header.id):await workoutApi.pause(session.header.id))}>{session.header.status==="PAUSED"?<Play/>:<Pause/>}</button></div><button className={`sync-state ${sync==="Cambios guardados"?"ok":""}`} title="ANURA guarda automáticamente las series y pesos de esta sesión" onClick={onSync}>{navigator.onLine?<Signal/>:<SignalZero/>}{navigator.onLine?sync:"Guardado en este dispositivo"}</button>
 {restEnd&&<div className={`rest-timer ${rest<=5?"ending":""}`}><span><small>DESCANSO</small><b>{formatTime(rest)}</b></span><button onClick={()=>setRestEnd(restEnd-15000)}>−15</button><button onClick={()=>setRestEnd(restEnd+15000)}>+15</button><button onClick={()=>setRestEnd(null)}><X/></button></div>}
 {session.exercises.map(ex=><ExerciseCard key={ex.id} sessionId={session.header.id} exercise={ex} open={expanded===ex.id} onToggle={()=>setExpanded(expanded===ex.id?"":ex.id)} refresh={refresh} startRest={seconds=>setRestEnd(Date.now()+seconds*1000)}/>)}
 <button className="secondary-action" onClick={addExercise}><Plus/>Añadir ejercicio</button><button className="finish-workout" onClick={()=>setFinish(true)}><Check/>Finalizar entrenamiento</button>{finish&&<FinishSheet session={session} close={()=>setFinish(false)} done={async body=>{setSession(await workoutApi.complete(session.header.id,body));setFinish(false);onFinish()}}/>}</div>
}

function ExerciseCard({sessionId,exercise,open,onToggle,refresh,startRest}:{sessionId:string;exercise:WorkoutExercise;open:boolean;onToggle:()=>void;refresh:()=>Promise<unknown>;startRest:(s:number)=>void}) {
 const template=exercise.sets.at(-1);
 const add=async(copy?:WorkoutSet)=>{const body={setType:copy?.setType||"WORKING",weight:copy?.weight,repetitions:copy?.repetitions,rir:copy?.rir??exercise.targetRir,restSeconds:exercise.targetRestSeconds,completed:false,clientExternalId:crypto.randomUUID()};try{await workoutApi.addSet(sessionId,exercise.id,body);await refresh()}catch{await queueOperation({operationId:crypto.randomUUID(),clientEntityId:body.clientExternalId,operationType:"ADD_SET",entityType:"SET",occurredAt:new Date().toISOString(),payload:{exercisePerformanceId:exercise.id,...body},sessionId});await refresh().catch(()=>undefined)}};
 const copyLast=async()=>{const last=await workoutApi.lastPerformance(exercise.exerciseId);if(last)await add({...last,id:"",setNumber:0,setType:"WORKING",completed:false,clientExternalId:crypto.randomUUID()})};
 const substitute=async()=>{const options=await workoutApi.exercises();const answer=prompt(`Sustituir por:\n${options.slice(0,20).map((x,i)=>`${i+1}. ${x.name}`).join("\n")}\n\nEscribe el número`);const selected=options[Number(answer)-1];if(selected){await workoutApi.substitute(sessionId,exercise.id,{replacementExerciseId:selected.id,reason:"PREFERENCE",notes:"Sustitución desde entrenamiento"});await refresh()}};
 return <article className={`live-exercise ${open?"open":""}`}><button className="exercise-head" onClick={onToggle}><span className={exercise.completed?"done":""}>{exercise.completed?<Check/>:exercise.order}</span><div><small>{exercise.muscleGroup||"EJERCICIO"}</small><h3>{exercise.name}</h3><p>{exercise.targetSets||"–"} series · {exercise.targetRepsMin||"–"}-{exercise.targetRepsMax||"–"} reps {exercise.targetRir!=null?`· RIR ${exercise.targetRir}`:""}</p></div><ChevronDown/></button><div className="exercise-body">{exercise.instructions&&<p className="exercise-tip">{exercise.instructions}</p>}<div className="set-labels"><span>SET</span><span>KG</span><span>REPS</span><span>RIR</span><span></span></div>{exercise.sets.map(s=><SetRow key={s.id} session={sessionId} exercise={exercise.id} value={s} refresh={refresh} rest={()=>startRest(s.restSeconds||exercise.targetRestSeconds||90)}/>)}<div className="set-actions"><button onClick={()=>add()}><Plus/>Añadir</button><button disabled={!template} onClick={()=>add(template)}><Copy/>Duplicar</button><button onClick={copyLast}><History/>Última</button></div><div className="exercise-actions"><button onClick={substitute}>Sustituir</button><button onClick={async()=>{const intensity=Number(prompt("Intensidad de molestia (0-10)","0"));if(Number.isFinite(intensity)){await workoutApi.pain(sessionId,exercise.id,{intensity,area:"Sin especificar"});await refresh()}}}>Molestia</button><button disabled={exercise.completed} onClick={async()=>{await workoutApi.finishExercise(sessionId,exercise.id);await refresh()}}><Check/>Terminar</button></div>{exercise.painReported&&<p className="pain-note">Revisa la técnica o el ejercicio y consulta con un profesional si el dolor persiste o es intenso.</p>}</div></article>
}

function SetRow({session,exercise,value,refresh,rest}:{session:string;exercise:string;value:WorkoutSet;refresh:()=>Promise<unknown>;rest:()=>void}) {
 const [draft,setDraft]=useState(value);
 const save=async(next:WorkoutSet)=>{setDraft(next);try{await workoutApi.updateSet(session,exercise,value.id,{...next,clientExternalId:value.clientExternalId});await refresh()}catch{await queueOperation({operationId:crypto.randomUUID(),clientEntityId:value.clientExternalId,operationType:"UPDATE_SET",entityType:"SET",occurredAt:new Date().toISOString(),payload:{exercisePerformanceId:exercise,setId:value.id,...next},sessionId:session})}if(next.completed&&!value.completed){navigator.vibrate?.(25);rest()}};
 const remove=async()=>{try{await workoutApi.deleteSet(session,exercise,value.id);await refresh()}catch{await queueOperation({operationId:crypto.randomUUID(),clientEntityId:value.clientExternalId,operationType:"DELETE_SET",entityType:"SET",occurredAt:new Date().toISOString(),payload:{exercisePerformanceId:exercise,setId:value.id},sessionId:session})}};
 return <div className={`set-row ${draft.completed?"completed":""}`}><b>{value.setNumber}</b><input aria-label="Peso" inputMode="decimal" value={draft.weight??""} onChange={e=>setDraft({...draft,weight:e.target.value===""?undefined:Number(e.target.value)})} onBlur={()=>void save(draft)}/><input aria-label="Repeticiones" inputMode="numeric" value={draft.repetitions??""} onChange={e=>setDraft({...draft,repetitions:e.target.value===""?undefined:Number(e.target.value)})} onBlur={()=>void save(draft)}/><input aria-label="RIR" inputMode="decimal" value={draft.rir??""} onChange={e=>setDraft({...draft,rir:e.target.value===""?undefined:Number(e.target.value)})} onBlur={()=>void save(draft)}/><button aria-label="Completar serie" onClick={()=>void save({...draft,completed:!draft.completed})}><Check/></button><button className="set-delete" onClick={remove}><Trash2/></button></div>
}

function FinishSheet({session,close,done}:{session:WorkoutSession;close:()=>void;done:(x:object)=>void}){const incomplete=session.exercises.reduce((n,e)=>n+e.sets.filter(s=>!s.completed).length,0);return <div className="finish-sheet"><button className="close-sheet" onClick={close}><X/></button><small>RESUMEN FINAL</small><h2>¿Cómo ha ido?</h2><p className="rating-help">Valora solo lo que aplique. El resto no se guardará.</p>{incomplete>0&&<p className="pending-warning">Quedan {incomplete} series incompletas. Puedes finalizar igualmente.</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const number=(name:string)=>f.has(name)?Number(f.get(name)):undefined;done({globalRpe:number("rpe"),energyLevel:number("energy"),pumpLevel:number("pump"),painLevel:number("pain"),difficultyLevel:number("difficulty"),notes:String(f.get("notes"))})}}><div className="rating-grid"><OptionalRating name="rpe" label="Esfuerzo (RPE)" initial={7} min={1}/><OptionalRating name="energy" label="Energía" initial={7}/><OptionalRating name="pump" label="Congestión" initial={6}/><OptionalRating name="pain" label="Dolor" initial={0}/><OptionalRating name="difficulty" label="Dificultad" initial={7}/></div><textarea name="notes" placeholder="Sensaciones y notas…"/><button className="start-workout">Guardar y finalizar</button></form></div>}
function OptionalRating({name,label,initial,min=0}:{name:string;label:string;initial:number;min?:number}){const [enabled,setEnabled]=useState(false),[value,setValue]=useState(initial);return <label className={enabled?"rating-enabled":"rating-disabled"}><span><b>{label}</b><button type="button" onClick={()=>setEnabled(!enabled)}>{enabled?"Quitar":"Valorar"}</button></span>{enabled?<><input name={name} type="range" min={min} max="10" value={value} onChange={e=>setValue(Number(e.target.value))}/><strong>{value}/10</strong></>:<em>No aplica</em>}</label>}
function WorkoutHistory({rows,onOpen}:{rows:WorkoutSummary[];onOpen:(id:string)=>void}){return <div className="workout-history">{rows.length?rows.map(r=><button key={r.id} onClick={()=>onOpen(r.id)}><span className="history-date">{new Date(r.date+"T12:00").toLocaleDateString("es",{day:"2-digit",month:"short"})}</span><span><b>{r.name}</b><small>{r.exercises} ejercicios · {r.sets} series</small></span><strong>{Math.round(r.volume||0).toLocaleString("es")}<small>kg vol.</small></strong></button>):<div className="workout-empty"><History/><h3>Tu histórico empieza aquí</h3></div>}</div>}
function WorkoutSummaryView({session,onBack}:{session:WorkoutSession;onBack:()=>void}){const m=session.metrics;return <div className="session-summary"><div className="summary-hero"><Check/><small>ENTRENAMIENTO COMPLETADO</small><h1>{session.header.name}</h1></div><div className="summary-grid"><div><small>VOLUMEN</small><b>{Math.round(m.volume||0).toLocaleString("es")} kg</b></div><div><small>SERIES</small><b>{m.sets}</b></div><div><small>REPETICIONES</small><b>{m.repetitions}</b></div><div><small>RÉCORDS</small><b>{m.personalRecords}</b></div></div>{m.maxPain>=5&&<p className="pain-note">Revisa la técnica o el ejercicio y consulta con un profesional si el dolor persiste o es intenso.</p>}<button className="secondary-action" onClick={onBack}><RotateCcw/>Ver histórico</button></div>}
const formatTime=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
