package app.anura.sleep;

import app.anura.config.CurrentUser;
import java.time.*;import java.util.*;import org.springframework.http.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/sleep")
public class SleepController {
 private final JdbcTemplate db; private static final int GOAL=480;
 SleepController(JdbcTemplate db){this.db=db;}
 @GetMapping("/today") Map<String,Object> today(){return db.queryForList("SELECT * FROM sleep_session WHERE user_id=? AND sleep_date=CURRENT_DATE",CurrentUser.id()).stream().findFirst().orElse(null);}
 @GetMapping List<Map<String,Object>> list(@RequestParam LocalDate from,@RequestParam LocalDate to){if(from==null||to==null||to.isBefore(from)||from.plusDays(366).isBefore(to))throw bad("INVALID_RANGE","El intervalo máximo es de 366 días");return db.queryForList("SELECT * FROM sleep_session WHERE user_id=? AND sleep_date BETWEEN ? AND ? ORDER BY sleep_date",CurrentUser.id(),from,to);}
 @PostMapping Map<String,Object> save(@RequestBody Input r){validate(r);UUID user=CurrentUser.id();UUID id=UUID.randomUUID();db.update("INSERT INTO sleep_session(id,user_id,sleep_date,total_sleep_minutes,quality_score,morning_energy,bed_time,wake_time,notes) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,sleep_date) DO UPDATE SET total_sleep_minutes=EXCLUDED.total_sleep_minutes,quality_score=EXCLUDED.quality_score,morning_energy=EXCLUDED.morning_energy,bed_time=EXCLUDED.bed_time,wake_time=EXCLUDED.wake_time,notes=EXCLUDED.notes,updated_at=CURRENT_TIMESTAMP",id,user,r.sleepDate(),r.totalSleepMinutes(),r.qualityScore(),r.morningEnergy(),r.bedTime(),r.wakeTime(),r.notes());return db.queryForMap("SELECT * FROM sleep_session WHERE user_id=? AND sleep_date=?",user,r.sleepDate());}
 @PutMapping("/{id}") Map<String,Object> update(@PathVariable UUID id,@RequestBody Input r){owned(id);validate(r);db.update("UPDATE sleep_session SET sleep_date=?,total_sleep_minutes=?,quality_score=?,morning_energy=?,bed_time=?,wake_time=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?",r.sleepDate(),r.totalSleepMinutes(),r.qualityScore(),r.morningEnergy(),r.bedTime(),r.wakeTime(),r.notes(),id,CurrentUser.id());return owned(id);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable UUID id){owned(id);db.update("DELETE FROM sleep_session WHERE id=? AND user_id=?",id,CurrentUser.id());}
 @GetMapping("/summary") Map<String,Object> summary(@RequestParam(defaultValue="30") int days){int n=Math.min(Math.max(days,1),366);List<Map<String,Object>> rows=db.queryForList("SELECT sleep_date,total_sleep_minutes,quality_score,morning_energy FROM sleep_session WHERE user_id=? AND sleep_date>=CURRENT_DATE-? ORDER BY sleep_date",CurrentUser.id(),n-1);double avg=rows.stream().mapToInt(x->((Number)x.get("total_sleep_minutes")).intValue()).average().orElse(0);double q=rows.stream().filter(x->x.get("quality_score")!=null).mapToInt(x->((Number)x.get("quality_score")).intValue()).average().orElse(0);double e=rows.stream().filter(x->x.get("morning_energy")!=null).mapToInt(x->((Number)x.get("morning_energy")).intValue()).average().orElse(0);int debt=rows.stream().mapToInt(x->Math.max(0,GOAL-((Number)x.get("total_sleep_minutes")).intValue())).sum();return Map.of("days",n,"records",rows.size(),"averageSleepMinutes",Math.round(avg),"averageQuality",q,"averageEnergy",e,"goalMinutes",GOAL,"goalCompletionPercentage",avg==0?0:Math.round(avg*100/GOAL),"sleepDebtMinutes",debt,"currentStreak",streak(rows),"series",rows);}
 private int streak(List<Map<String,Object>> rows){int s=0;LocalDate expected=LocalDate.now();for(int i=rows.size()-1;i>=0;i--){Object value=rows.get(i).get("sleep_date");LocalDate d=value instanceof LocalDate l?l:((java.sql.Date)value).toLocalDate();if(!d.equals(expected))break;s++;expected=expected.minusDays(1);}return s;}
 private Map<String,Object> owned(UUID id){return db.queryForList("SELECT * FROM sleep_session WHERE id=? AND user_id=?",id,CurrentUser.id()).stream().findFirst().orElseThrow(()->bad("SLEEP_NOT_FOUND","Registro de sueño no encontrado"));}
 private void validate(Input r){if(r==null||r.sleepDate()==null||r.totalSleepMinutes()==null||r.totalSleepMinutes()<0||r.totalSleepMinutes()>1440||r.qualityScore()!=null&&(r.qualityScore()<1||r.qualityScore()>5)||r.morningEnergy()!=null&&(r.morningEnergy()<1||r.morningEnergy()>5))throw bad("INVALID_SLEEP","Revisa duración, calidad y energía");}
 private static ResponseStatusException bad(String c,String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}
 public record Input(LocalDate sleepDate,Integer totalSleepMinutes,Integer qualityScore,Integer morningEnergy,LocalTime bedTime,LocalTime wakeTime,String notes){}
}
